// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportStatus 描述当前导入任务的可观测状态，供前端轮询展示进度条。
 */
export interface ImportStatus {
    /**
     * 是否正在导入
     */
    "running": boolean;

    /**
     * 当前阶段描述（解压/清空/导入表 x/y/完成等）
     */
    "stage": string;

    /**
     * 已处理表数
     */
    "current": number;

    /**
     * 总表数
     */
    "total": number;

    /**
     * 非空表示导入失败信息
     */
    "error": string;

    /**
     * 完成时间戳（UnixNano），供前端判断结果
     */
    "finished_at": number;
}
