// Code generated by ent, DO NOT EDIT.

package httplog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the httplog type in the database.
	Label = "http_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldRequestHeaders holds the string denoting the request_headers field in the database.
	FieldRequestHeaders = "request_headers"
	// FieldRequestBody holds the string denoting the request_body field in the database.
	FieldRequestBody = "request_body"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldResponseHeaders holds the string denoting the response_headers field in the database.
	FieldResponseHeaders = "response_headers"
	// FieldResponseBody holds the string denoting the response_body field in the database.
	FieldResponseBody = "response_body"
	// FieldElapseTime holds the string denoting the elapse_time field in the database.
	FieldElapseTime = "elapse_time"
	// FieldProcessElapseTime holds the string denoting the process_elapse_time field in the database.
	FieldProcessElapseTime = "process_elapse_time"
	// FieldIsError holds the string denoting the is_error field in the database.
	FieldIsError = "is_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldGoVersion holds the string denoting the go_version field in the database.
	FieldGoVersion = "go_version"
	// FieldPluginVersion holds the string denoting the plugin_version field in the database.
	FieldPluginVersion = "plugin_version"
	// Table holds the table name of the httplog in the database.
	Table = "http_log"
)

// Columns holds all SQL columns for httplog fields.
var Columns = []string{
	FieldID,
	FieldHostname,
	FieldMethod,
	FieldURL,
	FieldRequestHeaders,
	FieldRequestBody,
	FieldStatusCode,
	FieldResponseHeaders,
	FieldResponseBody,
	FieldElapseTime,
	FieldProcessElapseTime,
	FieldIsError,
	FieldCreatedAt,
	FieldGoVersion,
	FieldPluginVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsError holds the default value on creation for the "is_error" field.
	DefaultIsError bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the HttpLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByElapseTime orders the results by the elapse_time field.
func ByElapseTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldElapseTime, opts...).ToFunc()
}

// ByProcessElapseTime orders the results by the process_elapse_time field.
func ByProcessElapseTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessElapseTime, opts...).ToFunc()
}

// ByIsError orders the results by the is_error field.
func ByIsError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGoVersion orders the results by the go_version field.
func ByGoVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGoVersion, opts...).ToFunc()
}

// ByPluginVersion orders the results by the plugin_version field.
func ByPluginVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginVersion, opts...).ToFunc()
}
