// Code generated by ent, DO NOT EDIT.

package passkeycredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the passkeycredential type in the database.
	Label = "passkey_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCredentialID holds the string denoting the credential_id field in the database.
	FieldCredentialID = "credential_id"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldSignCount holds the string denoting the sign_count field in the database.
	FieldSignCount = "sign_count"
	// FieldAttestationType holds the string denoting the attestation_type field in the database.
	FieldAttestationType = "attestation_type"
	// FieldAuthenticatorAaguid holds the string denoting the authenticator_aaguid field in the database.
	FieldAuthenticatorAaguid = "authenticator_aaguid"
	// FieldAuthenticatorPublicKey holds the string denoting the authenticator_public_key field in the database.
	FieldAuthenticatorPublicKey = "authenticator_public_key"
	// FieldAuthMethodID holds the string denoting the auth_method_id field in the database.
	FieldAuthMethodID = "auth_method_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAuthMethod holds the string denoting the auth_method edge name in mutations.
	EdgeAuthMethod = "auth_method"
	// Table holds the table name of the passkeycredential in the database.
	Table = "passkey_credentials"
	// AuthMethodTable is the table that holds the auth_method relation/edge.
	AuthMethodTable = "passkey_credentials"
	// AuthMethodInverseTable is the table name for the AuthMethod entity.
	// It exists in this package in order to avoid circular dependency with the "authmethod" package.
	AuthMethodInverseTable = "auth_methods"
	// AuthMethodColumn is the table column denoting the auth_method relation/edge.
	AuthMethodColumn = "auth_method_id"
)

// Columns holds all SQL columns for passkeycredential fields.
var Columns = []string{
	FieldID,
	FieldCredentialID,
	FieldPublicKey,
	FieldSignCount,
	FieldAttestationType,
	FieldAuthenticatorAaguid,
	FieldAuthenticatorPublicKey,
	FieldAuthMethodID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CredentialIDValidator is a validator for the "credential_id" field. It is called by the builders before save.
	CredentialIDValidator func([]byte) error
	// PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	PublicKeyValidator func([]byte) error
	// DefaultSignCount holds the default value on creation for the "sign_count" field.
	DefaultSignCount uint64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PasskeyCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySignCount orders the results by the sign_count field.
func BySignCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignCount, opts...).ToFunc()
}

// ByAttestationType orders the results by the attestation_type field.
func ByAttestationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttestationType, opts...).ToFunc()
}

// ByAuthenticatorAaguid orders the results by the authenticator_aaguid field.
func ByAuthenticatorAaguid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthenticatorAaguid, opts...).ToFunc()
}

// ByAuthMethodID orders the results by the auth_method_id field.
func ByAuthMethodID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMethodID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAuthMethodField orders the results by auth_method field.
func ByAuthMethodField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthMethodStep(), sql.OrderByField(field, opts...))
	}
}
func newAuthMethodStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthMethodInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthMethodTable, AuthMethodColumn),
	)
}
