// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"cnb.cool/dtapp/certflow/internal/ent/deploylog"
	"cnb.cool/dtapp/certflow/internal/ent/deploytarget"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DeployLog is the model entity for the DeployLog schema.
type DeployLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 证书 ID
	CertID int `json:"cert_id,omitempty"`
	// 证书主域名
	CertDomain string `json:"cert_domain,omitempty"`
	// 实际部署到的域名 / CDN 域名
	DeployDomain string `json:"deploy_domain,omitempty"`
	// 部署目标名称（冗余，便于历史查看）
	TargetName string `json:"target_name,omitempty"`
	// 云厂商
	ProviderType string `json:"provider_type,omitempty"`
	// 部署服务
	DeployService string `json:"deploy_service,omitempty"`
	// 是否成功
	Success bool `json:"success,omitempty"`
	// 结果 / 错误信息
	Message string `json:"message,omitempty"`
	// 接口原始反馈 / 响应体（便于排查云端返回）
	Response string `json:"response,omitempty"`
	// 云厂商证书 ID
	CloudCertID string `json:"cloud_cert_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeployLogQuery when eager-loading is set.
	Edges                     DeployLogEdges `json:"edges"`
	deploy_target_deploy_logs *int
	selectValues              sql.SelectValues
}

// DeployLogEdges holds the relations/edges for other nodes in the graph.
type DeployLogEdges struct {
	// 所属部署目标
	DeployTarget *DeployTarget `json:"deploy_target,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeployTargetOrErr returns the DeployTarget value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeployLogEdges) DeployTargetOrErr() (*DeployTarget, error) {
	if e.DeployTarget != nil {
		return e.DeployTarget, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: deploytarget.Label}
	}
	return nil, &NotLoadedError{edge: "deploy_target"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeployLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deploylog.FieldSuccess:
			values[i] = new(sql.NullBool)
		case deploylog.FieldID, deploylog.FieldCertID:
			values[i] = new(sql.NullInt64)
		case deploylog.FieldCertDomain, deploylog.FieldDeployDomain, deploylog.FieldTargetName, deploylog.FieldProviderType, deploylog.FieldDeployService, deploylog.FieldMessage, deploylog.FieldResponse, deploylog.FieldCloudCertID:
			values[i] = new(sql.NullString)
		case deploylog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case deploylog.ForeignKeys[0]: // deploy_target_deploy_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeployLog fields.
func (_m *DeployLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deploylog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case deploylog.FieldCertID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cert_id", values[i])
			} else if value.Valid {
				_m.CertID = int(value.Int64)
			}
		case deploylog.FieldCertDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cert_domain", values[i])
			} else if value.Valid {
				_m.CertDomain = value.String
			}
		case deploylog.FieldDeployDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deploy_domain", values[i])
			} else if value.Valid {
				_m.DeployDomain = value.String
			}
		case deploylog.FieldTargetName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_name", values[i])
			} else if value.Valid {
				_m.TargetName = value.String
			}
		case deploylog.FieldProviderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_type", values[i])
			} else if value.Valid {
				_m.ProviderType = value.String
			}
		case deploylog.FieldDeployService:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deploy_service", values[i])
			} else if value.Valid {
				_m.DeployService = value.String
			}
		case deploylog.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		case deploylog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case deploylog.FieldResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response", values[i])
			} else if value.Valid {
				_m.Response = value.String
			}
		case deploylog.FieldCloudCertID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cloud_cert_id", values[i])
			} else if value.Valid {
				_m.CloudCertID = value.String
			}
		case deploylog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deploylog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field deploy_target_deploy_logs", value)
			} else if value.Valid {
				_m.deploy_target_deploy_logs = new(int)
				*_m.deploy_target_deploy_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeployLog.
// This includes values selected through modifiers, order, etc.
func (_m *DeployLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDeployTarget queries the "deploy_target" edge of the DeployLog entity.
func (_m *DeployLog) QueryDeployTarget() *DeployTargetQuery {
	return NewDeployLogClient(_m.config).QueryDeployTarget(_m)
}

// Update returns a builder for updating this DeployLog.
// Note that you need to call DeployLog.Unwrap() before calling this method if this DeployLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DeployLog) Update() *DeployLogUpdateOne {
	return NewDeployLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DeployLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeployLog) Unwrap() *DeployLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeployLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeployLog) String() string {
	var builder strings.Builder
	builder.WriteString("DeployLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cert_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CertID))
	builder.WriteString(", ")
	builder.WriteString("cert_domain=")
	builder.WriteString(_m.CertDomain)
	builder.WriteString(", ")
	builder.WriteString("deploy_domain=")
	builder.WriteString(_m.DeployDomain)
	builder.WriteString(", ")
	builder.WriteString("target_name=")
	builder.WriteString(_m.TargetName)
	builder.WriteString(", ")
	builder.WriteString("provider_type=")
	builder.WriteString(_m.ProviderType)
	builder.WriteString(", ")
	builder.WriteString("deploy_service=")
	builder.WriteString(_m.DeployService)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("response=")
	builder.WriteString(_m.Response)
	builder.WriteString(", ")
	builder.WriteString("cloud_cert_id=")
	builder.WriteString(_m.CloudCertID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeployLogs is a parsable slice of DeployLog.
type DeployLogs []*DeployLog
