// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cnb.cool/dtapp/certflow/internal/ent/certificate"
	"cnb.cool/dtapp/certflow/internal/ent/deploytarget"
	"cnb.cool/dtapp/certflow/internal/ent/dnsprovider"
	"cnb.cool/dtapp/certflow/internal/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DNSProviderUpdate is the builder for updating DNSProvider entities.
type DNSProviderUpdate struct {
	config
	hooks    []Hook
	mutation *DNSProviderMutation
}

// Where appends a list predicates to the DNSProviderUpdate builder.
func (_u *DNSProviderUpdate) Where(ps ...predicate.DNSProvider) *DNSProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DNSProviderUpdate) SetName(v string) *DNSProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DNSProviderUpdate) SetNillableName(v *string) *DNSProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DNSProviderUpdate) SetProviderType(v dnsprovider.ProviderType) *DNSProviderUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DNSProviderUpdate) SetNillableProviderType(v *dnsprovider.ProviderType) *DNSProviderUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DNSProviderUpdate) SetConfig(v []byte) *DNSProviderUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DNSProviderUpdate) ClearConfig() *DNSProviderUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DNSProviderUpdate) SetIsActive(v bool) *DNSProviderUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DNSProviderUpdate) SetNillableIsActive(v *bool) *DNSProviderUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DNSProviderUpdate) SetComment(v string) *DNSProviderUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DNSProviderUpdate) SetNillableComment(v *string) *DNSProviderUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *DNSProviderUpdate) ClearComment() *DNSProviderUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DNSProviderUpdate) SetUpdatedAt(v time.Time) *DNSProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCertificateIDs adds the "certificates" edge to the Certificate entity by IDs.
func (_u *DNSProviderUpdate) AddCertificateIDs(ids ...int) *DNSProviderUpdate {
	_u.mutation.AddCertificateIDs(ids...)
	return _u
}

// AddCertificates adds the "certificates" edges to the Certificate entity.
func (_u *DNSProviderUpdate) AddCertificates(v ...*Certificate) *DNSProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCertificateIDs(ids...)
}

// AddDeployTargetIDs adds the "deploy_targets" edge to the DeployTarget entity by IDs.
func (_u *DNSProviderUpdate) AddDeployTargetIDs(ids ...int) *DNSProviderUpdate {
	_u.mutation.AddDeployTargetIDs(ids...)
	return _u
}

// AddDeployTargets adds the "deploy_targets" edges to the DeployTarget entity.
func (_u *DNSProviderUpdate) AddDeployTargets(v ...*DeployTarget) *DNSProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTargetIDs(ids...)
}

// Mutation returns the DNSProviderMutation object of the builder.
func (_u *DNSProviderUpdate) Mutation() *DNSProviderMutation {
	return _u.mutation
}

// ClearCertificates clears all "certificates" edges to the Certificate entity.
func (_u *DNSProviderUpdate) ClearCertificates() *DNSProviderUpdate {
	_u.mutation.ClearCertificates()
	return _u
}

// RemoveCertificateIDs removes the "certificates" edge to Certificate entities by IDs.
func (_u *DNSProviderUpdate) RemoveCertificateIDs(ids ...int) *DNSProviderUpdate {
	_u.mutation.RemoveCertificateIDs(ids...)
	return _u
}

// RemoveCertificates removes "certificates" edges to Certificate entities.
func (_u *DNSProviderUpdate) RemoveCertificates(v ...*Certificate) *DNSProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCertificateIDs(ids...)
}

// ClearDeployTargets clears all "deploy_targets" edges to the DeployTarget entity.
func (_u *DNSProviderUpdate) ClearDeployTargets() *DNSProviderUpdate {
	_u.mutation.ClearDeployTargets()
	return _u
}

// RemoveDeployTargetIDs removes the "deploy_targets" edge to DeployTarget entities by IDs.
func (_u *DNSProviderUpdate) RemoveDeployTargetIDs(ids ...int) *DNSProviderUpdate {
	_u.mutation.RemoveDeployTargetIDs(ids...)
	return _u
}

// RemoveDeployTargets removes "deploy_targets" edges to DeployTarget entities.
func (_u *DNSProviderUpdate) RemoveDeployTargets(v ...*DeployTarget) *DNSProviderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTargetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DNSProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DNSProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DNSProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DNSProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DNSProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dnsprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DNSProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dnsprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DNSProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := dnsprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "DNSProvider.provider_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DNSProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnsprovider.Table, dnsprovider.Columns, sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dnsprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(dnsprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(dnsprovider.FieldConfig, field.TypeBytes, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(dnsprovider.FieldConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(dnsprovider.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(dnsprovider.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(dnsprovider.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dnsprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCertificatesIDs(); len(nodes) > 0 && !_u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTargetsIDs(); len(nodes) > 0 && !_u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DNSProviderUpdateOne is the builder for updating a single DNSProvider entity.
type DNSProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DNSProviderMutation
}

// SetName sets the "name" field.
func (_u *DNSProviderUpdateOne) SetName(v string) *DNSProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DNSProviderUpdateOne) SetNillableName(v *string) *DNSProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DNSProviderUpdateOne) SetProviderType(v dnsprovider.ProviderType) *DNSProviderUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DNSProviderUpdateOne) SetNillableProviderType(v *dnsprovider.ProviderType) *DNSProviderUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DNSProviderUpdateOne) SetConfig(v []byte) *DNSProviderUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DNSProviderUpdateOne) ClearConfig() *DNSProviderUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DNSProviderUpdateOne) SetIsActive(v bool) *DNSProviderUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DNSProviderUpdateOne) SetNillableIsActive(v *bool) *DNSProviderUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DNSProviderUpdateOne) SetComment(v string) *DNSProviderUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DNSProviderUpdateOne) SetNillableComment(v *string) *DNSProviderUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *DNSProviderUpdateOne) ClearComment() *DNSProviderUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DNSProviderUpdateOne) SetUpdatedAt(v time.Time) *DNSProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddCertificateIDs adds the "certificates" edge to the Certificate entity by IDs.
func (_u *DNSProviderUpdateOne) AddCertificateIDs(ids ...int) *DNSProviderUpdateOne {
	_u.mutation.AddCertificateIDs(ids...)
	return _u
}

// AddCertificates adds the "certificates" edges to the Certificate entity.
func (_u *DNSProviderUpdateOne) AddCertificates(v ...*Certificate) *DNSProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCertificateIDs(ids...)
}

// AddDeployTargetIDs adds the "deploy_targets" edge to the DeployTarget entity by IDs.
func (_u *DNSProviderUpdateOne) AddDeployTargetIDs(ids ...int) *DNSProviderUpdateOne {
	_u.mutation.AddDeployTargetIDs(ids...)
	return _u
}

// AddDeployTargets adds the "deploy_targets" edges to the DeployTarget entity.
func (_u *DNSProviderUpdateOne) AddDeployTargets(v ...*DeployTarget) *DNSProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTargetIDs(ids...)
}

// Mutation returns the DNSProviderMutation object of the builder.
func (_u *DNSProviderUpdateOne) Mutation() *DNSProviderMutation {
	return _u.mutation
}

// ClearCertificates clears all "certificates" edges to the Certificate entity.
func (_u *DNSProviderUpdateOne) ClearCertificates() *DNSProviderUpdateOne {
	_u.mutation.ClearCertificates()
	return _u
}

// RemoveCertificateIDs removes the "certificates" edge to Certificate entities by IDs.
func (_u *DNSProviderUpdateOne) RemoveCertificateIDs(ids ...int) *DNSProviderUpdateOne {
	_u.mutation.RemoveCertificateIDs(ids...)
	return _u
}

// RemoveCertificates removes "certificates" edges to Certificate entities.
func (_u *DNSProviderUpdateOne) RemoveCertificates(v ...*Certificate) *DNSProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCertificateIDs(ids...)
}

// ClearDeployTargets clears all "deploy_targets" edges to the DeployTarget entity.
func (_u *DNSProviderUpdateOne) ClearDeployTargets() *DNSProviderUpdateOne {
	_u.mutation.ClearDeployTargets()
	return _u
}

// RemoveDeployTargetIDs removes the "deploy_targets" edge to DeployTarget entities by IDs.
func (_u *DNSProviderUpdateOne) RemoveDeployTargetIDs(ids ...int) *DNSProviderUpdateOne {
	_u.mutation.RemoveDeployTargetIDs(ids...)
	return _u
}

// RemoveDeployTargets removes "deploy_targets" edges to DeployTarget entities.
func (_u *DNSProviderUpdateOne) RemoveDeployTargets(v ...*DeployTarget) *DNSProviderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTargetIDs(ids...)
}

// Where appends a list predicates to the DNSProviderUpdate builder.
func (_u *DNSProviderUpdateOne) Where(ps ...predicate.DNSProvider) *DNSProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DNSProviderUpdateOne) Select(field string, fields ...string) *DNSProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DNSProvider entity.
func (_u *DNSProviderUpdateOne) Save(ctx context.Context) (*DNSProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DNSProviderUpdateOne) SaveX(ctx context.Context) *DNSProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DNSProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DNSProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DNSProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dnsprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DNSProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dnsprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DNSProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := dnsprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "DNSProvider.provider_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DNSProviderUpdateOne) sqlSave(ctx context.Context) (_node *DNSProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dnsprovider.Table, dnsprovider.Columns, sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DNSProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dnsprovider.FieldID)
		for _, f := range fields {
			if !dnsprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dnsprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dnsprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(dnsprovider.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(dnsprovider.FieldConfig, field.TypeBytes, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(dnsprovider.FieldConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(dnsprovider.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(dnsprovider.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(dnsprovider.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dnsprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCertificatesIDs(); len(nodes) > 0 && !_u.mutation.CertificatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.CertificatesTable,
			Columns: []string{dnsprovider.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTargetsIDs(); len(nodes) > 0 && !_u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dnsprovider.DeployTargetsTable,
			Columns: []string{dnsprovider.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DNSProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dnsprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
