// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"cnb.cool/dtapp/certflow/internal/ent/monitorchecklog"
	"cnb.cool/dtapp/certflow/internal/ent/monitoreddomain"
	"cnb.cool/dtapp/certflow/internal/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitoredDomainQuery is the builder for querying MonitoredDomain entities.
type MonitoredDomainQuery struct {
	config
	ctx           *QueryContext
	order         []monitoreddomain.OrderOption
	inters        []Interceptor
	predicates    []predicate.MonitoredDomain
	withCheckLogs *MonitorCheckLogQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MonitoredDomainQuery builder.
func (_q *MonitoredDomainQuery) Where(ps ...predicate.MonitoredDomain) *MonitoredDomainQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MonitoredDomainQuery) Limit(limit int) *MonitoredDomainQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MonitoredDomainQuery) Offset(offset int) *MonitoredDomainQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MonitoredDomainQuery) Unique(unique bool) *MonitoredDomainQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MonitoredDomainQuery) Order(o ...monitoreddomain.OrderOption) *MonitoredDomainQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCheckLogs chains the current query on the "check_logs" edge.
func (_q *MonitoredDomainQuery) QueryCheckLogs() *MonitorCheckLogQuery {
	query := (&MonitorCheckLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(monitoreddomain.Table, monitoreddomain.FieldID, selector),
			sqlgraph.To(monitorchecklog.Table, monitorchecklog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, monitoreddomain.CheckLogsTable, monitoreddomain.CheckLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MonitoredDomain entity from the query.
// Returns a *NotFoundError when no MonitoredDomain was found.
func (_q *MonitoredDomainQuery) First(ctx context.Context) (*MonitoredDomain, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{monitoreddomain.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MonitoredDomainQuery) FirstX(ctx context.Context) *MonitoredDomain {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MonitoredDomain ID from the query.
// Returns a *NotFoundError when no MonitoredDomain ID was found.
func (_q *MonitoredDomainQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{monitoreddomain.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MonitoredDomainQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MonitoredDomain entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MonitoredDomain entity is found.
// Returns a *NotFoundError when no MonitoredDomain entities are found.
func (_q *MonitoredDomainQuery) Only(ctx context.Context) (*MonitoredDomain, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{monitoreddomain.Label}
	default:
		return nil, &NotSingularError{monitoreddomain.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MonitoredDomainQuery) OnlyX(ctx context.Context) *MonitoredDomain {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MonitoredDomain ID in the query.
// Returns a *NotSingularError when more than one MonitoredDomain ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MonitoredDomainQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{monitoreddomain.Label}
	default:
		err = &NotSingularError{monitoreddomain.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MonitoredDomainQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MonitoredDomains.
func (_q *MonitoredDomainQuery) All(ctx context.Context) ([]*MonitoredDomain, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MonitoredDomain, *MonitoredDomainQuery]()
	return withInterceptors[[]*MonitoredDomain](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MonitoredDomainQuery) AllX(ctx context.Context) []*MonitoredDomain {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MonitoredDomain IDs.
func (_q *MonitoredDomainQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(monitoreddomain.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MonitoredDomainQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MonitoredDomainQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MonitoredDomainQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MonitoredDomainQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MonitoredDomainQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MonitoredDomainQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MonitoredDomainQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MonitoredDomainQuery) Clone() *MonitoredDomainQuery {
	if _q == nil {
		return nil
	}
	return &MonitoredDomainQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]monitoreddomain.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.MonitoredDomain{}, _q.predicates...),
		withCheckLogs: _q.withCheckLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCheckLogs tells the query-builder to eager-load the nodes that are connected to
// the "check_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MonitoredDomainQuery) WithCheckLogs(opts ...func(*MonitorCheckLogQuery)) *MonitoredDomainQuery {
	query := (&MonitorCheckLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCheckLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Domain string `json:"domain,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MonitoredDomain.Query().
//		GroupBy(monitoreddomain.FieldDomain).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MonitoredDomainQuery) GroupBy(field string, fields ...string) *MonitoredDomainGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MonitoredDomainGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = monitoreddomain.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Domain string `json:"domain,omitempty"`
//	}
//
//	client.MonitoredDomain.Query().
//		Select(monitoreddomain.FieldDomain).
//		Scan(ctx, &v)
func (_q *MonitoredDomainQuery) Select(fields ...string) *MonitoredDomainSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MonitoredDomainSelect{MonitoredDomainQuery: _q}
	sbuild.label = monitoreddomain.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MonitoredDomainSelect configured with the given aggregations.
func (_q *MonitoredDomainQuery) Aggregate(fns ...AggregateFunc) *MonitoredDomainSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MonitoredDomainQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !monitoreddomain.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MonitoredDomainQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MonitoredDomain, error) {
	var (
		nodes       = []*MonitoredDomain{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withCheckLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MonitoredDomain).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MonitoredDomain{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCheckLogs; query != nil {
		if err := _q.loadCheckLogs(ctx, query, nodes,
			func(n *MonitoredDomain) { n.Edges.CheckLogs = []*MonitorCheckLog{} },
			func(n *MonitoredDomain, e *MonitorCheckLog) { n.Edges.CheckLogs = append(n.Edges.CheckLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MonitoredDomainQuery) loadCheckLogs(ctx context.Context, query *MonitorCheckLogQuery, nodes []*MonitoredDomain, init func(*MonitoredDomain), assign func(*MonitoredDomain, *MonitorCheckLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MonitoredDomain)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MonitorCheckLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(monitoreddomain.CheckLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.monitored_domain_check_logs
		if fk == nil {
			return fmt.Errorf(`foreign-key "monitored_domain_check_logs" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "monitored_domain_check_logs" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MonitoredDomainQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MonitoredDomainQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(monitoreddomain.Table, monitoreddomain.Columns, sqlgraph.NewFieldSpec(monitoreddomain.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitoreddomain.FieldID)
		for i := range fields {
			if fields[i] != monitoreddomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MonitoredDomainQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(monitoreddomain.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = monitoreddomain.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MonitoredDomainGroupBy is the group-by builder for MonitoredDomain entities.
type MonitoredDomainGroupBy struct {
	selector
	build *MonitoredDomainQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MonitoredDomainGroupBy) Aggregate(fns ...AggregateFunc) *MonitoredDomainGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MonitoredDomainGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitoredDomainQuery, *MonitoredDomainGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MonitoredDomainGroupBy) sqlScan(ctx context.Context, root *MonitoredDomainQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MonitoredDomainSelect is the builder for selecting fields of MonitoredDomain entities.
type MonitoredDomainSelect struct {
	*MonitoredDomainQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MonitoredDomainSelect) Aggregate(fns ...AggregateFunc) *MonitoredDomainSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MonitoredDomainSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MonitoredDomainQuery, *MonitoredDomainSelect](ctx, _s.MonitoredDomainQuery, _s, _s.inters, v)
}

func (_s *MonitoredDomainSelect) sqlScan(ctx context.Context, root *MonitoredDomainQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
