// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"cnb.cool/dtapp/certflow/internal/ent/authmethod"
	"cnb.cool/dtapp/certflow/internal/ent/passkeycredential"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PasskeyCredential is the model entity for the PasskeyCredential schema.
type PasskeyCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WebAuthn 凭据 ID
	CredentialID []byte `json:"credential_id,omitempty"`
	// 公钥（CBOR 编码）
	PublicKey []byte `json:"public_key,omitempty"`
	// 签名计数器
	SignCount uint64 `json:"sign_count,omitempty"`
	// 证明类型
	AttestationType string `json:"attestation_type,omitempty"`
	// 认证器 AAGUID
	AuthenticatorAaguid string `json:"authenticator_aaguid,omitempty"`
	// 认证器公钥
	AuthenticatorPublicKey []byte `json:"authenticator_public_key,omitempty"`
	// 关联的认证方式 ID
	AuthMethodID int `json:"auth_method_id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasskeyCredentialQuery when eager-loading is set.
	Edges        PasskeyCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PasskeyCredentialEdges holds the relations/edges for other nodes in the graph.
type PasskeyCredentialEdges struct {
	// AuthMethod holds the value of the auth_method edge.
	AuthMethod *AuthMethod `json:"auth_method,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AuthMethodOrErr returns the AuthMethod value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasskeyCredentialEdges) AuthMethodOrErr() (*AuthMethod, error) {
	if e.AuthMethod != nil {
		return e.AuthMethod, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: authmethod.Label}
	}
	return nil, &NotLoadedError{edge: "auth_method"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasskeyCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passkeycredential.FieldCredentialID, passkeycredential.FieldPublicKey, passkeycredential.FieldAuthenticatorPublicKey:
			values[i] = new([]byte)
		case passkeycredential.FieldID, passkeycredential.FieldSignCount, passkeycredential.FieldAuthMethodID:
			values[i] = new(sql.NullInt64)
		case passkeycredential.FieldAttestationType, passkeycredential.FieldAuthenticatorAaguid:
			values[i] = new(sql.NullString)
		case passkeycredential.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasskeyCredential fields.
func (_m *PasskeyCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passkeycredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case passkeycredential.FieldCredentialID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value != nil {
				_m.CredentialID = *value
			}
		case passkeycredential.FieldPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value != nil {
				_m.PublicKey = *value
			}
		case passkeycredential.FieldSignCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sign_count", values[i])
			} else if value.Valid {
				_m.SignCount = uint64(value.Int64)
			}
		case passkeycredential.FieldAttestationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attestation_type", values[i])
			} else if value.Valid {
				_m.AttestationType = value.String
			}
		case passkeycredential.FieldAuthenticatorAaguid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authenticator_aaguid", values[i])
			} else if value.Valid {
				_m.AuthenticatorAaguid = value.String
			}
		case passkeycredential.FieldAuthenticatorPublicKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field authenticator_public_key", values[i])
			} else if value != nil {
				_m.AuthenticatorPublicKey = *value
			}
		case passkeycredential.FieldAuthMethodID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auth_method_id", values[i])
			} else if value.Valid {
				_m.AuthMethodID = int(value.Int64)
			}
		case passkeycredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasskeyCredential.
// This includes values selected through modifiers, order, etc.
func (_m *PasskeyCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthMethod queries the "auth_method" edge of the PasskeyCredential entity.
func (_m *PasskeyCredential) QueryAuthMethod() *AuthMethodQuery {
	return NewPasskeyCredentialClient(_m.config).QueryAuthMethod(_m)
}

// Update returns a builder for updating this PasskeyCredential.
// Note that you need to call PasskeyCredential.Unwrap() before calling this method if this PasskeyCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PasskeyCredential) Update() *PasskeyCredentialUpdateOne {
	return NewPasskeyCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PasskeyCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PasskeyCredential) Unwrap() *PasskeyCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasskeyCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PasskeyCredential) String() string {
	var builder strings.Builder
	builder.WriteString("PasskeyCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("credential_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CredentialID))
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicKey))
	builder.WriteString(", ")
	builder.WriteString("sign_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SignCount))
	builder.WriteString(", ")
	builder.WriteString("attestation_type=")
	builder.WriteString(_m.AttestationType)
	builder.WriteString(", ")
	builder.WriteString("authenticator_aaguid=")
	builder.WriteString(_m.AuthenticatorAaguid)
	builder.WriteString(", ")
	builder.WriteString("authenticator_public_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthenticatorPublicKey))
	builder.WriteString(", ")
	builder.WriteString("auth_method_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMethodID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PasskeyCredentials is a parsable slice of PasskeyCredential.
type PasskeyCredentials []*PasskeyCredential
