// Code generated by ent, DO NOT EDIT.

package certupload

import (
	"time"

	"cnb.cool/dtapp/certflow/ent/predicate"
	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldID, id))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldProvider, v))
}

// AccessKeyID applies equality check predicate on the "access_key_id" field. It's identical to AccessKeyIDEQ.
func AccessKeyID(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldAccessKeyID, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldRegion, v))
}

// CertFingerprint applies equality check predicate on the "cert_fingerprint" field. It's identical to CertFingerprintEQ.
func CertFingerprint(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCertFingerprint, v))
}

// CloudCertID applies equality check predicate on the "cloud_cert_id" field. It's identical to CloudCertIDEQ.
func CloudCertID(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCloudCertID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContainsFold(FieldProvider, v))
}

// AccessKeyIDEQ applies the EQ predicate on the "access_key_id" field.
func AccessKeyIDEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldAccessKeyID, v))
}

// AccessKeyIDNEQ applies the NEQ predicate on the "access_key_id" field.
func AccessKeyIDNEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldAccessKeyID, v))
}

// AccessKeyIDIn applies the In predicate on the "access_key_id" field.
func AccessKeyIDIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldAccessKeyID, vs...))
}

// AccessKeyIDNotIn applies the NotIn predicate on the "access_key_id" field.
func AccessKeyIDNotIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldAccessKeyID, vs...))
}

// AccessKeyIDGT applies the GT predicate on the "access_key_id" field.
func AccessKeyIDGT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldAccessKeyID, v))
}

// AccessKeyIDGTE applies the GTE predicate on the "access_key_id" field.
func AccessKeyIDGTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldAccessKeyID, v))
}

// AccessKeyIDLT applies the LT predicate on the "access_key_id" field.
func AccessKeyIDLT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldAccessKeyID, v))
}

// AccessKeyIDLTE applies the LTE predicate on the "access_key_id" field.
func AccessKeyIDLTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldAccessKeyID, v))
}

// AccessKeyIDContains applies the Contains predicate on the "access_key_id" field.
func AccessKeyIDContains(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContains(FieldAccessKeyID, v))
}

// AccessKeyIDHasPrefix applies the HasPrefix predicate on the "access_key_id" field.
func AccessKeyIDHasPrefix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasPrefix(FieldAccessKeyID, v))
}

// AccessKeyIDHasSuffix applies the HasSuffix predicate on the "access_key_id" field.
func AccessKeyIDHasSuffix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasSuffix(FieldAccessKeyID, v))
}

// AccessKeyIDEqualFold applies the EqualFold predicate on the "access_key_id" field.
func AccessKeyIDEqualFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEqualFold(FieldAccessKeyID, v))
}

// AccessKeyIDContainsFold applies the ContainsFold predicate on the "access_key_id" field.
func AccessKeyIDContainsFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContainsFold(FieldAccessKeyID, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContainsFold(FieldRegion, v))
}

// CertFingerprintEQ applies the EQ predicate on the "cert_fingerprint" field.
func CertFingerprintEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCertFingerprint, v))
}

// CertFingerprintNEQ applies the NEQ predicate on the "cert_fingerprint" field.
func CertFingerprintNEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldCertFingerprint, v))
}

// CertFingerprintIn applies the In predicate on the "cert_fingerprint" field.
func CertFingerprintIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldCertFingerprint, vs...))
}

// CertFingerprintNotIn applies the NotIn predicate on the "cert_fingerprint" field.
func CertFingerprintNotIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldCertFingerprint, vs...))
}

// CertFingerprintGT applies the GT predicate on the "cert_fingerprint" field.
func CertFingerprintGT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldCertFingerprint, v))
}

// CertFingerprintGTE applies the GTE predicate on the "cert_fingerprint" field.
func CertFingerprintGTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldCertFingerprint, v))
}

// CertFingerprintLT applies the LT predicate on the "cert_fingerprint" field.
func CertFingerprintLT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldCertFingerprint, v))
}

// CertFingerprintLTE applies the LTE predicate on the "cert_fingerprint" field.
func CertFingerprintLTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldCertFingerprint, v))
}

// CertFingerprintContains applies the Contains predicate on the "cert_fingerprint" field.
func CertFingerprintContains(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContains(FieldCertFingerprint, v))
}

// CertFingerprintHasPrefix applies the HasPrefix predicate on the "cert_fingerprint" field.
func CertFingerprintHasPrefix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasPrefix(FieldCertFingerprint, v))
}

// CertFingerprintHasSuffix applies the HasSuffix predicate on the "cert_fingerprint" field.
func CertFingerprintHasSuffix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasSuffix(FieldCertFingerprint, v))
}

// CertFingerprintEqualFold applies the EqualFold predicate on the "cert_fingerprint" field.
func CertFingerprintEqualFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEqualFold(FieldCertFingerprint, v))
}

// CertFingerprintContainsFold applies the ContainsFold predicate on the "cert_fingerprint" field.
func CertFingerprintContainsFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContainsFold(FieldCertFingerprint, v))
}

// CloudCertIDEQ applies the EQ predicate on the "cloud_cert_id" field.
func CloudCertIDEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCloudCertID, v))
}

// CloudCertIDNEQ applies the NEQ predicate on the "cloud_cert_id" field.
func CloudCertIDNEQ(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldCloudCertID, v))
}

// CloudCertIDIn applies the In predicate on the "cloud_cert_id" field.
func CloudCertIDIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldCloudCertID, vs...))
}

// CloudCertIDNotIn applies the NotIn predicate on the "cloud_cert_id" field.
func CloudCertIDNotIn(vs ...string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldCloudCertID, vs...))
}

// CloudCertIDGT applies the GT predicate on the "cloud_cert_id" field.
func CloudCertIDGT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldCloudCertID, v))
}

// CloudCertIDGTE applies the GTE predicate on the "cloud_cert_id" field.
func CloudCertIDGTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldCloudCertID, v))
}

// CloudCertIDLT applies the LT predicate on the "cloud_cert_id" field.
func CloudCertIDLT(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldCloudCertID, v))
}

// CloudCertIDLTE applies the LTE predicate on the "cloud_cert_id" field.
func CloudCertIDLTE(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldCloudCertID, v))
}

// CloudCertIDContains applies the Contains predicate on the "cloud_cert_id" field.
func CloudCertIDContains(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContains(FieldCloudCertID, v))
}

// CloudCertIDHasPrefix applies the HasPrefix predicate on the "cloud_cert_id" field.
func CloudCertIDHasPrefix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasPrefix(FieldCloudCertID, v))
}

// CloudCertIDHasSuffix applies the HasSuffix predicate on the "cloud_cert_id" field.
func CloudCertIDHasSuffix(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldHasSuffix(FieldCloudCertID, v))
}

// CloudCertIDEqualFold applies the EqualFold predicate on the "cloud_cert_id" field.
func CloudCertIDEqualFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEqualFold(FieldCloudCertID, v))
}

// CloudCertIDContainsFold applies the ContainsFold predicate on the "cloud_cert_id" field.
func CloudCertIDContainsFold(v string) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldContainsFold(FieldCloudCertID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CertUpload {
	return predicate.CertUpload(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CertUpload) predicate.CertUpload {
	return predicate.CertUpload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CertUpload) predicate.CertUpload {
	return predicate.CertUpload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CertUpload) predicate.CertUpload {
	return predicate.CertUpload(sql.NotPredicates(p))
}
