// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DNSProviderConfig 是 DNS 提供商配置的统一结构体。
 * 包含所有厂商可能的字段，按 provider_type 不同使用不同字段。
 * 敏感字段以 secret:"true" 标记，便于通过 config.StripSecrets 向前端返回时剔除。
 */
export interface DNSProviderConfig {
    /**
     * 云厂商 AK/SK 类
     */
    "access_key_id"?: string;
    "access_key_secret"?: string;
    "secret_access_key"?: string;
    "access_key"?: string;
    "secret_key"?: string;
    "secret_id"?: string;

    /**
     * 区域
     */
    "region"?: string;
    "region_id"?: string;

    /**
     * API Token / Key 类
     */
    "api_token"?: string;
    "api_key"?: string;
    "api_secret"?: string;
    "application_key"?: string;
    "application_secret"?: string;
    "consumer_key"?: string;
    "auth_token"?: string;
    "personal_access_token"?: string;
    "token"?: string;
    "access_token"?: string;

    /**
     * 邮箱
     */
    "email"?: string;

    /**
     * 密码类
     */
    "password"?: string;
    "client_secret"?: string;

    /**
     * Azure 特有
     */
    "subscription_id"?: string;
    "resource_group"?: string;
    "client_id"?: string;
    "tenant_id"?: string;

    /**
     * 面板类
     */
    "public_key"?: string;
    "private_key"?: string;
    "username"?: string;

    /**
     * 其他
     */
    "agent_id"?: string;
    "auth_user_id"?: string;
    "api_id"?: string;
    "client_ip"?: string;
}

/**
 * DeployCredentialConfig 是部署凭证配置的统一结构体。
 * 包含所有厂商可能的字段（面板类和云厂商类），按 provider_type 不同使用不同字段。
 * 敏感字段以 secret:"true" 标记，便于通过 config.StripSecrets 向前端返回时剔除。
 */
export interface DeployCredentialConfig {
    /**
     * 云厂商 AK/SK 类
     */
    "access_key_id"?: string;
    "access_key_secret"?: string;
    "secret_access_key"?: string;
    "secret_id"?: string;
    "secret_key"?: string;

    /**
     * 区域
     */
    "region"?: string;
    "region_id"?: string;

    /**
     * 面板类
     */
    "api_key"?: string;
    "panel_url"?: string;
    "token_id"?: string;
    "token_secret"?: string;
    "jwt_secret"?: string;
}

/**
 * DeployTargetConfig 是部署目标配置的统一结构体。
 * 包含所有部署目标可能的字段（CDN/云厂商类和面板类），按 provider_type/deploy_service 不同使用不同字段。
 */
export interface DeployTargetConfig {
    /**
     * 区域（aliyun 用 region_id，其余用 region）
     */
    "region"?: string;
    "region_id"?: string;

    /**
     * 域名列表
     */
    "domains"?: string[] | null;

    /**
     * 云端证书名
     */
    "cert_name"?: string;

    /**
     * EdgeOne 站点
     */
    "zone_id"?: string;
    "zone_name"?: string;

    /**
     * ESA/面板站点
     */
    "site_id"?: string[] | null;
    "site_name"?: string[] | null;

    /**
     * GA 加速器
     */
    "accelerator_id"?: string;
    "listener_id"?: string;
}
