// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutostartServiceWrapper 自动启动服务包装器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Disable 禁用开机自启
 */
export function Disable(): $CancellablePromise<void> {
    return $Call.ByID(2653829671);
}

/**
 * Enable 启用开机自启
 */
export function Enable(): $CancellablePromise<void> {
    return $Call.ByID(1794523906);
}

/**
 * IsEnabled 检查是否启用开机自启
 */
export function IsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1549991474);
}

/**
 * SetApp 设置 app 引用（用于获取应用生命周期）
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4074144410, app);
}
