// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DockServiceWrapper Dock 服务包装器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetBadge 获取当前 Dock 徽章
 */
export function GetBadge(): $CancellablePromise<string | null> {
    return $Call.ByID(3507651352);
}

/**
 * HideAppIcon 隐藏 Dock 图标（仅 macOS）
 */
export function HideAppIcon(): $CancellablePromise<void> {
    return $Call.ByID(2298343515);
}

/**
 * RemoveBadge 移除 Dock 徽章
 */
export function RemoveBadge(): $CancellablePromise<void> {
    return $Call.ByID(3696035894);
}

/**
 * SetApp 设置 app 引用
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2520192168, app);
}

/**
 * SetBadge 设置 Dock 徽章
 */
export function SetBadge(label: string): $CancellablePromise<void> {
    return $Call.ByID(2539765660, label);
}

/**
 * ShowAppIcon 显示 Dock 图标（仅 macOS）
 */
export function ShowAppIcon(): $CancellablePromise<void> {
    return $Call.ByID(1135720576);
}
