// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileServiceWrapper 文件操作服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenDirectory 在系统文件管理器中打开目录
 */
export function OpenDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(4212715675, path);
}

/**
 * SetApp 设置 app 引用
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(376558635, app);
}
