// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScannerServiceWrapper 包装 scanner.ScannerService 以适配 Wails v3 服务接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanner$0 from "./internal/scanner/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * ClearHistory 清空扫描历史
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(1199909507);
}

/**
 * DeleteResult 删除扫描结果
 */
export function DeleteResult(id: number): $CancellablePromise<void> {
    return $Call.ByID(3772641310, id);
}

/**
 * ListHistory 获取扫描历史
 */
export function ListHistory(): $CancellablePromise<(scanner$0.ScanResultItem | null)[] | null> {
    return $Call.ByID(3606237364);
}

/**
 * Scan 执行一次证书扫描
 */
export function Scan(domain: string, port: number, scanType: string): $CancellablePromise<scanner$0.ScanResultItem | null> {
    return $Call.ByID(2263998317, domain, port, scanType);
}

/**
 * SetApp 设置 app 引用（用于获取应用生命周期）
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1891311383, app);
}
