// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsServiceWrapper 包装 settings.Service 以适配 Wails v3 服务接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";

/**
 * GetSettings 获取当前设置
 */
export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1954463446);
}

/**
 * SaveSettings 保存设置
 */
export function SaveSettings(input: settings$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(524082881, input);
}
