// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemServiceWrapper 提供系统信息（主题等）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetVersion 获取应用版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(301923417);
}

/**
 * IsDarkMode 检测系统是否深色模式
 */
export function IsDarkMode(): $CancellablePromise<boolean> {
    return $Call.ByID(2550514530);
}

/**
 * ReportFrontendError 接收前端运行时的错误并写入独立的 frontend.log（logging 包，
 * 等价于 slog，不混入 certflow.log）。用于在生产版本中定位前端问题：开发版可通过
 * 浏览器控制台查看报错，但发布版 esbuild 会 drop 掉 console，错误被静默吞噬，
 * 故由前端统一拦截后上报到后端落盘。
 * 参数：
 *   - level：错误级别（error/warn/info），直接进对应级别日志。
 *   - message：错误描述。
 *   - stack：错误堆栈或上下文（可为空）。
 *   - url：触发错误的页面/路由（可为空）。
 */
export function ReportFrontendError(level: string, message: string, stack: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(3798188807, level, message, stack, url);
}

/**
 * SetApp 设置 app 引用
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3339081910, app);
}

/**
 * SetUserAgent 设置全局 User-Agent（前端启动时传入 WebView 的 navigator.userAgent）。
 * 写入 internal/useragent 全局状态，所有经全局 transport（httplog 包裹）发出的
 * HTTP 请求在未显式设置 UA 时自动带上；monitor 检查请求也从该全局状态读取。
 */
export function SetUserAgent(ua: string): $CancellablePromise<void> {
    return $Call.ByID(3680343009, ua);
}

/**
 * ShowMessage 显示原生对话框（前端调用）
 */
export function ShowMessage(title: string, message: string, msgType: string): $CancellablePromise<void> {
    return $Call.ByID(1931405787, title, message, msgType);
}
