// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemServiceWrapper 提供系统信息（主题等）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * GetVersion 获取应用版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(301923417);
}

/**
 * IsDarkMode 检测系统是否深色模式
 */
export function IsDarkMode(): $CancellablePromise<boolean> {
    return $Call.ByID(2550514530);
}

/**
 * SetApp 设置 app 引用
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3339081910, app);
}

/**
 * SetMainWindow 设置主窗口引用
 */
export function SetMainWindow(w: application$0.Window): $CancellablePromise<void> {
    return $Call.ByID(1199370302, w);
}

/**
 * SetWindowAppearance 设置主窗口外观（标题栏主题）
 */
export function SetWindowAppearance(isDark: boolean): $CancellablePromise<void> {
    return $Call.ByID(258278425, isDark);
}
