// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CasColumns holds the columns for the "cas" table.
	CasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "directory_url", Type: field.TypeString},
		{Name: "account_email", Type: field.TypeString, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CasTable holds the schema information for the "cas" table.
	CasTable = &schema.Table{
		Name:       "cas",
		Columns:    CasColumns,
		PrimaryKey: []*schema.Column{CasColumns[0]},
	}
	// CertificatesColumns holds the columns for the "certificates" table.
	CertificatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "domain", Type: field.TypeString},
		{Name: "sans", Type: field.TypeJSON, Nullable: true},
		{Name: "cert_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "key_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "issuer", Type: field.TypeString, Nullable: true},
		{Name: "not_before", Type: field.TypeTime, Nullable: true},
		{Name: "not_after", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "active", "expired", "revoked", "failed"}, Default: "pending"},
		{Name: "auto_renew", Type: field.TypeBool, Default: true},
		{Name: "renewal_days", Type: field.TypeInt, Default: 30},
		{Name: "challenge_records", Type: field.TypeJSON, Nullable: true},
		{Name: "key_type", Type: field.TypeEnum, Enums: []string{"EC256", "EC384", "RSA2048", "RSA3072", "RSA4096", "RSA8192"}, Default: "EC256"},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "last_renewed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "ca_certificates", Type: field.TypeInt, Nullable: true},
		{Name: "dns_provider_certificates", Type: field.TypeInt, Nullable: true},
	}
	// CertificatesTable holds the schema information for the "certificates" table.
	CertificatesTable = &schema.Table{
		Name:       "certificates",
		Columns:    CertificatesColumns,
		PrimaryKey: []*schema.Column{CertificatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "certificates_cas_certificates",
				Columns:    []*schema.Column{CertificatesColumns[17]},
				RefColumns: []*schema.Column{CasColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "certificates_dns_providers_certificates",
				Columns:    []*schema.Column{CertificatesColumns[18]},
				RefColumns: []*schema.Column{DNSProvidersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DNSProvidersColumns holds the columns for the "dns_providers" table.
	DNSProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "provider_type", Type: field.TypeEnum, Enums: []string{"cloudflare", "aliyun", "tencentcloud", "huawei", "aws", "googlecloud", "baiducloud", "jdcloud", "volcengine", "edgeone", "aliesa", "ucloud", "westcn", "com35", "rainyun", "todaynic", "dnsla", "dns51", "xinnet"}},
		{Name: "config", Type: field.TypeBytes, Nullable: true},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "comment", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DNSProvidersTable holds the schema information for the "dns_providers" table.
	DNSProvidersTable = &schema.Table{
		Name:       "dns_providers",
		Columns:    DNSProvidersColumns,
		PrimaryKey: []*schema.Column{DNSProvidersColumns[0]},
	}
	// MonitoredDomainsColumns holds the columns for the "monitored_domains" table.
	MonitoredDomainsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "port", Type: field.TypeInt, Default: 443},
		{Name: "check_type", Type: field.TypeEnum, Enums: []string{"https", "http"}, Default: "https"},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "check_interval", Type: field.TypeInt, Default: 3600},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ok", "warning", "error", "expired", "unknown"}, Default: "unknown"},
		{Name: "cert_issuer", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_not_before", Type: field.TypeTime, Nullable: true},
		{Name: "cert_not_after", Type: field.TypeTime, Nullable: true},
		{Name: "cert_fingerprint", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_subject", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_signature_algo", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_public_key_algo", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_public_key_bits", Type: field.TypeInt, Default: 0},
		{Name: "cert_sans", Type: field.TypeJSON, Nullable: true},
		{Name: "cert_remaining_days", Type: field.TypeInt, Default: 0},
		{Name: "last_check_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_check_error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "http_status_code", Type: field.TypeInt, Default: 0},
		{Name: "response_time_ms", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MonitoredDomainsTable holds the schema information for the "monitored_domains" table.
	MonitoredDomainsTable = &schema.Table{
		Name:       "monitored_domains",
		Columns:    MonitoredDomainsColumns,
		PrimaryKey: []*schema.Column{MonitoredDomainsColumns[0]},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeEnum, Nullable: true, Enums: []string{"cert", "dns", "monitor", "system"}, Default: "system"},
		{Name: "read", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
	}
	// RenewalLogsColumns holds the columns for the "renewal_logs" table.
	RenewalLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "failed", "pending"}},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "key_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "attempt_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "certificate_renewal_logs", Type: field.TypeInt},
	}
	// RenewalLogsTable holds the schema information for the "renewal_logs" table.
	RenewalLogsTable = &schema.Table{
		Name:       "renewal_logs",
		Columns:    RenewalLogsColumns,
		PrimaryKey: []*schema.Column{RenewalLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "renewal_logs_certificates_renewal_logs",
				Columns:    []*schema.Column{RenewalLogsColumns[8]},
				RefColumns: []*schema.Column{CertificatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ScanResultsColumns holds the columns for the "scan_results" table.
	ScanResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "domain", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt, Default: 443},
		{Name: "scan_type", Type: field.TypeEnum, Enums: []string{"https", "http"}, Default: "https"},
		{Name: "scanned_at", Type: field.TypeTime},
		{Name: "response_time_ms", Type: field.TypeInt, Default: 0},
		{Name: "cert_issuer", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_subject", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_not_before", Type: field.TypeTime, Nullable: true},
		{Name: "cert_not_after", Type: field.TypeTime, Nullable: true},
		{Name: "cert_remaining_days", Type: field.TypeInt, Default: 0},
		{Name: "cert_fingerprint", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_signature_algo", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_public_key_algo", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "cert_public_key_bits", Type: field.TypeInt, Default: 0},
		{Name: "cert_sans", Type: field.TypeJSON, Nullable: true},
		{Name: "cert_serial_number", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ScanResultsTable holds the schema information for the "scan_results" table.
	ScanResultsTable = &schema.Table{
		Name:       "scan_results",
		Columns:    ScanResultsColumns,
		PrimaryKey: []*schema.Column{ScanResultsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CasTable,
		CertificatesTable,
		DNSProvidersTable,
		MonitoredDomainsTable,
		NotificationsTable,
		RenewalLogsTable,
		ScanResultsTable,
	}
)

func init() {
	CertificatesTable.ForeignKeys[0].RefTable = CasTable
	CertificatesTable.ForeignKeys[1].RefTable = DNSProvidersTable
	RenewalLogsTable.ForeignKeys[0].RefTable = CertificatesTable
}
