// Code generated by ent, DO NOT EDIT.

package certificate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the certificate type in the database.
	Label = "certificate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldSans holds the string denoting the sans field in the database.
	FieldSans = "sans"
	// FieldCertContent holds the string denoting the cert_content field in the database.
	FieldCertContent = "cert_content"
	// FieldKeyContent holds the string denoting the key_content field in the database.
	FieldKeyContent = "key_content"
	// FieldIssuer holds the string denoting the issuer field in the database.
	FieldIssuer = "issuer"
	// FieldNotBefore holds the string denoting the not_before field in the database.
	FieldNotBefore = "not_before"
	// FieldNotAfter holds the string denoting the not_after field in the database.
	FieldNotAfter = "not_after"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAutoRenew holds the string denoting the auto_renew field in the database.
	FieldAutoRenew = "auto_renew"
	// FieldRenewalDays holds the string denoting the renewal_days field in the database.
	FieldRenewalDays = "renewal_days"
	// FieldChallengeRecords holds the string denoting the challenge_records field in the database.
	FieldChallengeRecords = "challenge_records"
	// FieldKeyType holds the string denoting the key_type field in the database.
	FieldKeyType = "key_type"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastRenewedAt holds the string denoting the last_renewed_at field in the database.
	FieldLastRenewedAt = "last_renewed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCa holds the string denoting the ca edge name in mutations.
	EdgeCa = "ca"
	// EdgeDNSProvider holds the string denoting the dns_provider edge name in mutations.
	EdgeDNSProvider = "dns_provider"
	// EdgeRenewalLogs holds the string denoting the renewal_logs edge name in mutations.
	EdgeRenewalLogs = "renewal_logs"
	// Table holds the table name of the certificate in the database.
	Table = "certificates"
	// CaTable is the table that holds the ca relation/edge.
	CaTable = "certificates"
	// CaInverseTable is the table name for the CA entity.
	// It exists in this package in order to avoid circular dependency with the "ca" package.
	CaInverseTable = "cas"
	// CaColumn is the table column denoting the ca relation/edge.
	CaColumn = "ca_certificates"
	// DNSProviderTable is the table that holds the dns_provider relation/edge.
	DNSProviderTable = "certificates"
	// DNSProviderInverseTable is the table name for the DNSProvider entity.
	// It exists in this package in order to avoid circular dependency with the "dnsprovider" package.
	DNSProviderInverseTable = "dns_providers"
	// DNSProviderColumn is the table column denoting the dns_provider relation/edge.
	DNSProviderColumn = "dns_provider_certificates"
	// RenewalLogsTable is the table that holds the renewal_logs relation/edge.
	RenewalLogsTable = "renewal_logs"
	// RenewalLogsInverseTable is the table name for the RenewalLog entity.
	// It exists in this package in order to avoid circular dependency with the "renewallog" package.
	RenewalLogsInverseTable = "renewal_logs"
	// RenewalLogsColumn is the table column denoting the renewal_logs relation/edge.
	RenewalLogsColumn = "certificate_renewal_logs"
)

// Columns holds all SQL columns for certificate fields.
var Columns = []string{
	FieldID,
	FieldDomain,
	FieldSans,
	FieldCertContent,
	FieldKeyContent,
	FieldIssuer,
	FieldNotBefore,
	FieldNotAfter,
	FieldStatus,
	FieldAutoRenew,
	FieldRenewalDays,
	FieldChallengeRecords,
	FieldKeyType,
	FieldLastError,
	FieldLastRenewedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "certificates"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ca_certificates",
	"dns_provider_certificates",
	"deploy_target_certificates",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// DefaultAutoRenew holds the default value on creation for the "auto_renew" field.
	DefaultAutoRenew bool
	// DefaultRenewalDays holds the default value on creation for the "renewal_days" field.
	DefaultRenewalDays int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending Status = "pending"
	StatusActive  Status = "active"
	StatusExpired Status = "expired"
	StatusRevoked Status = "revoked"
	StatusFailed  Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusActive, StatusExpired, StatusRevoked, StatusFailed:
		return nil
	default:
		return fmt.Errorf("certificate: invalid enum value for status field: %q", s)
	}
}

// KeyType defines the type for the "key_type" enum field.
type KeyType string

// KeyTypeEC256 is the default value of the KeyType enum.
const DefaultKeyType = KeyTypeEC256

// KeyType values.
const (
	KeyTypeEC256   KeyType = "EC256"
	KeyTypeEC384   KeyType = "EC384"
	KeyTypeRSA2048 KeyType = "RSA2048"
	KeyTypeRSA3072 KeyType = "RSA3072"
	KeyTypeRSA4096 KeyType = "RSA4096"
	KeyTypeRSA8192 KeyType = "RSA8192"
)

func (kt KeyType) String() string {
	return string(kt)
}

// KeyTypeValidator is a validator for the "key_type" field enum values. It is called by the builders before save.
func KeyTypeValidator(kt KeyType) error {
	switch kt {
	case KeyTypeEC256, KeyTypeEC384, KeyTypeRSA2048, KeyTypeRSA3072, KeyTypeRSA4096, KeyTypeRSA8192:
		return nil
	default:
		return fmt.Errorf("certificate: invalid enum value for key_type field: %q", kt)
	}
}

// OrderOption defines the ordering options for the Certificate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByCertContent orders the results by the cert_content field.
func ByCertContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertContent, opts...).ToFunc()
}

// ByKeyContent orders the results by the key_content field.
func ByKeyContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyContent, opts...).ToFunc()
}

// ByIssuer orders the results by the issuer field.
func ByIssuer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuer, opts...).ToFunc()
}

// ByNotBefore orders the results by the not_before field.
func ByNotBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotBefore, opts...).ToFunc()
}

// ByNotAfter orders the results by the not_after field.
func ByNotAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotAfter, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAutoRenew orders the results by the auto_renew field.
func ByAutoRenew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRenew, opts...).ToFunc()
}

// ByRenewalDays orders the results by the renewal_days field.
func ByRenewalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRenewalDays, opts...).ToFunc()
}

// ByKeyType orders the results by the key_type field.
func ByKeyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyType, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastRenewedAt orders the results by the last_renewed_at field.
func ByLastRenewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRenewedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCaField orders the results by ca field.
func ByCaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCaStep(), sql.OrderByField(field, opts...))
	}
}

// ByDNSProviderField orders the results by dns_provider field.
func ByDNSProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDNSProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByRenewalLogsCount orders the results by renewal_logs count.
func ByRenewalLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRenewalLogsStep(), opts...)
	}
}

// ByRenewalLogs orders the results by renewal_logs terms.
func ByRenewalLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRenewalLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CaTable, CaColumn),
	)
}
func newDNSProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DNSProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DNSProviderTable, DNSProviderColumn),
	)
}
func newRenewalLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RenewalLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RenewalLogsTable, RenewalLogsColumn),
	)
}
