// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cnb.cool/dtapp/certflow/ent/ca"
	"cnb.cool/dtapp/certflow/ent/certificate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CACreate is the builder for creating a CA entity.
type CACreate struct {
	config
	mutation *CAMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *CACreate) SetName(v string) *CACreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDirectoryURL sets the "directory_url" field.
func (_c *CACreate) SetDirectoryURL(v string) *CACreate {
	_c.mutation.SetDirectoryURL(v)
	return _c
}

// SetAccountEmail sets the "account_email" field.
func (_c *CACreate) SetAccountEmail(v string) *CACreate {
	_c.mutation.SetAccountEmail(v)
	return _c
}

// SetNillableAccountEmail sets the "account_email" field if the given value is not nil.
func (_c *CACreate) SetNillableAccountEmail(v *string) *CACreate {
	if v != nil {
		_c.SetAccountEmail(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *CACreate) SetIsDefault(v bool) *CACreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *CACreate) SetNillableIsDefault(v *bool) *CACreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *CACreate) SetIsActive(v bool) *CACreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *CACreate) SetNillableIsActive(v *bool) *CACreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CACreate) SetCreatedAt(v time.Time) *CACreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CACreate) SetNillableCreatedAt(v *time.Time) *CACreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CACreate) SetUpdatedAt(v time.Time) *CACreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CACreate) SetNillableUpdatedAt(v *time.Time) *CACreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddCertificateIDs adds the "certificates" edge to the Certificate entity by IDs.
func (_c *CACreate) AddCertificateIDs(ids ...int) *CACreate {
	_c.mutation.AddCertificateIDs(ids...)
	return _c
}

// AddCertificates adds the "certificates" edges to the Certificate entity.
func (_c *CACreate) AddCertificates(v ...*Certificate) *CACreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCertificateIDs(ids...)
}

// Mutation returns the CAMutation object of the builder.
func (_c *CACreate) Mutation() *CAMutation {
	return _c.mutation
}

// Save creates the CA in the database.
func (_c *CACreate) Save(ctx context.Context) (*CA, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CACreate) SaveX(ctx context.Context) *CA {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CACreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CACreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CACreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := ca.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := ca.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ca.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ca.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CACreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CA.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ca.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CA.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DirectoryURL(); !ok {
		return &ValidationError{Name: "directory_url", err: errors.New(`ent: missing required field "CA.directory_url"`)}
	}
	if v, ok := _c.mutation.DirectoryURL(); ok {
		if err := ca.DirectoryURLValidator(v); err != nil {
			return &ValidationError{Name: "directory_url", err: fmt.Errorf(`ent: validator failed for field "CA.directory_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "CA.is_default"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "CA.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CA.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CA.updated_at"`)}
	}
	return nil
}

func (_c *CACreate) sqlSave(ctx context.Context) (*CA, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CACreate) createSpec() (*CA, *sqlgraph.CreateSpec) {
	var (
		_node = &CA{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ca.Table, sqlgraph.NewFieldSpec(ca.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ca.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DirectoryURL(); ok {
		_spec.SetField(ca.FieldDirectoryURL, field.TypeString, value)
		_node.DirectoryURL = value
	}
	if value, ok := _c.mutation.AccountEmail(); ok {
		_spec.SetField(ca.FieldAccountEmail, field.TypeString, value)
		_node.AccountEmail = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(ca.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(ca.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ca.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ca.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CertificatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ca.CertificatesTable,
			Columns: []string{ca.CertificatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CA.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CAUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CACreate) OnConflict(opts ...sql.ConflictOption) *CAUpsertOne {
	_c.conflict = opts
	return &CAUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CA.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CACreate) OnConflictColumns(columns ...string) *CAUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CAUpsertOne{
		create: _c,
	}
}

type (
	// CAUpsertOne is the builder for "upsert"-ing
	//  one CA node.
	CAUpsertOne struct {
		create *CACreate
	}

	// CAUpsert is the "OnConflict" setter.
	CAUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CAUpsert) SetName(v string) *CAUpsert {
	u.Set(ca.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CAUpsert) UpdateName() *CAUpsert {
	u.SetExcluded(ca.FieldName)
	return u
}

// SetDirectoryURL sets the "directory_url" field.
func (u *CAUpsert) SetDirectoryURL(v string) *CAUpsert {
	u.Set(ca.FieldDirectoryURL, v)
	return u
}

// UpdateDirectoryURL sets the "directory_url" field to the value that was provided on create.
func (u *CAUpsert) UpdateDirectoryURL() *CAUpsert {
	u.SetExcluded(ca.FieldDirectoryURL)
	return u
}

// SetAccountEmail sets the "account_email" field.
func (u *CAUpsert) SetAccountEmail(v string) *CAUpsert {
	u.Set(ca.FieldAccountEmail, v)
	return u
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *CAUpsert) UpdateAccountEmail() *CAUpsert {
	u.SetExcluded(ca.FieldAccountEmail)
	return u
}

// ClearAccountEmail clears the value of the "account_email" field.
func (u *CAUpsert) ClearAccountEmail() *CAUpsert {
	u.SetNull(ca.FieldAccountEmail)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *CAUpsert) SetIsDefault(v bool) *CAUpsert {
	u.Set(ca.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *CAUpsert) UpdateIsDefault() *CAUpsert {
	u.SetExcluded(ca.FieldIsDefault)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *CAUpsert) SetIsActive(v bool) *CAUpsert {
	u.Set(ca.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CAUpsert) UpdateIsActive() *CAUpsert {
	u.SetExcluded(ca.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CAUpsert) SetUpdatedAt(v time.Time) *CAUpsert {
	u.Set(ca.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CAUpsert) UpdateUpdatedAt() *CAUpsert {
	u.SetExcluded(ca.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CA.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CAUpsertOne) UpdateNewValues() *CAUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ca.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CA.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CAUpsertOne) Ignore() *CAUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CAUpsertOne) DoNothing() *CAUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CACreate.OnConflict
// documentation for more info.
func (u *CAUpsertOne) Update(set func(*CAUpsert)) *CAUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CAUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CAUpsertOne) SetName(v string) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateName() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateName()
	})
}

// SetDirectoryURL sets the "directory_url" field.
func (u *CAUpsertOne) SetDirectoryURL(v string) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetDirectoryURL(v)
	})
}

// UpdateDirectoryURL sets the "directory_url" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateDirectoryURL() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateDirectoryURL()
	})
}

// SetAccountEmail sets the "account_email" field.
func (u *CAUpsertOne) SetAccountEmail(v string) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetAccountEmail(v)
	})
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateAccountEmail() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateAccountEmail()
	})
}

// ClearAccountEmail clears the value of the "account_email" field.
func (u *CAUpsertOne) ClearAccountEmail() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.ClearAccountEmail()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *CAUpsertOne) SetIsDefault(v bool) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateIsDefault() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CAUpsertOne) SetIsActive(v bool) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateIsActive() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CAUpsertOne) SetUpdatedAt(v time.Time) *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CAUpsertOne) UpdateUpdatedAt() *CAUpsertOne {
	return u.Update(func(s *CAUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CAUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CACreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CAUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CAUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CAUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CACreateBulk is the builder for creating many CA entities in bulk.
type CACreateBulk struct {
	config
	err      error
	builders []*CACreate
	conflict []sql.ConflictOption
}

// Save creates the CA entities in the database.
func (_c *CACreateBulk) Save(ctx context.Context) ([]*CA, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CA, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CAMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CACreateBulk) SaveX(ctx context.Context) []*CA {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CACreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CACreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CA.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CAUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *CACreateBulk) OnConflict(opts ...sql.ConflictOption) *CAUpsertBulk {
	_c.conflict = opts
	return &CAUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CA.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CACreateBulk) OnConflictColumns(columns ...string) *CAUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CAUpsertBulk{
		create: _c,
	}
}

// CAUpsertBulk is the builder for "upsert"-ing
// a bulk of CA nodes.
type CAUpsertBulk struct {
	create *CACreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CA.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CAUpsertBulk) UpdateNewValues() *CAUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ca.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CA.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CAUpsertBulk) Ignore() *CAUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CAUpsertBulk) DoNothing() *CAUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CACreateBulk.OnConflict
// documentation for more info.
func (u *CAUpsertBulk) Update(set func(*CAUpsert)) *CAUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CAUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CAUpsertBulk) SetName(v string) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateName() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateName()
	})
}

// SetDirectoryURL sets the "directory_url" field.
func (u *CAUpsertBulk) SetDirectoryURL(v string) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetDirectoryURL(v)
	})
}

// UpdateDirectoryURL sets the "directory_url" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateDirectoryURL() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateDirectoryURL()
	})
}

// SetAccountEmail sets the "account_email" field.
func (u *CAUpsertBulk) SetAccountEmail(v string) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetAccountEmail(v)
	})
}

// UpdateAccountEmail sets the "account_email" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateAccountEmail() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateAccountEmail()
	})
}

// ClearAccountEmail clears the value of the "account_email" field.
func (u *CAUpsertBulk) ClearAccountEmail() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.ClearAccountEmail()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *CAUpsertBulk) SetIsDefault(v bool) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateIsDefault() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CAUpsertBulk) SetIsActive(v bool) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateIsActive() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CAUpsertBulk) SetUpdatedAt(v time.Time) *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CAUpsertBulk) UpdateUpdatedAt() *CAUpsertBulk {
	return u.Update(func(s *CAUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CAUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CACreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CACreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CAUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
