// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cnb.cool/dtapp/certflow/ent/ca"
	"cnb.cool/dtapp/certflow/ent/certificate"
	"cnb.cool/dtapp/certflow/ent/dnsprovider"
	"cnb.cool/dtapp/certflow/ent/predicate"
	"cnb.cool/dtapp/certflow/ent/renewallog"
	"cnb.cool/dtapp/certflow/ent/schema"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *CertificateUpdate) SetDomain(v string) *CertificateUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableDomain(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSans sets the "sans" field.
func (_u *CertificateUpdate) SetSans(v []string) *CertificateUpdate {
	_u.mutation.SetSans(v)
	return _u
}

// AppendSans appends value to the "sans" field.
func (_u *CertificateUpdate) AppendSans(v []string) *CertificateUpdate {
	_u.mutation.AppendSans(v)
	return _u
}

// ClearSans clears the value of the "sans" field.
func (_u *CertificateUpdate) ClearSans() *CertificateUpdate {
	_u.mutation.ClearSans()
	return _u
}

// SetCertContent sets the "cert_content" field.
func (_u *CertificateUpdate) SetCertContent(v string) *CertificateUpdate {
	_u.mutation.SetCertContent(v)
	return _u
}

// SetNillableCertContent sets the "cert_content" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCertContent(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetCertContent(*v)
	}
	return _u
}

// ClearCertContent clears the value of the "cert_content" field.
func (_u *CertificateUpdate) ClearCertContent() *CertificateUpdate {
	_u.mutation.ClearCertContent()
	return _u
}

// SetKeyContent sets the "key_content" field.
func (_u *CertificateUpdate) SetKeyContent(v string) *CertificateUpdate {
	_u.mutation.SetKeyContent(v)
	return _u
}

// SetNillableKeyContent sets the "key_content" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableKeyContent(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetKeyContent(*v)
	}
	return _u
}

// ClearKeyContent clears the value of the "key_content" field.
func (_u *CertificateUpdate) ClearKeyContent() *CertificateUpdate {
	_u.mutation.ClearKeyContent()
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *CertificateUpdate) SetIssuer(v string) *CertificateUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIssuer(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// ClearIssuer clears the value of the "issuer" field.
func (_u *CertificateUpdate) ClearIssuer() *CertificateUpdate {
	_u.mutation.ClearIssuer()
	return _u
}

// SetNotBefore sets the "not_before" field.
func (_u *CertificateUpdate) SetNotBefore(v time.Time) *CertificateUpdate {
	_u.mutation.SetNotBefore(v)
	return _u
}

// SetNillableNotBefore sets the "not_before" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableNotBefore(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetNotBefore(*v)
	}
	return _u
}

// ClearNotBefore clears the value of the "not_before" field.
func (_u *CertificateUpdate) ClearNotBefore() *CertificateUpdate {
	_u.mutation.ClearNotBefore()
	return _u
}

// SetNotAfter sets the "not_after" field.
func (_u *CertificateUpdate) SetNotAfter(v time.Time) *CertificateUpdate {
	_u.mutation.SetNotAfter(v)
	return _u
}

// SetNillableNotAfter sets the "not_after" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableNotAfter(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetNotAfter(*v)
	}
	return _u
}

// ClearNotAfter clears the value of the "not_after" field.
func (_u *CertificateUpdate) ClearNotAfter() *CertificateUpdate {
	_u.mutation.ClearNotAfter()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdate) SetStatus(v certificate.Status) *CertificateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableStatus(v *certificate.Status) *CertificateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAutoRenew sets the "auto_renew" field.
func (_u *CertificateUpdate) SetAutoRenew(v bool) *CertificateUpdate {
	_u.mutation.SetAutoRenew(v)
	return _u
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableAutoRenew(v *bool) *CertificateUpdate {
	if v != nil {
		_u.SetAutoRenew(*v)
	}
	return _u
}

// SetRenewalDays sets the "renewal_days" field.
func (_u *CertificateUpdate) SetRenewalDays(v int) *CertificateUpdate {
	_u.mutation.ResetRenewalDays()
	_u.mutation.SetRenewalDays(v)
	return _u
}

// SetNillableRenewalDays sets the "renewal_days" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableRenewalDays(v *int) *CertificateUpdate {
	if v != nil {
		_u.SetRenewalDays(*v)
	}
	return _u
}

// AddRenewalDays adds value to the "renewal_days" field.
func (_u *CertificateUpdate) AddRenewalDays(v int) *CertificateUpdate {
	_u.mutation.AddRenewalDays(v)
	return _u
}

// SetChallengeRecords sets the "challenge_records" field.
func (_u *CertificateUpdate) SetChallengeRecords(v []schema.TXTRecord) *CertificateUpdate {
	_u.mutation.SetChallengeRecords(v)
	return _u
}

// AppendChallengeRecords appends value to the "challenge_records" field.
func (_u *CertificateUpdate) AppendChallengeRecords(v []schema.TXTRecord) *CertificateUpdate {
	_u.mutation.AppendChallengeRecords(v)
	return _u
}

// ClearChallengeRecords clears the value of the "challenge_records" field.
func (_u *CertificateUpdate) ClearChallengeRecords() *CertificateUpdate {
	_u.mutation.ClearChallengeRecords()
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *CertificateUpdate) SetKeyType(v certificate.KeyType) *CertificateUpdate {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableKeyType(v *certificate.KeyType) *CertificateUpdate {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CertificateUpdate) SetLastError(v string) *CertificateUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableLastError(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CertificateUpdate) ClearLastError() *CertificateUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastRenewedAt sets the "last_renewed_at" field.
func (_u *CertificateUpdate) SetLastRenewedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetLastRenewedAt(v)
	return _u
}

// SetNillableLastRenewedAt sets the "last_renewed_at" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableLastRenewedAt(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetLastRenewedAt(*v)
	}
	return _u
}

// ClearLastRenewedAt clears the value of the "last_renewed_at" field.
func (_u *CertificateUpdate) ClearLastRenewedAt() *CertificateUpdate {
	_u.mutation.ClearLastRenewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdate) SetUpdatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCaID sets the "ca" edge to the CA entity by ID.
func (_u *CertificateUpdate) SetCaID(id int) *CertificateUpdate {
	_u.mutation.SetCaID(id)
	return _u
}

// SetNillableCaID sets the "ca" edge to the CA entity by ID if the given value is not nil.
func (_u *CertificateUpdate) SetNillableCaID(id *int) *CertificateUpdate {
	if id != nil {
		_u = _u.SetCaID(*id)
	}
	return _u
}

// SetCa sets the "ca" edge to the CA entity.
func (_u *CertificateUpdate) SetCa(v *CA) *CertificateUpdate {
	return _u.SetCaID(v.ID)
}

// SetDNSProviderID sets the "dns_provider" edge to the DNSProvider entity by ID.
func (_u *CertificateUpdate) SetDNSProviderID(id int) *CertificateUpdate {
	_u.mutation.SetDNSProviderID(id)
	return _u
}

// SetNillableDNSProviderID sets the "dns_provider" edge to the DNSProvider entity by ID if the given value is not nil.
func (_u *CertificateUpdate) SetNillableDNSProviderID(id *int) *CertificateUpdate {
	if id != nil {
		_u = _u.SetDNSProviderID(*id)
	}
	return _u
}

// SetDNSProvider sets the "dns_provider" edge to the DNSProvider entity.
func (_u *CertificateUpdate) SetDNSProvider(v *DNSProvider) *CertificateUpdate {
	return _u.SetDNSProviderID(v.ID)
}

// AddRenewalLogIDs adds the "renewal_logs" edge to the RenewalLog entity by IDs.
func (_u *CertificateUpdate) AddRenewalLogIDs(ids ...int) *CertificateUpdate {
	_u.mutation.AddRenewalLogIDs(ids...)
	return _u
}

// AddRenewalLogs adds the "renewal_logs" edges to the RenewalLog entity.
func (_u *CertificateUpdate) AddRenewalLogs(v ...*RenewalLog) *CertificateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRenewalLogIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdate) Mutation() *CertificateMutation {
	return _u.mutation
}

// ClearCa clears the "ca" edge to the CA entity.
func (_u *CertificateUpdate) ClearCa() *CertificateUpdate {
	_u.mutation.ClearCa()
	return _u
}

// ClearDNSProvider clears the "dns_provider" edge to the DNSProvider entity.
func (_u *CertificateUpdate) ClearDNSProvider() *CertificateUpdate {
	_u.mutation.ClearDNSProvider()
	return _u
}

// ClearRenewalLogs clears all "renewal_logs" edges to the RenewalLog entity.
func (_u *CertificateUpdate) ClearRenewalLogs() *CertificateUpdate {
	_u.mutation.ClearRenewalLogs()
	return _u
}

// RemoveRenewalLogIDs removes the "renewal_logs" edge to RenewalLog entities by IDs.
func (_u *CertificateUpdate) RemoveRenewalLogIDs(ids ...int) *CertificateUpdate {
	_u.mutation.RemoveRenewalLogIDs(ids...)
	return _u
}

// RemoveRenewalLogs removes "renewal_logs" edges to RenewalLog entities.
func (_u *CertificateUpdate) RemoveRenewalLogs(v ...*RenewalLog) *CertificateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRenewalLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := certificate.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Certificate.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyType(); ok {
		if err := certificate.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "Certificate.key_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(certificate.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sans(); ok {
		_spec.SetField(certificate.FieldSans, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSans(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldSans, value)
		})
	}
	if _u.mutation.SansCleared() {
		_spec.ClearField(certificate.FieldSans, field.TypeJSON)
	}
	if value, ok := _u.mutation.CertContent(); ok {
		_spec.SetField(certificate.FieldCertContent, field.TypeString, value)
	}
	if _u.mutation.CertContentCleared() {
		_spec.ClearField(certificate.FieldCertContent, field.TypeString)
	}
	if value, ok := _u.mutation.KeyContent(); ok {
		_spec.SetField(certificate.FieldKeyContent, field.TypeString, value)
	}
	if _u.mutation.KeyContentCleared() {
		_spec.ClearField(certificate.FieldKeyContent, field.TypeString)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
	}
	if _u.mutation.IssuerCleared() {
		_spec.ClearField(certificate.FieldIssuer, field.TypeString)
	}
	if value, ok := _u.mutation.NotBefore(); ok {
		_spec.SetField(certificate.FieldNotBefore, field.TypeTime, value)
	}
	if _u.mutation.NotBeforeCleared() {
		_spec.ClearField(certificate.FieldNotBefore, field.TypeTime)
	}
	if value, ok := _u.mutation.NotAfter(); ok {
		_spec.SetField(certificate.FieldNotAfter, field.TypeTime, value)
	}
	if _u.mutation.NotAfterCleared() {
		_spec.ClearField(certificate.FieldNotAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AutoRenew(); ok {
		_spec.SetField(certificate.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RenewalDays(); ok {
		_spec.SetField(certificate.FieldRenewalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenewalDays(); ok {
		_spec.AddField(certificate.FieldRenewalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChallengeRecords(); ok {
		_spec.SetField(certificate.FieldChallengeRecords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChallengeRecords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldChallengeRecords, value)
		})
	}
	if _u.mutation.ChallengeRecordsCleared() {
		_spec.ClearField(certificate.FieldChallengeRecords, field.TypeJSON)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(certificate.FieldKeyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(certificate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(certificate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastRenewedAt(); ok {
		_spec.SetField(certificate.FieldLastRenewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRenewedAtCleared() {
		_spec.ClearField(certificate.FieldLastRenewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.CaTable,
			Columns: []string{certificate.CaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ca.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.CaTable,
			Columns: []string{certificate.CaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ca.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DNSProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.DNSProviderTable,
			Columns: []string{certificate.DNSProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DNSProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.DNSProviderTable,
			Columns: []string{certificate.DNSProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RenewalLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRenewalLogsIDs(); len(nodes) > 0 && !_u.mutation.RenewalLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RenewalLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateMutation
}

// SetDomain sets the "domain" field.
func (_u *CertificateUpdateOne) SetDomain(v string) *CertificateUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableDomain(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSans sets the "sans" field.
func (_u *CertificateUpdateOne) SetSans(v []string) *CertificateUpdateOne {
	_u.mutation.SetSans(v)
	return _u
}

// AppendSans appends value to the "sans" field.
func (_u *CertificateUpdateOne) AppendSans(v []string) *CertificateUpdateOne {
	_u.mutation.AppendSans(v)
	return _u
}

// ClearSans clears the value of the "sans" field.
func (_u *CertificateUpdateOne) ClearSans() *CertificateUpdateOne {
	_u.mutation.ClearSans()
	return _u
}

// SetCertContent sets the "cert_content" field.
func (_u *CertificateUpdateOne) SetCertContent(v string) *CertificateUpdateOne {
	_u.mutation.SetCertContent(v)
	return _u
}

// SetNillableCertContent sets the "cert_content" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCertContent(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetCertContent(*v)
	}
	return _u
}

// ClearCertContent clears the value of the "cert_content" field.
func (_u *CertificateUpdateOne) ClearCertContent() *CertificateUpdateOne {
	_u.mutation.ClearCertContent()
	return _u
}

// SetKeyContent sets the "key_content" field.
func (_u *CertificateUpdateOne) SetKeyContent(v string) *CertificateUpdateOne {
	_u.mutation.SetKeyContent(v)
	return _u
}

// SetNillableKeyContent sets the "key_content" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableKeyContent(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetKeyContent(*v)
	}
	return _u
}

// ClearKeyContent clears the value of the "key_content" field.
func (_u *CertificateUpdateOne) ClearKeyContent() *CertificateUpdateOne {
	_u.mutation.ClearKeyContent()
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *CertificateUpdateOne) SetIssuer(v string) *CertificateUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIssuer(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// ClearIssuer clears the value of the "issuer" field.
func (_u *CertificateUpdateOne) ClearIssuer() *CertificateUpdateOne {
	_u.mutation.ClearIssuer()
	return _u
}

// SetNotBefore sets the "not_before" field.
func (_u *CertificateUpdateOne) SetNotBefore(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetNotBefore(v)
	return _u
}

// SetNillableNotBefore sets the "not_before" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableNotBefore(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetNotBefore(*v)
	}
	return _u
}

// ClearNotBefore clears the value of the "not_before" field.
func (_u *CertificateUpdateOne) ClearNotBefore() *CertificateUpdateOne {
	_u.mutation.ClearNotBefore()
	return _u
}

// SetNotAfter sets the "not_after" field.
func (_u *CertificateUpdateOne) SetNotAfter(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetNotAfter(v)
	return _u
}

// SetNillableNotAfter sets the "not_after" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableNotAfter(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetNotAfter(*v)
	}
	return _u
}

// ClearNotAfter clears the value of the "not_after" field.
func (_u *CertificateUpdateOne) ClearNotAfter() *CertificateUpdateOne {
	_u.mutation.ClearNotAfter()
	return _u
}

// SetStatus sets the "status" field.
func (_u *CertificateUpdateOne) SetStatus(v certificate.Status) *CertificateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableStatus(v *certificate.Status) *CertificateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAutoRenew sets the "auto_renew" field.
func (_u *CertificateUpdateOne) SetAutoRenew(v bool) *CertificateUpdateOne {
	_u.mutation.SetAutoRenew(v)
	return _u
}

// SetNillableAutoRenew sets the "auto_renew" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableAutoRenew(v *bool) *CertificateUpdateOne {
	if v != nil {
		_u.SetAutoRenew(*v)
	}
	return _u
}

// SetRenewalDays sets the "renewal_days" field.
func (_u *CertificateUpdateOne) SetRenewalDays(v int) *CertificateUpdateOne {
	_u.mutation.ResetRenewalDays()
	_u.mutation.SetRenewalDays(v)
	return _u
}

// SetNillableRenewalDays sets the "renewal_days" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableRenewalDays(v *int) *CertificateUpdateOne {
	if v != nil {
		_u.SetRenewalDays(*v)
	}
	return _u
}

// AddRenewalDays adds value to the "renewal_days" field.
func (_u *CertificateUpdateOne) AddRenewalDays(v int) *CertificateUpdateOne {
	_u.mutation.AddRenewalDays(v)
	return _u
}

// SetChallengeRecords sets the "challenge_records" field.
func (_u *CertificateUpdateOne) SetChallengeRecords(v []schema.TXTRecord) *CertificateUpdateOne {
	_u.mutation.SetChallengeRecords(v)
	return _u
}

// AppendChallengeRecords appends value to the "challenge_records" field.
func (_u *CertificateUpdateOne) AppendChallengeRecords(v []schema.TXTRecord) *CertificateUpdateOne {
	_u.mutation.AppendChallengeRecords(v)
	return _u
}

// ClearChallengeRecords clears the value of the "challenge_records" field.
func (_u *CertificateUpdateOne) ClearChallengeRecords() *CertificateUpdateOne {
	_u.mutation.ClearChallengeRecords()
	return _u
}

// SetKeyType sets the "key_type" field.
func (_u *CertificateUpdateOne) SetKeyType(v certificate.KeyType) *CertificateUpdateOne {
	_u.mutation.SetKeyType(v)
	return _u
}

// SetNillableKeyType sets the "key_type" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableKeyType(v *certificate.KeyType) *CertificateUpdateOne {
	if v != nil {
		_u.SetKeyType(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CertificateUpdateOne) SetLastError(v string) *CertificateUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableLastError(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CertificateUpdateOne) ClearLastError() *CertificateUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastRenewedAt sets the "last_renewed_at" field.
func (_u *CertificateUpdateOne) SetLastRenewedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetLastRenewedAt(v)
	return _u
}

// SetNillableLastRenewedAt sets the "last_renewed_at" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableLastRenewedAt(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetLastRenewedAt(*v)
	}
	return _u
}

// ClearLastRenewedAt clears the value of the "last_renewed_at" field.
func (_u *CertificateUpdateOne) ClearLastRenewedAt() *CertificateUpdateOne {
	_u.mutation.ClearLastRenewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdateOne) SetUpdatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCaID sets the "ca" edge to the CA entity by ID.
func (_u *CertificateUpdateOne) SetCaID(id int) *CertificateUpdateOne {
	_u.mutation.SetCaID(id)
	return _u
}

// SetNillableCaID sets the "ca" edge to the CA entity by ID if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableCaID(id *int) *CertificateUpdateOne {
	if id != nil {
		_u = _u.SetCaID(*id)
	}
	return _u
}

// SetCa sets the "ca" edge to the CA entity.
func (_u *CertificateUpdateOne) SetCa(v *CA) *CertificateUpdateOne {
	return _u.SetCaID(v.ID)
}

// SetDNSProviderID sets the "dns_provider" edge to the DNSProvider entity by ID.
func (_u *CertificateUpdateOne) SetDNSProviderID(id int) *CertificateUpdateOne {
	_u.mutation.SetDNSProviderID(id)
	return _u
}

// SetNillableDNSProviderID sets the "dns_provider" edge to the DNSProvider entity by ID if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableDNSProviderID(id *int) *CertificateUpdateOne {
	if id != nil {
		_u = _u.SetDNSProviderID(*id)
	}
	return _u
}

// SetDNSProvider sets the "dns_provider" edge to the DNSProvider entity.
func (_u *CertificateUpdateOne) SetDNSProvider(v *DNSProvider) *CertificateUpdateOne {
	return _u.SetDNSProviderID(v.ID)
}

// AddRenewalLogIDs adds the "renewal_logs" edge to the RenewalLog entity by IDs.
func (_u *CertificateUpdateOne) AddRenewalLogIDs(ids ...int) *CertificateUpdateOne {
	_u.mutation.AddRenewalLogIDs(ids...)
	return _u
}

// AddRenewalLogs adds the "renewal_logs" edges to the RenewalLog entity.
func (_u *CertificateUpdateOne) AddRenewalLogs(v ...*RenewalLog) *CertificateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRenewalLogIDs(ids...)
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdateOne) Mutation() *CertificateMutation {
	return _u.mutation
}

// ClearCa clears the "ca" edge to the CA entity.
func (_u *CertificateUpdateOne) ClearCa() *CertificateUpdateOne {
	_u.mutation.ClearCa()
	return _u
}

// ClearDNSProvider clears the "dns_provider" edge to the DNSProvider entity.
func (_u *CertificateUpdateOne) ClearDNSProvider() *CertificateUpdateOne {
	_u.mutation.ClearDNSProvider()
	return _u
}

// ClearRenewalLogs clears all "renewal_logs" edges to the RenewalLog entity.
func (_u *CertificateUpdateOne) ClearRenewalLogs() *CertificateUpdateOne {
	_u.mutation.ClearRenewalLogs()
	return _u
}

// RemoveRenewalLogIDs removes the "renewal_logs" edge to RenewalLog entities by IDs.
func (_u *CertificateUpdateOne) RemoveRenewalLogIDs(ids ...int) *CertificateUpdateOne {
	_u.mutation.RemoveRenewalLogIDs(ids...)
	return _u
}

// RemoveRenewalLogs removes "renewal_logs" edges to RenewalLog entities.
func (_u *CertificateUpdateOne) RemoveRenewalLogs(v ...*RenewalLog) *CertificateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRenewalLogIDs(ids...)
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdateOne) Where(ps ...predicate.Certificate) *CertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificateUpdateOne) Select(field string, fields ...string) *CertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Certificate entity.
func (_u *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := certificate.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Certificate.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := certificate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Certificate.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyType(); ok {
		if err := certificate.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "Certificate.key_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdateOne) sqlSave(ctx context.Context) (_node *Certificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Certificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificate.FieldID)
		for _, f := range fields {
			if !certificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(certificate.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sans(); ok {
		_spec.SetField(certificate.FieldSans, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSans(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldSans, value)
		})
	}
	if _u.mutation.SansCleared() {
		_spec.ClearField(certificate.FieldSans, field.TypeJSON)
	}
	if value, ok := _u.mutation.CertContent(); ok {
		_spec.SetField(certificate.FieldCertContent, field.TypeString, value)
	}
	if _u.mutation.CertContentCleared() {
		_spec.ClearField(certificate.FieldCertContent, field.TypeString)
	}
	if value, ok := _u.mutation.KeyContent(); ok {
		_spec.SetField(certificate.FieldKeyContent, field.TypeString, value)
	}
	if _u.mutation.KeyContentCleared() {
		_spec.ClearField(certificate.FieldKeyContent, field.TypeString)
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(certificate.FieldIssuer, field.TypeString, value)
	}
	if _u.mutation.IssuerCleared() {
		_spec.ClearField(certificate.FieldIssuer, field.TypeString)
	}
	if value, ok := _u.mutation.NotBefore(); ok {
		_spec.SetField(certificate.FieldNotBefore, field.TypeTime, value)
	}
	if _u.mutation.NotBeforeCleared() {
		_spec.ClearField(certificate.FieldNotBefore, field.TypeTime)
	}
	if value, ok := _u.mutation.NotAfter(); ok {
		_spec.SetField(certificate.FieldNotAfter, field.TypeTime, value)
	}
	if _u.mutation.NotAfterCleared() {
		_spec.ClearField(certificate.FieldNotAfter, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(certificate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AutoRenew(); ok {
		_spec.SetField(certificate.FieldAutoRenew, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RenewalDays(); ok {
		_spec.SetField(certificate.FieldRenewalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRenewalDays(); ok {
		_spec.AddField(certificate.FieldRenewalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ChallengeRecords(); ok {
		_spec.SetField(certificate.FieldChallengeRecords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChallengeRecords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, certificate.FieldChallengeRecords, value)
		})
	}
	if _u.mutation.ChallengeRecordsCleared() {
		_spec.ClearField(certificate.FieldChallengeRecords, field.TypeJSON)
	}
	if value, ok := _u.mutation.KeyType(); ok {
		_spec.SetField(certificate.FieldKeyType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(certificate.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(certificate.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastRenewedAt(); ok {
		_spec.SetField(certificate.FieldLastRenewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRenewedAtCleared() {
		_spec.ClearField(certificate.FieldLastRenewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.CaTable,
			Columns: []string{certificate.CaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ca.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.CaTable,
			Columns: []string{certificate.CaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ca.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DNSProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.DNSProviderTable,
			Columns: []string{certificate.DNSProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DNSProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   certificate.DNSProviderTable,
			Columns: []string{certificate.DNSProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dnsprovider.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RenewalLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRenewalLogsIDs(); len(nodes) > 0 && !_u.mutation.RenewalLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RenewalLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   certificate.RenewalLogsTable,
			Columns: []string{certificate.RenewalLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(renewallog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Certificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
