// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"cnb.cool/dtapp/certflow/ent/migrate"

	"cnb.cool/dtapp/certflow/ent/authmethod"
	"cnb.cool/dtapp/certflow/ent/ca"
	"cnb.cool/dtapp/certflow/ent/certificate"
	"cnb.cool/dtapp/certflow/ent/dnsprovider"
	"cnb.cool/dtapp/certflow/ent/monitoreddomain"
	"cnb.cool/dtapp/certflow/ent/notification"
	"cnb.cool/dtapp/certflow/ent/passkeycredential"
	"cnb.cool/dtapp/certflow/ent/renewallog"
	"cnb.cool/dtapp/certflow/ent/scanresult"
	"cnb.cool/dtapp/certflow/ent/totpcredential"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AuthMethod is the client for interacting with the AuthMethod builders.
	AuthMethod *AuthMethodClient
	// CA is the client for interacting with the CA builders.
	CA *CAClient
	// Certificate is the client for interacting with the Certificate builders.
	Certificate *CertificateClient
	// DNSProvider is the client for interacting with the DNSProvider builders.
	DNSProvider *DNSProviderClient
	// MonitoredDomain is the client for interacting with the MonitoredDomain builders.
	MonitoredDomain *MonitoredDomainClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// PasskeyCredential is the client for interacting with the PasskeyCredential builders.
	PasskeyCredential *PasskeyCredentialClient
	// RenewalLog is the client for interacting with the RenewalLog builders.
	RenewalLog *RenewalLogClient
	// ScanResult is the client for interacting with the ScanResult builders.
	ScanResult *ScanResultClient
	// TOTPCredential is the client for interacting with the TOTPCredential builders.
	TOTPCredential *TOTPCredentialClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AuthMethod = NewAuthMethodClient(c.config)
	c.CA = NewCAClient(c.config)
	c.Certificate = NewCertificateClient(c.config)
	c.DNSProvider = NewDNSProviderClient(c.config)
	c.MonitoredDomain = NewMonitoredDomainClient(c.config)
	c.Notification = NewNotificationClient(c.config)
	c.PasskeyCredential = NewPasskeyCredentialClient(c.config)
	c.RenewalLog = NewRenewalLogClient(c.config)
	c.ScanResult = NewScanResultClient(c.config)
	c.TOTPCredential = NewTOTPCredentialClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		AuthMethod:        NewAuthMethodClient(cfg),
		CA:                NewCAClient(cfg),
		Certificate:       NewCertificateClient(cfg),
		DNSProvider:       NewDNSProviderClient(cfg),
		MonitoredDomain:   NewMonitoredDomainClient(cfg),
		Notification:      NewNotificationClient(cfg),
		PasskeyCredential: NewPasskeyCredentialClient(cfg),
		RenewalLog:        NewRenewalLogClient(cfg),
		ScanResult:        NewScanResultClient(cfg),
		TOTPCredential:    NewTOTPCredentialClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		AuthMethod:        NewAuthMethodClient(cfg),
		CA:                NewCAClient(cfg),
		Certificate:       NewCertificateClient(cfg),
		DNSProvider:       NewDNSProviderClient(cfg),
		MonitoredDomain:   NewMonitoredDomainClient(cfg),
		Notification:      NewNotificationClient(cfg),
		PasskeyCredential: NewPasskeyCredentialClient(cfg),
		RenewalLog:        NewRenewalLogClient(cfg),
		ScanResult:        NewScanResultClient(cfg),
		TOTPCredential:    NewTOTPCredentialClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AuthMethod.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AuthMethod, c.CA, c.Certificate, c.DNSProvider, c.MonitoredDomain,
		c.Notification, c.PasskeyCredential, c.RenewalLog, c.ScanResult,
		c.TOTPCredential,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AuthMethod, c.CA, c.Certificate, c.DNSProvider, c.MonitoredDomain,
		c.Notification, c.PasskeyCredential, c.RenewalLog, c.ScanResult,
		c.TOTPCredential,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AuthMethodMutation:
		return c.AuthMethod.mutate(ctx, m)
	case *CAMutation:
		return c.CA.mutate(ctx, m)
	case *CertificateMutation:
		return c.Certificate.mutate(ctx, m)
	case *DNSProviderMutation:
		return c.DNSProvider.mutate(ctx, m)
	case *MonitoredDomainMutation:
		return c.MonitoredDomain.mutate(ctx, m)
	case *NotificationMutation:
		return c.Notification.mutate(ctx, m)
	case *PasskeyCredentialMutation:
		return c.PasskeyCredential.mutate(ctx, m)
	case *RenewalLogMutation:
		return c.RenewalLog.mutate(ctx, m)
	case *ScanResultMutation:
		return c.ScanResult.mutate(ctx, m)
	case *TOTPCredentialMutation:
		return c.TOTPCredential.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AuthMethodClient is a client for the AuthMethod schema.
type AuthMethodClient struct {
	config
}

// NewAuthMethodClient returns a client for the AuthMethod from the given config.
func NewAuthMethodClient(c config) *AuthMethodClient {
	return &AuthMethodClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `authmethod.Hooks(f(g(h())))`.
func (c *AuthMethodClient) Use(hooks ...Hook) {
	c.hooks.AuthMethod = append(c.hooks.AuthMethod, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `authmethod.Intercept(f(g(h())))`.
func (c *AuthMethodClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuthMethod = append(c.inters.AuthMethod, interceptors...)
}

// Create returns a builder for creating a AuthMethod entity.
func (c *AuthMethodClient) Create() *AuthMethodCreate {
	mutation := newAuthMethodMutation(c.config, OpCreate)
	return &AuthMethodCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuthMethod entities.
func (c *AuthMethodClient) CreateBulk(builders ...*AuthMethodCreate) *AuthMethodCreateBulk {
	return &AuthMethodCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuthMethodClient) MapCreateBulk(slice any, setFunc func(*AuthMethodCreate, int)) *AuthMethodCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuthMethodCreateBulk{err: fmt.Errorf("calling to AuthMethodClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuthMethodCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuthMethodCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuthMethod.
func (c *AuthMethodClient) Update() *AuthMethodUpdate {
	mutation := newAuthMethodMutation(c.config, OpUpdate)
	return &AuthMethodUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuthMethodClient) UpdateOne(_m *AuthMethod) *AuthMethodUpdateOne {
	mutation := newAuthMethodMutation(c.config, OpUpdateOne, withAuthMethod(_m))
	return &AuthMethodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuthMethodClient) UpdateOneID(id int) *AuthMethodUpdateOne {
	mutation := newAuthMethodMutation(c.config, OpUpdateOne, withAuthMethodID(id))
	return &AuthMethodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuthMethod.
func (c *AuthMethodClient) Delete() *AuthMethodDelete {
	mutation := newAuthMethodMutation(c.config, OpDelete)
	return &AuthMethodDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuthMethodClient) DeleteOne(_m *AuthMethod) *AuthMethodDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuthMethodClient) DeleteOneID(id int) *AuthMethodDeleteOne {
	builder := c.Delete().Where(authmethod.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuthMethodDeleteOne{builder}
}

// Query returns a query builder for AuthMethod.
func (c *AuthMethodClient) Query() *AuthMethodQuery {
	return &AuthMethodQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuthMethod},
		inters: c.Interceptors(),
	}
}

// Get returns a AuthMethod entity by its id.
func (c *AuthMethodClient) Get(ctx context.Context, id int) (*AuthMethod, error) {
	return c.Query().Where(authmethod.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuthMethodClient) GetX(ctx context.Context, id int) *AuthMethod {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTotpCredentials queries the totp_credentials edge of a AuthMethod.
func (c *AuthMethodClient) QueryTotpCredentials(_m *AuthMethod) *TOTPCredentialQuery {
	query := (&TOTPCredentialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(authmethod.Table, authmethod.FieldID, id),
			sqlgraph.To(totpcredential.Table, totpcredential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, authmethod.TotpCredentialsTable, authmethod.TotpCredentialsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPasskeyCredentials queries the passkey_credentials edge of a AuthMethod.
func (c *AuthMethodClient) QueryPasskeyCredentials(_m *AuthMethod) *PasskeyCredentialQuery {
	query := (&PasskeyCredentialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(authmethod.Table, authmethod.FieldID, id),
			sqlgraph.To(passkeycredential.Table, passkeycredential.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, authmethod.PasskeyCredentialsTable, authmethod.PasskeyCredentialsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuthMethodClient) Hooks() []Hook {
	return c.hooks.AuthMethod
}

// Interceptors returns the client interceptors.
func (c *AuthMethodClient) Interceptors() []Interceptor {
	return c.inters.AuthMethod
}

func (c *AuthMethodClient) mutate(ctx context.Context, m *AuthMethodMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuthMethodCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuthMethodUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuthMethodUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuthMethodDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuthMethod mutation op: %q", m.Op())
	}
}

// CAClient is a client for the CA schema.
type CAClient struct {
	config
}

// NewCAClient returns a client for the CA from the given config.
func NewCAClient(c config) *CAClient {
	return &CAClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ca.Hooks(f(g(h())))`.
func (c *CAClient) Use(hooks ...Hook) {
	c.hooks.CA = append(c.hooks.CA, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ca.Intercept(f(g(h())))`.
func (c *CAClient) Intercept(interceptors ...Interceptor) {
	c.inters.CA = append(c.inters.CA, interceptors...)
}

// Create returns a builder for creating a CA entity.
func (c *CAClient) Create() *CACreate {
	mutation := newCAMutation(c.config, OpCreate)
	return &CACreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CA entities.
func (c *CAClient) CreateBulk(builders ...*CACreate) *CACreateBulk {
	return &CACreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CAClient) MapCreateBulk(slice any, setFunc func(*CACreate, int)) *CACreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CACreateBulk{err: fmt.Errorf("calling to CAClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CACreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CACreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CA.
func (c *CAClient) Update() *CAUpdate {
	mutation := newCAMutation(c.config, OpUpdate)
	return &CAUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CAClient) UpdateOne(_m *CA) *CAUpdateOne {
	mutation := newCAMutation(c.config, OpUpdateOne, withCA(_m))
	return &CAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CAClient) UpdateOneID(id int) *CAUpdateOne {
	mutation := newCAMutation(c.config, OpUpdateOne, withCAID(id))
	return &CAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CA.
func (c *CAClient) Delete() *CADelete {
	mutation := newCAMutation(c.config, OpDelete)
	return &CADelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CAClient) DeleteOne(_m *CA) *CADeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CAClient) DeleteOneID(id int) *CADeleteOne {
	builder := c.Delete().Where(ca.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CADeleteOne{builder}
}

// Query returns a query builder for CA.
func (c *CAClient) Query() *CAQuery {
	return &CAQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCA},
		inters: c.Interceptors(),
	}
}

// Get returns a CA entity by its id.
func (c *CAClient) Get(ctx context.Context, id int) (*CA, error) {
	return c.Query().Where(ca.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CAClient) GetX(ctx context.Context, id int) *CA {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCertificates queries the certificates edge of a CA.
func (c *CAClient) QueryCertificates(_m *CA) *CertificateQuery {
	query := (&CertificateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ca.Table, ca.FieldID, id),
			sqlgraph.To(certificate.Table, certificate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ca.CertificatesTable, ca.CertificatesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CAClient) Hooks() []Hook {
	return c.hooks.CA
}

// Interceptors returns the client interceptors.
func (c *CAClient) Interceptors() []Interceptor {
	return c.inters.CA
}

func (c *CAClient) mutate(ctx context.Context, m *CAMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CACreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CAUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CAUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CADelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CA mutation op: %q", m.Op())
	}
}

// CertificateClient is a client for the Certificate schema.
type CertificateClient struct {
	config
}

// NewCertificateClient returns a client for the Certificate from the given config.
func NewCertificateClient(c config) *CertificateClient {
	return &CertificateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `certificate.Hooks(f(g(h())))`.
func (c *CertificateClient) Use(hooks ...Hook) {
	c.hooks.Certificate = append(c.hooks.Certificate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `certificate.Intercept(f(g(h())))`.
func (c *CertificateClient) Intercept(interceptors ...Interceptor) {
	c.inters.Certificate = append(c.inters.Certificate, interceptors...)
}

// Create returns a builder for creating a Certificate entity.
func (c *CertificateClient) Create() *CertificateCreate {
	mutation := newCertificateMutation(c.config, OpCreate)
	return &CertificateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Certificate entities.
func (c *CertificateClient) CreateBulk(builders ...*CertificateCreate) *CertificateCreateBulk {
	return &CertificateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CertificateClient) MapCreateBulk(slice any, setFunc func(*CertificateCreate, int)) *CertificateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CertificateCreateBulk{err: fmt.Errorf("calling to CertificateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CertificateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CertificateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Certificate.
func (c *CertificateClient) Update() *CertificateUpdate {
	mutation := newCertificateMutation(c.config, OpUpdate)
	return &CertificateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CertificateClient) UpdateOne(_m *Certificate) *CertificateUpdateOne {
	mutation := newCertificateMutation(c.config, OpUpdateOne, withCertificate(_m))
	return &CertificateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CertificateClient) UpdateOneID(id int) *CertificateUpdateOne {
	mutation := newCertificateMutation(c.config, OpUpdateOne, withCertificateID(id))
	return &CertificateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Certificate.
func (c *CertificateClient) Delete() *CertificateDelete {
	mutation := newCertificateMutation(c.config, OpDelete)
	return &CertificateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CertificateClient) DeleteOne(_m *Certificate) *CertificateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CertificateClient) DeleteOneID(id int) *CertificateDeleteOne {
	builder := c.Delete().Where(certificate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CertificateDeleteOne{builder}
}

// Query returns a query builder for Certificate.
func (c *CertificateClient) Query() *CertificateQuery {
	return &CertificateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCertificate},
		inters: c.Interceptors(),
	}
}

// Get returns a Certificate entity by its id.
func (c *CertificateClient) Get(ctx context.Context, id int) (*Certificate, error) {
	return c.Query().Where(certificate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CertificateClient) GetX(ctx context.Context, id int) *Certificate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCa queries the ca edge of a Certificate.
func (c *CertificateClient) QueryCa(_m *Certificate) *CAQuery {
	query := (&CAClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(certificate.Table, certificate.FieldID, id),
			sqlgraph.To(ca.Table, ca.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, certificate.CaTable, certificate.CaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDNSProvider queries the dns_provider edge of a Certificate.
func (c *CertificateClient) QueryDNSProvider(_m *Certificate) *DNSProviderQuery {
	query := (&DNSProviderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(certificate.Table, certificate.FieldID, id),
			sqlgraph.To(dnsprovider.Table, dnsprovider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, certificate.DNSProviderTable, certificate.DNSProviderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRenewalLogs queries the renewal_logs edge of a Certificate.
func (c *CertificateClient) QueryRenewalLogs(_m *Certificate) *RenewalLogQuery {
	query := (&RenewalLogClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(certificate.Table, certificate.FieldID, id),
			sqlgraph.To(renewallog.Table, renewallog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, certificate.RenewalLogsTable, certificate.RenewalLogsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CertificateClient) Hooks() []Hook {
	return c.hooks.Certificate
}

// Interceptors returns the client interceptors.
func (c *CertificateClient) Interceptors() []Interceptor {
	return c.inters.Certificate
}

func (c *CertificateClient) mutate(ctx context.Context, m *CertificateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CertificateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CertificateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CertificateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CertificateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Certificate mutation op: %q", m.Op())
	}
}

// DNSProviderClient is a client for the DNSProvider schema.
type DNSProviderClient struct {
	config
}

// NewDNSProviderClient returns a client for the DNSProvider from the given config.
func NewDNSProviderClient(c config) *DNSProviderClient {
	return &DNSProviderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dnsprovider.Hooks(f(g(h())))`.
func (c *DNSProviderClient) Use(hooks ...Hook) {
	c.hooks.DNSProvider = append(c.hooks.DNSProvider, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dnsprovider.Intercept(f(g(h())))`.
func (c *DNSProviderClient) Intercept(interceptors ...Interceptor) {
	c.inters.DNSProvider = append(c.inters.DNSProvider, interceptors...)
}

// Create returns a builder for creating a DNSProvider entity.
func (c *DNSProviderClient) Create() *DNSProviderCreate {
	mutation := newDNSProviderMutation(c.config, OpCreate)
	return &DNSProviderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DNSProvider entities.
func (c *DNSProviderClient) CreateBulk(builders ...*DNSProviderCreate) *DNSProviderCreateBulk {
	return &DNSProviderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DNSProviderClient) MapCreateBulk(slice any, setFunc func(*DNSProviderCreate, int)) *DNSProviderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DNSProviderCreateBulk{err: fmt.Errorf("calling to DNSProviderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DNSProviderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DNSProviderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DNSProvider.
func (c *DNSProviderClient) Update() *DNSProviderUpdate {
	mutation := newDNSProviderMutation(c.config, OpUpdate)
	return &DNSProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DNSProviderClient) UpdateOne(_m *DNSProvider) *DNSProviderUpdateOne {
	mutation := newDNSProviderMutation(c.config, OpUpdateOne, withDNSProvider(_m))
	return &DNSProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DNSProviderClient) UpdateOneID(id int) *DNSProviderUpdateOne {
	mutation := newDNSProviderMutation(c.config, OpUpdateOne, withDNSProviderID(id))
	return &DNSProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DNSProvider.
func (c *DNSProviderClient) Delete() *DNSProviderDelete {
	mutation := newDNSProviderMutation(c.config, OpDelete)
	return &DNSProviderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DNSProviderClient) DeleteOne(_m *DNSProvider) *DNSProviderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DNSProviderClient) DeleteOneID(id int) *DNSProviderDeleteOne {
	builder := c.Delete().Where(dnsprovider.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DNSProviderDeleteOne{builder}
}

// Query returns a query builder for DNSProvider.
func (c *DNSProviderClient) Query() *DNSProviderQuery {
	return &DNSProviderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDNSProvider},
		inters: c.Interceptors(),
	}
}

// Get returns a DNSProvider entity by its id.
func (c *DNSProviderClient) Get(ctx context.Context, id int) (*DNSProvider, error) {
	return c.Query().Where(dnsprovider.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DNSProviderClient) GetX(ctx context.Context, id int) *DNSProvider {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCertificates queries the certificates edge of a DNSProvider.
func (c *DNSProviderClient) QueryCertificates(_m *DNSProvider) *CertificateQuery {
	query := (&CertificateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(dnsprovider.Table, dnsprovider.FieldID, id),
			sqlgraph.To(certificate.Table, certificate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dnsprovider.CertificatesTable, dnsprovider.CertificatesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DNSProviderClient) Hooks() []Hook {
	return c.hooks.DNSProvider
}

// Interceptors returns the client interceptors.
func (c *DNSProviderClient) Interceptors() []Interceptor {
	return c.inters.DNSProvider
}

func (c *DNSProviderClient) mutate(ctx context.Context, m *DNSProviderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DNSProviderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DNSProviderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DNSProviderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DNSProviderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DNSProvider mutation op: %q", m.Op())
	}
}

// MonitoredDomainClient is a client for the MonitoredDomain schema.
type MonitoredDomainClient struct {
	config
}

// NewMonitoredDomainClient returns a client for the MonitoredDomain from the given config.
func NewMonitoredDomainClient(c config) *MonitoredDomainClient {
	return &MonitoredDomainClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `monitoreddomain.Hooks(f(g(h())))`.
func (c *MonitoredDomainClient) Use(hooks ...Hook) {
	c.hooks.MonitoredDomain = append(c.hooks.MonitoredDomain, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `monitoreddomain.Intercept(f(g(h())))`.
func (c *MonitoredDomainClient) Intercept(interceptors ...Interceptor) {
	c.inters.MonitoredDomain = append(c.inters.MonitoredDomain, interceptors...)
}

// Create returns a builder for creating a MonitoredDomain entity.
func (c *MonitoredDomainClient) Create() *MonitoredDomainCreate {
	mutation := newMonitoredDomainMutation(c.config, OpCreate)
	return &MonitoredDomainCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MonitoredDomain entities.
func (c *MonitoredDomainClient) CreateBulk(builders ...*MonitoredDomainCreate) *MonitoredDomainCreateBulk {
	return &MonitoredDomainCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MonitoredDomainClient) MapCreateBulk(slice any, setFunc func(*MonitoredDomainCreate, int)) *MonitoredDomainCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MonitoredDomainCreateBulk{err: fmt.Errorf("calling to MonitoredDomainClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MonitoredDomainCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MonitoredDomainCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MonitoredDomain.
func (c *MonitoredDomainClient) Update() *MonitoredDomainUpdate {
	mutation := newMonitoredDomainMutation(c.config, OpUpdate)
	return &MonitoredDomainUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MonitoredDomainClient) UpdateOne(_m *MonitoredDomain) *MonitoredDomainUpdateOne {
	mutation := newMonitoredDomainMutation(c.config, OpUpdateOne, withMonitoredDomain(_m))
	return &MonitoredDomainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MonitoredDomainClient) UpdateOneID(id int) *MonitoredDomainUpdateOne {
	mutation := newMonitoredDomainMutation(c.config, OpUpdateOne, withMonitoredDomainID(id))
	return &MonitoredDomainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MonitoredDomain.
func (c *MonitoredDomainClient) Delete() *MonitoredDomainDelete {
	mutation := newMonitoredDomainMutation(c.config, OpDelete)
	return &MonitoredDomainDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MonitoredDomainClient) DeleteOne(_m *MonitoredDomain) *MonitoredDomainDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MonitoredDomainClient) DeleteOneID(id int) *MonitoredDomainDeleteOne {
	builder := c.Delete().Where(monitoreddomain.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MonitoredDomainDeleteOne{builder}
}

// Query returns a query builder for MonitoredDomain.
func (c *MonitoredDomainClient) Query() *MonitoredDomainQuery {
	return &MonitoredDomainQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMonitoredDomain},
		inters: c.Interceptors(),
	}
}

// Get returns a MonitoredDomain entity by its id.
func (c *MonitoredDomainClient) Get(ctx context.Context, id int) (*MonitoredDomain, error) {
	return c.Query().Where(monitoreddomain.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MonitoredDomainClient) GetX(ctx context.Context, id int) *MonitoredDomain {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MonitoredDomainClient) Hooks() []Hook {
	return c.hooks.MonitoredDomain
}

// Interceptors returns the client interceptors.
func (c *MonitoredDomainClient) Interceptors() []Interceptor {
	return c.inters.MonitoredDomain
}

func (c *MonitoredDomainClient) mutate(ctx context.Context, m *MonitoredDomainMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MonitoredDomainCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MonitoredDomainUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MonitoredDomainUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MonitoredDomainDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MonitoredDomain mutation op: %q", m.Op())
	}
}

// NotificationClient is a client for the Notification schema.
type NotificationClient struct {
	config
}

// NewNotificationClient returns a client for the Notification from the given config.
func NewNotificationClient(c config) *NotificationClient {
	return &NotificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `notification.Hooks(f(g(h())))`.
func (c *NotificationClient) Use(hooks ...Hook) {
	c.hooks.Notification = append(c.hooks.Notification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `notification.Intercept(f(g(h())))`.
func (c *NotificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.Notification = append(c.inters.Notification, interceptors...)
}

// Create returns a builder for creating a Notification entity.
func (c *NotificationClient) Create() *NotificationCreate {
	mutation := newNotificationMutation(c.config, OpCreate)
	return &NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Notification entities.
func (c *NotificationClient) CreateBulk(builders ...*NotificationCreate) *NotificationCreateBulk {
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *NotificationClient) MapCreateBulk(slice any, setFunc func(*NotificationCreate, int)) *NotificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &NotificationCreateBulk{err: fmt.Errorf("calling to NotificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*NotificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &NotificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Notification.
func (c *NotificationClient) Update() *NotificationUpdate {
	mutation := newNotificationMutation(c.config, OpUpdate)
	return &NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NotificationClient) UpdateOne(_m *Notification) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotification(_m))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NotificationClient) UpdateOneID(id int) *NotificationUpdateOne {
	mutation := newNotificationMutation(c.config, OpUpdateOne, withNotificationID(id))
	return &NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Notification.
func (c *NotificationClient) Delete() *NotificationDelete {
	mutation := newNotificationMutation(c.config, OpDelete)
	return &NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *NotificationClient) DeleteOne(_m *Notification) *NotificationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *NotificationClient) DeleteOneID(id int) *NotificationDeleteOne {
	builder := c.Delete().Where(notification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NotificationDeleteOne{builder}
}

// Query returns a query builder for Notification.
func (c *NotificationClient) Query() *NotificationQuery {
	return &NotificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeNotification},
		inters: c.Interceptors(),
	}
}

// Get returns a Notification entity by its id.
func (c *NotificationClient) Get(ctx context.Context, id int) (*Notification, error) {
	return c.Query().Where(notification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NotificationClient) GetX(ctx context.Context, id int) *Notification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *NotificationClient) Hooks() []Hook {
	return c.hooks.Notification
}

// Interceptors returns the client interceptors.
func (c *NotificationClient) Interceptors() []Interceptor {
	return c.inters.Notification
}

func (c *NotificationClient) mutate(ctx context.Context, m *NotificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&NotificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&NotificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&NotificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&NotificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Notification mutation op: %q", m.Op())
	}
}

// PasskeyCredentialClient is a client for the PasskeyCredential schema.
type PasskeyCredentialClient struct {
	config
}

// NewPasskeyCredentialClient returns a client for the PasskeyCredential from the given config.
func NewPasskeyCredentialClient(c config) *PasskeyCredentialClient {
	return &PasskeyCredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passkeycredential.Hooks(f(g(h())))`.
func (c *PasskeyCredentialClient) Use(hooks ...Hook) {
	c.hooks.PasskeyCredential = append(c.hooks.PasskeyCredential, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passkeycredential.Intercept(f(g(h())))`.
func (c *PasskeyCredentialClient) Intercept(interceptors ...Interceptor) {
	c.inters.PasskeyCredential = append(c.inters.PasskeyCredential, interceptors...)
}

// Create returns a builder for creating a PasskeyCredential entity.
func (c *PasskeyCredentialClient) Create() *PasskeyCredentialCreate {
	mutation := newPasskeyCredentialMutation(c.config, OpCreate)
	return &PasskeyCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasskeyCredential entities.
func (c *PasskeyCredentialClient) CreateBulk(builders ...*PasskeyCredentialCreate) *PasskeyCredentialCreateBulk {
	return &PasskeyCredentialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PasskeyCredentialClient) MapCreateBulk(slice any, setFunc func(*PasskeyCredentialCreate, int)) *PasskeyCredentialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PasskeyCredentialCreateBulk{err: fmt.Errorf("calling to PasskeyCredentialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PasskeyCredentialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PasskeyCredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasskeyCredential.
func (c *PasskeyCredentialClient) Update() *PasskeyCredentialUpdate {
	mutation := newPasskeyCredentialMutation(c.config, OpUpdate)
	return &PasskeyCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasskeyCredentialClient) UpdateOne(_m *PasskeyCredential) *PasskeyCredentialUpdateOne {
	mutation := newPasskeyCredentialMutation(c.config, OpUpdateOne, withPasskeyCredential(_m))
	return &PasskeyCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasskeyCredentialClient) UpdateOneID(id int) *PasskeyCredentialUpdateOne {
	mutation := newPasskeyCredentialMutation(c.config, OpUpdateOne, withPasskeyCredentialID(id))
	return &PasskeyCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasskeyCredential.
func (c *PasskeyCredentialClient) Delete() *PasskeyCredentialDelete {
	mutation := newPasskeyCredentialMutation(c.config, OpDelete)
	return &PasskeyCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasskeyCredentialClient) DeleteOne(_m *PasskeyCredential) *PasskeyCredentialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasskeyCredentialClient) DeleteOneID(id int) *PasskeyCredentialDeleteOne {
	builder := c.Delete().Where(passkeycredential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasskeyCredentialDeleteOne{builder}
}

// Query returns a query builder for PasskeyCredential.
func (c *PasskeyCredentialClient) Query() *PasskeyCredentialQuery {
	return &PasskeyCredentialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePasskeyCredential},
		inters: c.Interceptors(),
	}
}

// Get returns a PasskeyCredential entity by its id.
func (c *PasskeyCredentialClient) Get(ctx context.Context, id int) (*PasskeyCredential, error) {
	return c.Query().Where(passkeycredential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasskeyCredentialClient) GetX(ctx context.Context, id int) *PasskeyCredential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAuthMethod queries the auth_method edge of a PasskeyCredential.
func (c *PasskeyCredentialClient) QueryAuthMethod(_m *PasskeyCredential) *AuthMethodQuery {
	query := (&AuthMethodClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(passkeycredential.Table, passkeycredential.FieldID, id),
			sqlgraph.To(authmethod.Table, authmethod.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, passkeycredential.AuthMethodTable, passkeycredential.AuthMethodColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PasskeyCredentialClient) Hooks() []Hook {
	return c.hooks.PasskeyCredential
}

// Interceptors returns the client interceptors.
func (c *PasskeyCredentialClient) Interceptors() []Interceptor {
	return c.inters.PasskeyCredential
}

func (c *PasskeyCredentialClient) mutate(ctx context.Context, m *PasskeyCredentialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PasskeyCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PasskeyCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PasskeyCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PasskeyCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PasskeyCredential mutation op: %q", m.Op())
	}
}

// RenewalLogClient is a client for the RenewalLog schema.
type RenewalLogClient struct {
	config
}

// NewRenewalLogClient returns a client for the RenewalLog from the given config.
func NewRenewalLogClient(c config) *RenewalLogClient {
	return &RenewalLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `renewallog.Hooks(f(g(h())))`.
func (c *RenewalLogClient) Use(hooks ...Hook) {
	c.hooks.RenewalLog = append(c.hooks.RenewalLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `renewallog.Intercept(f(g(h())))`.
func (c *RenewalLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.RenewalLog = append(c.inters.RenewalLog, interceptors...)
}

// Create returns a builder for creating a RenewalLog entity.
func (c *RenewalLogClient) Create() *RenewalLogCreate {
	mutation := newRenewalLogMutation(c.config, OpCreate)
	return &RenewalLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RenewalLog entities.
func (c *RenewalLogClient) CreateBulk(builders ...*RenewalLogCreate) *RenewalLogCreateBulk {
	return &RenewalLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RenewalLogClient) MapCreateBulk(slice any, setFunc func(*RenewalLogCreate, int)) *RenewalLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RenewalLogCreateBulk{err: fmt.Errorf("calling to RenewalLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RenewalLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RenewalLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RenewalLog.
func (c *RenewalLogClient) Update() *RenewalLogUpdate {
	mutation := newRenewalLogMutation(c.config, OpUpdate)
	return &RenewalLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RenewalLogClient) UpdateOne(_m *RenewalLog) *RenewalLogUpdateOne {
	mutation := newRenewalLogMutation(c.config, OpUpdateOne, withRenewalLog(_m))
	return &RenewalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RenewalLogClient) UpdateOneID(id int) *RenewalLogUpdateOne {
	mutation := newRenewalLogMutation(c.config, OpUpdateOne, withRenewalLogID(id))
	return &RenewalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RenewalLog.
func (c *RenewalLogClient) Delete() *RenewalLogDelete {
	mutation := newRenewalLogMutation(c.config, OpDelete)
	return &RenewalLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RenewalLogClient) DeleteOne(_m *RenewalLog) *RenewalLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RenewalLogClient) DeleteOneID(id int) *RenewalLogDeleteOne {
	builder := c.Delete().Where(renewallog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RenewalLogDeleteOne{builder}
}

// Query returns a query builder for RenewalLog.
func (c *RenewalLogClient) Query() *RenewalLogQuery {
	return &RenewalLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRenewalLog},
		inters: c.Interceptors(),
	}
}

// Get returns a RenewalLog entity by its id.
func (c *RenewalLogClient) Get(ctx context.Context, id int) (*RenewalLog, error) {
	return c.Query().Where(renewallog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RenewalLogClient) GetX(ctx context.Context, id int) *RenewalLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCertificate queries the certificate edge of a RenewalLog.
func (c *RenewalLogClient) QueryCertificate(_m *RenewalLog) *CertificateQuery {
	query := (&CertificateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(renewallog.Table, renewallog.FieldID, id),
			sqlgraph.To(certificate.Table, certificate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, renewallog.CertificateTable, renewallog.CertificateColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RenewalLogClient) Hooks() []Hook {
	return c.hooks.RenewalLog
}

// Interceptors returns the client interceptors.
func (c *RenewalLogClient) Interceptors() []Interceptor {
	return c.inters.RenewalLog
}

func (c *RenewalLogClient) mutate(ctx context.Context, m *RenewalLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RenewalLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RenewalLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RenewalLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RenewalLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RenewalLog mutation op: %q", m.Op())
	}
}

// ScanResultClient is a client for the ScanResult schema.
type ScanResultClient struct {
	config
}

// NewScanResultClient returns a client for the ScanResult from the given config.
func NewScanResultClient(c config) *ScanResultClient {
	return &ScanResultClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `scanresult.Hooks(f(g(h())))`.
func (c *ScanResultClient) Use(hooks ...Hook) {
	c.hooks.ScanResult = append(c.hooks.ScanResult, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `scanresult.Intercept(f(g(h())))`.
func (c *ScanResultClient) Intercept(interceptors ...Interceptor) {
	c.inters.ScanResult = append(c.inters.ScanResult, interceptors...)
}

// Create returns a builder for creating a ScanResult entity.
func (c *ScanResultClient) Create() *ScanResultCreate {
	mutation := newScanResultMutation(c.config, OpCreate)
	return &ScanResultCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ScanResult entities.
func (c *ScanResultClient) CreateBulk(builders ...*ScanResultCreate) *ScanResultCreateBulk {
	return &ScanResultCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScanResultClient) MapCreateBulk(slice any, setFunc func(*ScanResultCreate, int)) *ScanResultCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScanResultCreateBulk{err: fmt.Errorf("calling to ScanResultClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScanResultCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScanResultCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ScanResult.
func (c *ScanResultClient) Update() *ScanResultUpdate {
	mutation := newScanResultMutation(c.config, OpUpdate)
	return &ScanResultUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScanResultClient) UpdateOne(_m *ScanResult) *ScanResultUpdateOne {
	mutation := newScanResultMutation(c.config, OpUpdateOne, withScanResult(_m))
	return &ScanResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScanResultClient) UpdateOneID(id int) *ScanResultUpdateOne {
	mutation := newScanResultMutation(c.config, OpUpdateOne, withScanResultID(id))
	return &ScanResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ScanResult.
func (c *ScanResultClient) Delete() *ScanResultDelete {
	mutation := newScanResultMutation(c.config, OpDelete)
	return &ScanResultDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScanResultClient) DeleteOne(_m *ScanResult) *ScanResultDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScanResultClient) DeleteOneID(id int) *ScanResultDeleteOne {
	builder := c.Delete().Where(scanresult.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScanResultDeleteOne{builder}
}

// Query returns a query builder for ScanResult.
func (c *ScanResultClient) Query() *ScanResultQuery {
	return &ScanResultQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScanResult},
		inters: c.Interceptors(),
	}
}

// Get returns a ScanResult entity by its id.
func (c *ScanResultClient) Get(ctx context.Context, id int) (*ScanResult, error) {
	return c.Query().Where(scanresult.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScanResultClient) GetX(ctx context.Context, id int) *ScanResult {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ScanResultClient) Hooks() []Hook {
	return c.hooks.ScanResult
}

// Interceptors returns the client interceptors.
func (c *ScanResultClient) Interceptors() []Interceptor {
	return c.inters.ScanResult
}

func (c *ScanResultClient) mutate(ctx context.Context, m *ScanResultMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScanResultCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScanResultUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScanResultUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScanResultDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ScanResult mutation op: %q", m.Op())
	}
}

// TOTPCredentialClient is a client for the TOTPCredential schema.
type TOTPCredentialClient struct {
	config
}

// NewTOTPCredentialClient returns a client for the TOTPCredential from the given config.
func NewTOTPCredentialClient(c config) *TOTPCredentialClient {
	return &TOTPCredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `totpcredential.Hooks(f(g(h())))`.
func (c *TOTPCredentialClient) Use(hooks ...Hook) {
	c.hooks.TOTPCredential = append(c.hooks.TOTPCredential, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `totpcredential.Intercept(f(g(h())))`.
func (c *TOTPCredentialClient) Intercept(interceptors ...Interceptor) {
	c.inters.TOTPCredential = append(c.inters.TOTPCredential, interceptors...)
}

// Create returns a builder for creating a TOTPCredential entity.
func (c *TOTPCredentialClient) Create() *TOTPCredentialCreate {
	mutation := newTOTPCredentialMutation(c.config, OpCreate)
	return &TOTPCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TOTPCredential entities.
func (c *TOTPCredentialClient) CreateBulk(builders ...*TOTPCredentialCreate) *TOTPCredentialCreateBulk {
	return &TOTPCredentialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TOTPCredentialClient) MapCreateBulk(slice any, setFunc func(*TOTPCredentialCreate, int)) *TOTPCredentialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TOTPCredentialCreateBulk{err: fmt.Errorf("calling to TOTPCredentialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TOTPCredentialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TOTPCredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TOTPCredential.
func (c *TOTPCredentialClient) Update() *TOTPCredentialUpdate {
	mutation := newTOTPCredentialMutation(c.config, OpUpdate)
	return &TOTPCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TOTPCredentialClient) UpdateOne(_m *TOTPCredential) *TOTPCredentialUpdateOne {
	mutation := newTOTPCredentialMutation(c.config, OpUpdateOne, withTOTPCredential(_m))
	return &TOTPCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TOTPCredentialClient) UpdateOneID(id int) *TOTPCredentialUpdateOne {
	mutation := newTOTPCredentialMutation(c.config, OpUpdateOne, withTOTPCredentialID(id))
	return &TOTPCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TOTPCredential.
func (c *TOTPCredentialClient) Delete() *TOTPCredentialDelete {
	mutation := newTOTPCredentialMutation(c.config, OpDelete)
	return &TOTPCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TOTPCredentialClient) DeleteOne(_m *TOTPCredential) *TOTPCredentialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TOTPCredentialClient) DeleteOneID(id int) *TOTPCredentialDeleteOne {
	builder := c.Delete().Where(totpcredential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TOTPCredentialDeleteOne{builder}
}

// Query returns a query builder for TOTPCredential.
func (c *TOTPCredentialClient) Query() *TOTPCredentialQuery {
	return &TOTPCredentialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTOTPCredential},
		inters: c.Interceptors(),
	}
}

// Get returns a TOTPCredential entity by its id.
func (c *TOTPCredentialClient) Get(ctx context.Context, id int) (*TOTPCredential, error) {
	return c.Query().Where(totpcredential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TOTPCredentialClient) GetX(ctx context.Context, id int) *TOTPCredential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAuthMethod queries the auth_method edge of a TOTPCredential.
func (c *TOTPCredentialClient) QueryAuthMethod(_m *TOTPCredential) *AuthMethodQuery {
	query := (&AuthMethodClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(totpcredential.Table, totpcredential.FieldID, id),
			sqlgraph.To(authmethod.Table, authmethod.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, totpcredential.AuthMethodTable, totpcredential.AuthMethodColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TOTPCredentialClient) Hooks() []Hook {
	return c.hooks.TOTPCredential
}

// Interceptors returns the client interceptors.
func (c *TOTPCredentialClient) Interceptors() []Interceptor {
	return c.inters.TOTPCredential
}

func (c *TOTPCredentialClient) mutate(ctx context.Context, m *TOTPCredentialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TOTPCredentialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TOTPCredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TOTPCredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TOTPCredentialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TOTPCredential mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AuthMethod, CA, Certificate, DNSProvider, MonitoredDomain, Notification,
		PasskeyCredential, RenewalLog, ScanResult, TOTPCredential []ent.Hook
	}
	inters struct {
		AuthMethod, CA, Certificate, DNSProvider, MonitoredDomain, Notification,
		PasskeyCredential, RenewalLog, ScanResult, TOTPCredential []ent.Interceptor
	}
)
