// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cnb.cool/dtapp/certflow/ent/deploycredential"
	"cnb.cool/dtapp/certflow/ent/deploytarget"
	"cnb.cool/dtapp/certflow/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeployCredentialUpdate is the builder for updating DeployCredential entities.
type DeployCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *DeployCredentialMutation
}

// Where appends a list predicates to the DeployCredentialUpdate builder.
func (_u *DeployCredentialUpdate) Where(ps ...predicate.DeployCredential) *DeployCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DeployCredentialUpdate) SetName(v string) *DeployCredentialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeployCredentialUpdate) SetNillableName(v *string) *DeployCredentialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DeployCredentialUpdate) SetProviderType(v deploycredential.ProviderType) *DeployCredentialUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DeployCredentialUpdate) SetNillableProviderType(v *deploycredential.ProviderType) *DeployCredentialUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DeployCredentialUpdate) SetConfig(v []byte) *DeployCredentialUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DeployCredentialUpdate) ClearConfig() *DeployCredentialUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DeployCredentialUpdate) SetIsActive(v bool) *DeployCredentialUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DeployCredentialUpdate) SetNillableIsActive(v *bool) *DeployCredentialUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DeployCredentialUpdate) SetComment(v string) *DeployCredentialUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DeployCredentialUpdate) SetNillableComment(v *string) *DeployCredentialUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *DeployCredentialUpdate) ClearComment() *DeployCredentialUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployCredentialUpdate) SetUpdatedAt(v time.Time) *DeployCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDeployTargetIDs adds the "deploy_targets" edge to the DeployTarget entity by IDs.
func (_u *DeployCredentialUpdate) AddDeployTargetIDs(ids ...int) *DeployCredentialUpdate {
	_u.mutation.AddDeployTargetIDs(ids...)
	return _u
}

// AddDeployTargets adds the "deploy_targets" edges to the DeployTarget entity.
func (_u *DeployCredentialUpdate) AddDeployTargets(v ...*DeployTarget) *DeployCredentialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTargetIDs(ids...)
}

// Mutation returns the DeployCredentialMutation object of the builder.
func (_u *DeployCredentialUpdate) Mutation() *DeployCredentialMutation {
	return _u.mutation
}

// ClearDeployTargets clears all "deploy_targets" edges to the DeployTarget entity.
func (_u *DeployCredentialUpdate) ClearDeployTargets() *DeployCredentialUpdate {
	_u.mutation.ClearDeployTargets()
	return _u
}

// RemoveDeployTargetIDs removes the "deploy_targets" edge to DeployTarget entities by IDs.
func (_u *DeployCredentialUpdate) RemoveDeployTargetIDs(ids ...int) *DeployCredentialUpdate {
	_u.mutation.RemoveDeployTargetIDs(ids...)
	return _u
}

// RemoveDeployTargets removes "deploy_targets" edges to DeployTarget entities.
func (_u *DeployCredentialUpdate) RemoveDeployTargets(v ...*DeployTarget) *DeployCredentialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTargetIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeployCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeployCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployCredentialUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := deploycredential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeployCredential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := deploycredential.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "DeployCredential.provider_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploycredential.Table, deploycredential.Columns, sqlgraph.NewFieldSpec(deploycredential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deploycredential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(deploycredential.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(deploycredential.FieldConfig, field.TypeBytes, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(deploycredential.FieldConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(deploycredential.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(deploycredential.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(deploycredential.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTargetsIDs(); len(nodes) > 0 && !_u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeployCredentialUpdateOne is the builder for updating a single DeployCredential entity.
type DeployCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeployCredentialMutation
}

// SetName sets the "name" field.
func (_u *DeployCredentialUpdateOne) SetName(v string) *DeployCredentialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeployCredentialUpdateOne) SetNillableName(v *string) *DeployCredentialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DeployCredentialUpdateOne) SetProviderType(v deploycredential.ProviderType) *DeployCredentialUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DeployCredentialUpdateOne) SetNillableProviderType(v *deploycredential.ProviderType) *DeployCredentialUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *DeployCredentialUpdateOne) SetConfig(v []byte) *DeployCredentialUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *DeployCredentialUpdateOne) ClearConfig() *DeployCredentialUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DeployCredentialUpdateOne) SetIsActive(v bool) *DeployCredentialUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DeployCredentialUpdateOne) SetNillableIsActive(v *bool) *DeployCredentialUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *DeployCredentialUpdateOne) SetComment(v string) *DeployCredentialUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *DeployCredentialUpdateOne) SetNillableComment(v *string) *DeployCredentialUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *DeployCredentialUpdateOne) ClearComment() *DeployCredentialUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployCredentialUpdateOne) SetUpdatedAt(v time.Time) *DeployCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddDeployTargetIDs adds the "deploy_targets" edge to the DeployTarget entity by IDs.
func (_u *DeployCredentialUpdateOne) AddDeployTargetIDs(ids ...int) *DeployCredentialUpdateOne {
	_u.mutation.AddDeployTargetIDs(ids...)
	return _u
}

// AddDeployTargets adds the "deploy_targets" edges to the DeployTarget entity.
func (_u *DeployCredentialUpdateOne) AddDeployTargets(v ...*DeployTarget) *DeployCredentialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployTargetIDs(ids...)
}

// Mutation returns the DeployCredentialMutation object of the builder.
func (_u *DeployCredentialUpdateOne) Mutation() *DeployCredentialMutation {
	return _u.mutation
}

// ClearDeployTargets clears all "deploy_targets" edges to the DeployTarget entity.
func (_u *DeployCredentialUpdateOne) ClearDeployTargets() *DeployCredentialUpdateOne {
	_u.mutation.ClearDeployTargets()
	return _u
}

// RemoveDeployTargetIDs removes the "deploy_targets" edge to DeployTarget entities by IDs.
func (_u *DeployCredentialUpdateOne) RemoveDeployTargetIDs(ids ...int) *DeployCredentialUpdateOne {
	_u.mutation.RemoveDeployTargetIDs(ids...)
	return _u
}

// RemoveDeployTargets removes "deploy_targets" edges to DeployTarget entities.
func (_u *DeployCredentialUpdateOne) RemoveDeployTargets(v ...*DeployTarget) *DeployCredentialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployTargetIDs(ids...)
}

// Where appends a list predicates to the DeployCredentialUpdate builder.
func (_u *DeployCredentialUpdateOne) Where(ps ...predicate.DeployCredential) *DeployCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeployCredentialUpdateOne) Select(field string, fields ...string) *DeployCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeployCredential entity.
func (_u *DeployCredentialUpdateOne) Save(ctx context.Context) (*DeployCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployCredentialUpdateOne) SaveX(ctx context.Context) *DeployCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeployCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploycredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := deploycredential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeployCredential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := deploycredential.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "DeployCredential.provider_type": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployCredentialUpdateOne) sqlSave(ctx context.Context) (_node *DeployCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploycredential.Table, deploycredential.Columns, sqlgraph.NewFieldSpec(deploycredential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeployCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploycredential.FieldID)
		for _, f := range fields {
			if !deploycredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploycredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deploycredential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(deploycredential.FieldProviderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(deploycredential.FieldConfig, field.TypeBytes, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(deploycredential.FieldConfig, field.TypeBytes)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(deploycredential.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(deploycredential.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(deploycredential.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploycredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeployTargetsIDs(); len(nodes) > 0 && !_u.mutation.DeployTargetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploycredential.DeployTargetsTable,
			Columns: []string{deploycredential.DeployTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeployCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploycredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
