// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"cnb.cool/dtapp/certflow/ent/deploylog"
	"cnb.cool/dtapp/certflow/ent/deploytarget"
	"cnb.cool/dtapp/certflow/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeployLogUpdate is the builder for updating DeployLog entities.
type DeployLogUpdate struct {
	config
	hooks    []Hook
	mutation *DeployLogMutation
}

// Where appends a list predicates to the DeployLogUpdate builder.
func (_u *DeployLogUpdate) Where(ps ...predicate.DeployLog) *DeployLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCertID sets the "cert_id" field.
func (_u *DeployLogUpdate) SetCertID(v int) *DeployLogUpdate {
	_u.mutation.ResetCertID()
	_u.mutation.SetCertID(v)
	return _u
}

// SetNillableCertID sets the "cert_id" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableCertID(v *int) *DeployLogUpdate {
	if v != nil {
		_u.SetCertID(*v)
	}
	return _u
}

// AddCertID adds value to the "cert_id" field.
func (_u *DeployLogUpdate) AddCertID(v int) *DeployLogUpdate {
	_u.mutation.AddCertID(v)
	return _u
}

// SetCertDomain sets the "cert_domain" field.
func (_u *DeployLogUpdate) SetCertDomain(v string) *DeployLogUpdate {
	_u.mutation.SetCertDomain(v)
	return _u
}

// SetNillableCertDomain sets the "cert_domain" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableCertDomain(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetCertDomain(*v)
	}
	return _u
}

// SetDeployDomain sets the "deploy_domain" field.
func (_u *DeployLogUpdate) SetDeployDomain(v string) *DeployLogUpdate {
	_u.mutation.SetDeployDomain(v)
	return _u
}

// SetNillableDeployDomain sets the "deploy_domain" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableDeployDomain(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetDeployDomain(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *DeployLogUpdate) SetTargetName(v string) *DeployLogUpdate {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableTargetName(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// ClearTargetName clears the value of the "target_name" field.
func (_u *DeployLogUpdate) ClearTargetName() *DeployLogUpdate {
	_u.mutation.ClearTargetName()
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DeployLogUpdate) SetProviderType(v string) *DeployLogUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableProviderType(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// ClearProviderType clears the value of the "provider_type" field.
func (_u *DeployLogUpdate) ClearProviderType() *DeployLogUpdate {
	_u.mutation.ClearProviderType()
	return _u
}

// SetDeployService sets the "deploy_service" field.
func (_u *DeployLogUpdate) SetDeployService(v string) *DeployLogUpdate {
	_u.mutation.SetDeployService(v)
	return _u
}

// SetNillableDeployService sets the "deploy_service" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableDeployService(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetDeployService(*v)
	}
	return _u
}

// ClearDeployService clears the value of the "deploy_service" field.
func (_u *DeployLogUpdate) ClearDeployService() *DeployLogUpdate {
	_u.mutation.ClearDeployService()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *DeployLogUpdate) SetSuccess(v bool) *DeployLogUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableSuccess(v *bool) *DeployLogUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeployLogUpdate) SetMessage(v string) *DeployLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableMessage(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *DeployLogUpdate) ClearMessage() *DeployLogUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetResponse sets the "response" field.
func (_u *DeployLogUpdate) SetResponse(v string) *DeployLogUpdate {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableResponse(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *DeployLogUpdate) ClearResponse() *DeployLogUpdate {
	_u.mutation.ClearResponse()
	return _u
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (_u *DeployLogUpdate) SetCloudCertID(v string) *DeployLogUpdate {
	_u.mutation.SetCloudCertID(v)
	return _u
}

// SetNillableCloudCertID sets the "cloud_cert_id" field if the given value is not nil.
func (_u *DeployLogUpdate) SetNillableCloudCertID(v *string) *DeployLogUpdate {
	if v != nil {
		_u.SetCloudCertID(*v)
	}
	return _u
}

// ClearCloudCertID clears the value of the "cloud_cert_id" field.
func (_u *DeployLogUpdate) ClearCloudCertID() *DeployLogUpdate {
	_u.mutation.ClearCloudCertID()
	return _u
}

// SetDeployTargetID sets the "deploy_target" edge to the DeployTarget entity by ID.
func (_u *DeployLogUpdate) SetDeployTargetID(id int) *DeployLogUpdate {
	_u.mutation.SetDeployTargetID(id)
	return _u
}

// SetDeployTarget sets the "deploy_target" edge to the DeployTarget entity.
func (_u *DeployLogUpdate) SetDeployTarget(v *DeployTarget) *DeployLogUpdate {
	return _u.SetDeployTargetID(v.ID)
}

// Mutation returns the DeployLogMutation object of the builder.
func (_u *DeployLogUpdate) Mutation() *DeployLogMutation {
	return _u.mutation
}

// ClearDeployTarget clears the "deploy_target" edge to the DeployTarget entity.
func (_u *DeployLogUpdate) ClearDeployTarget() *DeployLogUpdate {
	_u.mutation.ClearDeployTarget()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeployLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeployLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployLogUpdate) check() error {
	if _u.mutation.DeployTargetCleared() && len(_u.mutation.DeployTargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeployLog.deploy_target"`)
	}
	return nil
}

func (_u *DeployLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploylog.Table, deploylog.Columns, sqlgraph.NewFieldSpec(deploylog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CertID(); ok {
		_spec.SetField(deploylog.FieldCertID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCertID(); ok {
		_spec.AddField(deploylog.FieldCertID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CertDomain(); ok {
		_spec.SetField(deploylog.FieldCertDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployDomain(); ok {
		_spec.SetField(deploylog.FieldDeployDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(deploylog.FieldTargetName, field.TypeString, value)
	}
	if _u.mutation.TargetNameCleared() {
		_spec.ClearField(deploylog.FieldTargetName, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(deploylog.FieldProviderType, field.TypeString, value)
	}
	if _u.mutation.ProviderTypeCleared() {
		_spec.ClearField(deploylog.FieldProviderType, field.TypeString)
	}
	if value, ok := _u.mutation.DeployService(); ok {
		_spec.SetField(deploylog.FieldDeployService, field.TypeString, value)
	}
	if _u.mutation.DeployServiceCleared() {
		_spec.ClearField(deploylog.FieldDeployService, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(deploylog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(deploylog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(deploylog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(deploylog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(deploylog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CloudCertID(); ok {
		_spec.SetField(deploylog.FieldCloudCertID, field.TypeString, value)
	}
	if _u.mutation.CloudCertIDCleared() {
		_spec.ClearField(deploylog.FieldCloudCertID, field.TypeString)
	}
	if _u.mutation.DeployTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploylog.DeployTargetTable,
			Columns: []string{deploylog.DeployTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploylog.DeployTargetTable,
			Columns: []string{deploylog.DeployTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeployLogUpdateOne is the builder for updating a single DeployLog entity.
type DeployLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeployLogMutation
}

// SetCertID sets the "cert_id" field.
func (_u *DeployLogUpdateOne) SetCertID(v int) *DeployLogUpdateOne {
	_u.mutation.ResetCertID()
	_u.mutation.SetCertID(v)
	return _u
}

// SetNillableCertID sets the "cert_id" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableCertID(v *int) *DeployLogUpdateOne {
	if v != nil {
		_u.SetCertID(*v)
	}
	return _u
}

// AddCertID adds value to the "cert_id" field.
func (_u *DeployLogUpdateOne) AddCertID(v int) *DeployLogUpdateOne {
	_u.mutation.AddCertID(v)
	return _u
}

// SetCertDomain sets the "cert_domain" field.
func (_u *DeployLogUpdateOne) SetCertDomain(v string) *DeployLogUpdateOne {
	_u.mutation.SetCertDomain(v)
	return _u
}

// SetNillableCertDomain sets the "cert_domain" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableCertDomain(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetCertDomain(*v)
	}
	return _u
}

// SetDeployDomain sets the "deploy_domain" field.
func (_u *DeployLogUpdateOne) SetDeployDomain(v string) *DeployLogUpdateOne {
	_u.mutation.SetDeployDomain(v)
	return _u
}

// SetNillableDeployDomain sets the "deploy_domain" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableDeployDomain(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetDeployDomain(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *DeployLogUpdateOne) SetTargetName(v string) *DeployLogUpdateOne {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableTargetName(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// ClearTargetName clears the value of the "target_name" field.
func (_u *DeployLogUpdateOne) ClearTargetName() *DeployLogUpdateOne {
	_u.mutation.ClearTargetName()
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *DeployLogUpdateOne) SetProviderType(v string) *DeployLogUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableProviderType(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// ClearProviderType clears the value of the "provider_type" field.
func (_u *DeployLogUpdateOne) ClearProviderType() *DeployLogUpdateOne {
	_u.mutation.ClearProviderType()
	return _u
}

// SetDeployService sets the "deploy_service" field.
func (_u *DeployLogUpdateOne) SetDeployService(v string) *DeployLogUpdateOne {
	_u.mutation.SetDeployService(v)
	return _u
}

// SetNillableDeployService sets the "deploy_service" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableDeployService(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetDeployService(*v)
	}
	return _u
}

// ClearDeployService clears the value of the "deploy_service" field.
func (_u *DeployLogUpdateOne) ClearDeployService() *DeployLogUpdateOne {
	_u.mutation.ClearDeployService()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *DeployLogUpdateOne) SetSuccess(v bool) *DeployLogUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableSuccess(v *bool) *DeployLogUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *DeployLogUpdateOne) SetMessage(v string) *DeployLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableMessage(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *DeployLogUpdateOne) ClearMessage() *DeployLogUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetResponse sets the "response" field.
func (_u *DeployLogUpdateOne) SetResponse(v string) *DeployLogUpdateOne {
	_u.mutation.SetResponse(v)
	return _u
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableResponse(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetResponse(*v)
	}
	return _u
}

// ClearResponse clears the value of the "response" field.
func (_u *DeployLogUpdateOne) ClearResponse() *DeployLogUpdateOne {
	_u.mutation.ClearResponse()
	return _u
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (_u *DeployLogUpdateOne) SetCloudCertID(v string) *DeployLogUpdateOne {
	_u.mutation.SetCloudCertID(v)
	return _u
}

// SetNillableCloudCertID sets the "cloud_cert_id" field if the given value is not nil.
func (_u *DeployLogUpdateOne) SetNillableCloudCertID(v *string) *DeployLogUpdateOne {
	if v != nil {
		_u.SetCloudCertID(*v)
	}
	return _u
}

// ClearCloudCertID clears the value of the "cloud_cert_id" field.
func (_u *DeployLogUpdateOne) ClearCloudCertID() *DeployLogUpdateOne {
	_u.mutation.ClearCloudCertID()
	return _u
}

// SetDeployTargetID sets the "deploy_target" edge to the DeployTarget entity by ID.
func (_u *DeployLogUpdateOne) SetDeployTargetID(id int) *DeployLogUpdateOne {
	_u.mutation.SetDeployTargetID(id)
	return _u
}

// SetDeployTarget sets the "deploy_target" edge to the DeployTarget entity.
func (_u *DeployLogUpdateOne) SetDeployTarget(v *DeployTarget) *DeployLogUpdateOne {
	return _u.SetDeployTargetID(v.ID)
}

// Mutation returns the DeployLogMutation object of the builder.
func (_u *DeployLogUpdateOne) Mutation() *DeployLogMutation {
	return _u.mutation
}

// ClearDeployTarget clears the "deploy_target" edge to the DeployTarget entity.
func (_u *DeployLogUpdateOne) ClearDeployTarget() *DeployLogUpdateOne {
	_u.mutation.ClearDeployTarget()
	return _u
}

// Where appends a list predicates to the DeployLogUpdate builder.
func (_u *DeployLogUpdateOne) Where(ps ...predicate.DeployLog) *DeployLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeployLogUpdateOne) Select(field string, fields ...string) *DeployLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeployLog entity.
func (_u *DeployLogUpdateOne) Save(ctx context.Context) (*DeployLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployLogUpdateOne) SaveX(ctx context.Context) *DeployLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeployLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployLogUpdateOne) check() error {
	if _u.mutation.DeployTargetCleared() && len(_u.mutation.DeployTargetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DeployLog.deploy_target"`)
	}
	return nil
}

func (_u *DeployLogUpdateOne) sqlSave(ctx context.Context) (_node *DeployLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploylog.Table, deploylog.Columns, sqlgraph.NewFieldSpec(deploylog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeployLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploylog.FieldID)
		for _, f := range fields {
			if !deploylog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CertID(); ok {
		_spec.SetField(deploylog.FieldCertID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCertID(); ok {
		_spec.AddField(deploylog.FieldCertID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CertDomain(); ok {
		_spec.SetField(deploylog.FieldCertDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployDomain(); ok {
		_spec.SetField(deploylog.FieldDeployDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(deploylog.FieldTargetName, field.TypeString, value)
	}
	if _u.mutation.TargetNameCleared() {
		_spec.ClearField(deploylog.FieldTargetName, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(deploylog.FieldProviderType, field.TypeString, value)
	}
	if _u.mutation.ProviderTypeCleared() {
		_spec.ClearField(deploylog.FieldProviderType, field.TypeString)
	}
	if value, ok := _u.mutation.DeployService(); ok {
		_spec.SetField(deploylog.FieldDeployService, field.TypeString, value)
	}
	if _u.mutation.DeployServiceCleared() {
		_spec.ClearField(deploylog.FieldDeployService, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(deploylog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(deploylog.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(deploylog.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Response(); ok {
		_spec.SetField(deploylog.FieldResponse, field.TypeString, value)
	}
	if _u.mutation.ResponseCleared() {
		_spec.ClearField(deploylog.FieldResponse, field.TypeString)
	}
	if value, ok := _u.mutation.CloudCertID(); ok {
		_spec.SetField(deploylog.FieldCloudCertID, field.TypeString, value)
	}
	if _u.mutation.CloudCertIDCleared() {
		_spec.ClearField(deploylog.FieldCloudCertID, field.TypeString)
	}
	if _u.mutation.DeployTargetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploylog.DeployTargetTable,
			Columns: []string{deploylog.DeployTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploylog.DeployTargetTable,
			Columns: []string{deploylog.DeployTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeployLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploylog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
