// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"cnb.cool/dtapp/certflow/ent/deploylog"
	"cnb.cool/dtapp/certflow/ent/deploytarget"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeployLogCreate is the builder for creating a DeployLog entity.
type DeployLogCreate struct {
	config
	mutation *DeployLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCertID sets the "cert_id" field.
func (_c *DeployLogCreate) SetCertID(v int) *DeployLogCreate {
	_c.mutation.SetCertID(v)
	return _c
}

// SetCertDomain sets the "cert_domain" field.
func (_c *DeployLogCreate) SetCertDomain(v string) *DeployLogCreate {
	_c.mutation.SetCertDomain(v)
	return _c
}

// SetDeployDomain sets the "deploy_domain" field.
func (_c *DeployLogCreate) SetDeployDomain(v string) *DeployLogCreate {
	_c.mutation.SetDeployDomain(v)
	return _c
}

// SetTargetName sets the "target_name" field.
func (_c *DeployLogCreate) SetTargetName(v string) *DeployLogCreate {
	_c.mutation.SetTargetName(v)
	return _c
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableTargetName(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetTargetName(*v)
	}
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *DeployLogCreate) SetProviderType(v string) *DeployLogCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableProviderType(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetProviderType(*v)
	}
	return _c
}

// SetDeployService sets the "deploy_service" field.
func (_c *DeployLogCreate) SetDeployService(v string) *DeployLogCreate {
	_c.mutation.SetDeployService(v)
	return _c
}

// SetNillableDeployService sets the "deploy_service" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableDeployService(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetDeployService(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *DeployLogCreate) SetSuccess(v bool) *DeployLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *DeployLogCreate) SetMessage(v string) *DeployLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableMessage(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetResponse sets the "response" field.
func (_c *DeployLogCreate) SetResponse(v string) *DeployLogCreate {
	_c.mutation.SetResponse(v)
	return _c
}

// SetNillableResponse sets the "response" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableResponse(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetResponse(*v)
	}
	return _c
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (_c *DeployLogCreate) SetCloudCertID(v string) *DeployLogCreate {
	_c.mutation.SetCloudCertID(v)
	return _c
}

// SetNillableCloudCertID sets the "cloud_cert_id" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableCloudCertID(v *string) *DeployLogCreate {
	if v != nil {
		_c.SetCloudCertID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeployLogCreate) SetCreatedAt(v time.Time) *DeployLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeployLogCreate) SetNillableCreatedAt(v *time.Time) *DeployLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeployTargetID sets the "deploy_target" edge to the DeployTarget entity by ID.
func (_c *DeployLogCreate) SetDeployTargetID(id int) *DeployLogCreate {
	_c.mutation.SetDeployTargetID(id)
	return _c
}

// SetDeployTarget sets the "deploy_target" edge to the DeployTarget entity.
func (_c *DeployLogCreate) SetDeployTarget(v *DeployTarget) *DeployLogCreate {
	return _c.SetDeployTargetID(v.ID)
}

// Mutation returns the DeployLogMutation object of the builder.
func (_c *DeployLogCreate) Mutation() *DeployLogMutation {
	return _c.mutation
}

// Save creates the DeployLog in the database.
func (_c *DeployLogCreate) Save(ctx context.Context) (*DeployLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeployLogCreate) SaveX(ctx context.Context) *DeployLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeployLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeployLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeployLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := deploylog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeployLogCreate) check() error {
	if _, ok := _c.mutation.CertID(); !ok {
		return &ValidationError{Name: "cert_id", err: errors.New(`ent: missing required field "DeployLog.cert_id"`)}
	}
	if _, ok := _c.mutation.CertDomain(); !ok {
		return &ValidationError{Name: "cert_domain", err: errors.New(`ent: missing required field "DeployLog.cert_domain"`)}
	}
	if _, ok := _c.mutation.DeployDomain(); !ok {
		return &ValidationError{Name: "deploy_domain", err: errors.New(`ent: missing required field "DeployLog.deploy_domain"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "DeployLog.success"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeployLog.created_at"`)}
	}
	if len(_c.mutation.DeployTargetIDs()) == 0 {
		return &ValidationError{Name: "deploy_target", err: errors.New(`ent: missing required edge "DeployLog.deploy_target"`)}
	}
	return nil
}

func (_c *DeployLogCreate) sqlSave(ctx context.Context) (*DeployLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeployLogCreate) createSpec() (*DeployLog, *sqlgraph.CreateSpec) {
	var (
		_node = &DeployLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deploylog.Table, sqlgraph.NewFieldSpec(deploylog.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CertID(); ok {
		_spec.SetField(deploylog.FieldCertID, field.TypeInt, value)
		_node.CertID = value
	}
	if value, ok := _c.mutation.CertDomain(); ok {
		_spec.SetField(deploylog.FieldCertDomain, field.TypeString, value)
		_node.CertDomain = value
	}
	if value, ok := _c.mutation.DeployDomain(); ok {
		_spec.SetField(deploylog.FieldDeployDomain, field.TypeString, value)
		_node.DeployDomain = value
	}
	if value, ok := _c.mutation.TargetName(); ok {
		_spec.SetField(deploylog.FieldTargetName, field.TypeString, value)
		_node.TargetName = value
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(deploylog.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.DeployService(); ok {
		_spec.SetField(deploylog.FieldDeployService, field.TypeString, value)
		_node.DeployService = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(deploylog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(deploylog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Response(); ok {
		_spec.SetField(deploylog.FieldResponse, field.TypeString, value)
		_node.Response = value
	}
	if value, ok := _c.mutation.CloudCertID(); ok {
		_spec.SetField(deploylog.FieldCloudCertID, field.TypeString, value)
		_node.CloudCertID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(deploylog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DeployTargetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploylog.DeployTargetTable,
			Columns: []string{deploylog.DeployTargetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploytarget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deploy_target_deploy_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeployLog.Create().
//		SetCertID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeployLogUpsert) {
//			SetCertID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeployLogCreate) OnConflict(opts ...sql.ConflictOption) *DeployLogUpsertOne {
	_c.conflict = opts
	return &DeployLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeployLogCreate) OnConflictColumns(columns ...string) *DeployLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeployLogUpsertOne{
		create: _c,
	}
}

type (
	// DeployLogUpsertOne is the builder for "upsert"-ing
	//  one DeployLog node.
	DeployLogUpsertOne struct {
		create *DeployLogCreate
	}

	// DeployLogUpsert is the "OnConflict" setter.
	DeployLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetCertID sets the "cert_id" field.
func (u *DeployLogUpsert) SetCertID(v int) *DeployLogUpsert {
	u.Set(deploylog.FieldCertID, v)
	return u
}

// UpdateCertID sets the "cert_id" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateCertID() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldCertID)
	return u
}

// AddCertID adds v to the "cert_id" field.
func (u *DeployLogUpsert) AddCertID(v int) *DeployLogUpsert {
	u.Add(deploylog.FieldCertID, v)
	return u
}

// SetCertDomain sets the "cert_domain" field.
func (u *DeployLogUpsert) SetCertDomain(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldCertDomain, v)
	return u
}

// UpdateCertDomain sets the "cert_domain" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateCertDomain() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldCertDomain)
	return u
}

// SetDeployDomain sets the "deploy_domain" field.
func (u *DeployLogUpsert) SetDeployDomain(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldDeployDomain, v)
	return u
}

// UpdateDeployDomain sets the "deploy_domain" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateDeployDomain() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldDeployDomain)
	return u
}

// SetTargetName sets the "target_name" field.
func (u *DeployLogUpsert) SetTargetName(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldTargetName, v)
	return u
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateTargetName() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldTargetName)
	return u
}

// ClearTargetName clears the value of the "target_name" field.
func (u *DeployLogUpsert) ClearTargetName() *DeployLogUpsert {
	u.SetNull(deploylog.FieldTargetName)
	return u
}

// SetProviderType sets the "provider_type" field.
func (u *DeployLogUpsert) SetProviderType(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldProviderType, v)
	return u
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateProviderType() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldProviderType)
	return u
}

// ClearProviderType clears the value of the "provider_type" field.
func (u *DeployLogUpsert) ClearProviderType() *DeployLogUpsert {
	u.SetNull(deploylog.FieldProviderType)
	return u
}

// SetDeployService sets the "deploy_service" field.
func (u *DeployLogUpsert) SetDeployService(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldDeployService, v)
	return u
}

// UpdateDeployService sets the "deploy_service" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateDeployService() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldDeployService)
	return u
}

// ClearDeployService clears the value of the "deploy_service" field.
func (u *DeployLogUpsert) ClearDeployService() *DeployLogUpsert {
	u.SetNull(deploylog.FieldDeployService)
	return u
}

// SetSuccess sets the "success" field.
func (u *DeployLogUpsert) SetSuccess(v bool) *DeployLogUpsert {
	u.Set(deploylog.FieldSuccess, v)
	return u
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateSuccess() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldSuccess)
	return u
}

// SetMessage sets the "message" field.
func (u *DeployLogUpsert) SetMessage(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateMessage() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *DeployLogUpsert) ClearMessage() *DeployLogUpsert {
	u.SetNull(deploylog.FieldMessage)
	return u
}

// SetResponse sets the "response" field.
func (u *DeployLogUpsert) SetResponse(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldResponse, v)
	return u
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateResponse() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldResponse)
	return u
}

// ClearResponse clears the value of the "response" field.
func (u *DeployLogUpsert) ClearResponse() *DeployLogUpsert {
	u.SetNull(deploylog.FieldResponse)
	return u
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (u *DeployLogUpsert) SetCloudCertID(v string) *DeployLogUpsert {
	u.Set(deploylog.FieldCloudCertID, v)
	return u
}

// UpdateCloudCertID sets the "cloud_cert_id" field to the value that was provided on create.
func (u *DeployLogUpsert) UpdateCloudCertID() *DeployLogUpsert {
	u.SetExcluded(deploylog.FieldCloudCertID)
	return u
}

// ClearCloudCertID clears the value of the "cloud_cert_id" field.
func (u *DeployLogUpsert) ClearCloudCertID() *DeployLogUpsert {
	u.SetNull(deploylog.FieldCloudCertID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeployLogUpsertOne) UpdateNewValues() *DeployLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(deploylog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeployLogUpsertOne) Ignore() *DeployLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeployLogUpsertOne) DoNothing() *DeployLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeployLogCreate.OnConflict
// documentation for more info.
func (u *DeployLogUpsertOne) Update(set func(*DeployLogUpsert)) *DeployLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeployLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCertID sets the "cert_id" field.
func (u *DeployLogUpsertOne) SetCertID(v int) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCertID(v)
	})
}

// AddCertID adds v to the "cert_id" field.
func (u *DeployLogUpsertOne) AddCertID(v int) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.AddCertID(v)
	})
}

// UpdateCertID sets the "cert_id" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateCertID() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCertID()
	})
}

// SetCertDomain sets the "cert_domain" field.
func (u *DeployLogUpsertOne) SetCertDomain(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCertDomain(v)
	})
}

// UpdateCertDomain sets the "cert_domain" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateCertDomain() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCertDomain()
	})
}

// SetDeployDomain sets the "deploy_domain" field.
func (u *DeployLogUpsertOne) SetDeployDomain(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetDeployDomain(v)
	})
}

// UpdateDeployDomain sets the "deploy_domain" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateDeployDomain() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateDeployDomain()
	})
}

// SetTargetName sets the "target_name" field.
func (u *DeployLogUpsertOne) SetTargetName(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetTargetName(v)
	})
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateTargetName() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateTargetName()
	})
}

// ClearTargetName clears the value of the "target_name" field.
func (u *DeployLogUpsertOne) ClearTargetName() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearTargetName()
	})
}

// SetProviderType sets the "provider_type" field.
func (u *DeployLogUpsertOne) SetProviderType(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetProviderType(v)
	})
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateProviderType() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateProviderType()
	})
}

// ClearProviderType clears the value of the "provider_type" field.
func (u *DeployLogUpsertOne) ClearProviderType() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearProviderType()
	})
}

// SetDeployService sets the "deploy_service" field.
func (u *DeployLogUpsertOne) SetDeployService(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetDeployService(v)
	})
}

// UpdateDeployService sets the "deploy_service" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateDeployService() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateDeployService()
	})
}

// ClearDeployService clears the value of the "deploy_service" field.
func (u *DeployLogUpsertOne) ClearDeployService() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearDeployService()
	})
}

// SetSuccess sets the "success" field.
func (u *DeployLogUpsertOne) SetSuccess(v bool) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateSuccess() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateSuccess()
	})
}

// SetMessage sets the "message" field.
func (u *DeployLogUpsertOne) SetMessage(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateMessage() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *DeployLogUpsertOne) ClearMessage() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearMessage()
	})
}

// SetResponse sets the "response" field.
func (u *DeployLogUpsertOne) SetResponse(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateResponse() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *DeployLogUpsertOne) ClearResponse() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearResponse()
	})
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (u *DeployLogUpsertOne) SetCloudCertID(v string) *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCloudCertID(v)
	})
}

// UpdateCloudCertID sets the "cloud_cert_id" field to the value that was provided on create.
func (u *DeployLogUpsertOne) UpdateCloudCertID() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCloudCertID()
	})
}

// ClearCloudCertID clears the value of the "cloud_cert_id" field.
func (u *DeployLogUpsertOne) ClearCloudCertID() *DeployLogUpsertOne {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearCloudCertID()
	})
}

// Exec executes the query.
func (u *DeployLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeployLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeployLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeployLogUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeployLogUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeployLogCreateBulk is the builder for creating many DeployLog entities in bulk.
type DeployLogCreateBulk struct {
	config
	err      error
	builders []*DeployLogCreate
	conflict []sql.ConflictOption
}

// Save creates the DeployLog entities in the database.
func (_c *DeployLogCreateBulk) Save(ctx context.Context) ([]*DeployLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeployLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeployLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeployLogCreateBulk) SaveX(ctx context.Context) []*DeployLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeployLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeployLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeployLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeployLogUpsert) {
//			SetCertID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeployLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeployLogUpsertBulk {
	_c.conflict = opts
	return &DeployLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeployLogCreateBulk) OnConflictColumns(columns ...string) *DeployLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeployLogUpsertBulk{
		create: _c,
	}
}

// DeployLogUpsertBulk is the builder for "upsert"-ing
// a bulk of DeployLog nodes.
type DeployLogUpsertBulk struct {
	create *DeployLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeployLogUpsertBulk) UpdateNewValues() *DeployLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(deploylog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeployLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeployLogUpsertBulk) Ignore() *DeployLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeployLogUpsertBulk) DoNothing() *DeployLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeployLogCreateBulk.OnConflict
// documentation for more info.
func (u *DeployLogUpsertBulk) Update(set func(*DeployLogUpsert)) *DeployLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeployLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCertID sets the "cert_id" field.
func (u *DeployLogUpsertBulk) SetCertID(v int) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCertID(v)
	})
}

// AddCertID adds v to the "cert_id" field.
func (u *DeployLogUpsertBulk) AddCertID(v int) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.AddCertID(v)
	})
}

// UpdateCertID sets the "cert_id" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateCertID() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCertID()
	})
}

// SetCertDomain sets the "cert_domain" field.
func (u *DeployLogUpsertBulk) SetCertDomain(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCertDomain(v)
	})
}

// UpdateCertDomain sets the "cert_domain" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateCertDomain() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCertDomain()
	})
}

// SetDeployDomain sets the "deploy_domain" field.
func (u *DeployLogUpsertBulk) SetDeployDomain(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetDeployDomain(v)
	})
}

// UpdateDeployDomain sets the "deploy_domain" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateDeployDomain() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateDeployDomain()
	})
}

// SetTargetName sets the "target_name" field.
func (u *DeployLogUpsertBulk) SetTargetName(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetTargetName(v)
	})
}

// UpdateTargetName sets the "target_name" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateTargetName() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateTargetName()
	})
}

// ClearTargetName clears the value of the "target_name" field.
func (u *DeployLogUpsertBulk) ClearTargetName() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearTargetName()
	})
}

// SetProviderType sets the "provider_type" field.
func (u *DeployLogUpsertBulk) SetProviderType(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetProviderType(v)
	})
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateProviderType() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateProviderType()
	})
}

// ClearProviderType clears the value of the "provider_type" field.
func (u *DeployLogUpsertBulk) ClearProviderType() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearProviderType()
	})
}

// SetDeployService sets the "deploy_service" field.
func (u *DeployLogUpsertBulk) SetDeployService(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetDeployService(v)
	})
}

// UpdateDeployService sets the "deploy_service" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateDeployService() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateDeployService()
	})
}

// ClearDeployService clears the value of the "deploy_service" field.
func (u *DeployLogUpsertBulk) ClearDeployService() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearDeployService()
	})
}

// SetSuccess sets the "success" field.
func (u *DeployLogUpsertBulk) SetSuccess(v bool) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetSuccess(v)
	})
}

// UpdateSuccess sets the "success" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateSuccess() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateSuccess()
	})
}

// SetMessage sets the "message" field.
func (u *DeployLogUpsertBulk) SetMessage(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateMessage() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *DeployLogUpsertBulk) ClearMessage() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearMessage()
	})
}

// SetResponse sets the "response" field.
func (u *DeployLogUpsertBulk) SetResponse(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetResponse(v)
	})
}

// UpdateResponse sets the "response" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateResponse() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateResponse()
	})
}

// ClearResponse clears the value of the "response" field.
func (u *DeployLogUpsertBulk) ClearResponse() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearResponse()
	})
}

// SetCloudCertID sets the "cloud_cert_id" field.
func (u *DeployLogUpsertBulk) SetCloudCertID(v string) *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.SetCloudCertID(v)
	})
}

// UpdateCloudCertID sets the "cloud_cert_id" field to the value that was provided on create.
func (u *DeployLogUpsertBulk) UpdateCloudCertID() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.UpdateCloudCertID()
	})
}

// ClearCloudCertID clears the value of the "cloud_cert_id" field.
func (u *DeployLogUpsertBulk) ClearCloudCertID() *DeployLogUpsertBulk {
	return u.Update(func(s *DeployLogUpsert) {
		s.ClearCloudCertID()
	})
}

// Exec executes the query.
func (u *DeployLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeployLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeployLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeployLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
