// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"cnb.cool/dtapp/certflow/ent/monitorchecklog"
	"cnb.cool/dtapp/certflow/ent/monitoreddomain"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MonitorCheckLog is the model entity for the MonitorCheckLog schema.
type MonitorCheckLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 检查时间
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// 检查状态
	Status monitorchecklog.Status `json:"status,omitempty"`
	// 证书剩余天数（HTTP 检查无证书时为 null）
	CertRemainingDays *int `json:"cert_remaining_days,omitempty"`
	// 响应时间（毫秒）
	ResponseTimeMs *int `json:"response_time_ms,omitempty"`
	// HTTP 响应码
	HTTPStatusCode *int `json:"http_status_code,omitempty"`
	// 检查错误信息
	LastCheckError string `json:"last_check_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MonitorCheckLogQuery when eager-loading is set.
	Edges                       MonitorCheckLogEdges `json:"edges"`
	monitored_domain_check_logs *int
	selectValues                sql.SelectValues
}

// MonitorCheckLogEdges holds the relations/edges for other nodes in the graph.
type MonitorCheckLogEdges struct {
	// 关联的监控域名
	Domain *MonitoredDomain `json:"domain,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DomainOrErr returns the Domain value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckLogEdges) DomainOrErr() (*MonitoredDomain, error) {
	if e.Domain != nil {
		return e.Domain, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: monitoreddomain.Label}
	}
	return nil, &NotLoadedError{edge: "domain"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorCheckLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorchecklog.FieldID, monitorchecklog.FieldCertRemainingDays, monitorchecklog.FieldResponseTimeMs, monitorchecklog.FieldHTTPStatusCode:
			values[i] = new(sql.NullInt64)
		case monitorchecklog.FieldStatus, monitorchecklog.FieldLastCheckError:
			values[i] = new(sql.NullString)
		case monitorchecklog.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		case monitorchecklog.ForeignKeys[0]: // monitored_domain_check_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorCheckLog fields.
func (_m *MonitorCheckLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorchecklog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case monitorchecklog.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		case monitorchecklog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = monitorchecklog.Status(value.String)
			}
		case monitorchecklog.FieldCertRemainingDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cert_remaining_days", values[i])
			} else if value.Valid {
				_m.CertRemainingDays = new(int)
				*_m.CertRemainingDays = int(value.Int64)
			}
		case monitorchecklog.FieldResponseTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_time_ms", values[i])
			} else if value.Valid {
				_m.ResponseTimeMs = new(int)
				*_m.ResponseTimeMs = int(value.Int64)
			}
		case monitorchecklog.FieldHTTPStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status_code", values[i])
			} else if value.Valid {
				_m.HTTPStatusCode = new(int)
				*_m.HTTPStatusCode = int(value.Int64)
			}
		case monitorchecklog.FieldLastCheckError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_check_error", values[i])
			} else if value.Valid {
				_m.LastCheckError = value.String
			}
		case monitorchecklog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field monitored_domain_check_logs", value)
			} else if value.Valid {
				_m.monitored_domain_check_logs = new(int)
				*_m.monitored_domain_check_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorCheckLog.
// This includes values selected through modifiers, order, etc.
func (_m *MonitorCheckLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDomain queries the "domain" edge of the MonitorCheckLog entity.
func (_m *MonitorCheckLog) QueryDomain() *MonitoredDomainQuery {
	return NewMonitorCheckLogClient(_m.config).QueryDomain(_m)
}

// Update returns a builder for updating this MonitorCheckLog.
// Note that you need to call MonitorCheckLog.Unwrap() before calling this method if this MonitorCheckLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MonitorCheckLog) Update() *MonitorCheckLogUpdateOne {
	return NewMonitorCheckLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MonitorCheckLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MonitorCheckLog) Unwrap() *MonitorCheckLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorCheckLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MonitorCheckLog) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorCheckLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.CertRemainingDays; v != nil {
		builder.WriteString("cert_remaining_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResponseTimeMs; v != nil {
		builder.WriteString("response_time_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.HTTPStatusCode; v != nil {
		builder.WriteString("http_status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("last_check_error=")
	builder.WriteString(_m.LastCheckError)
	builder.WriteByte(')')
	return builder.String()
}

// MonitorCheckLogs is a parsable slice of MonitorCheckLog.
type MonitorCheckLogs []*MonitorCheckLog
