// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"cnb.cool/dtapp/certflow/ent/predicate"
	"cnb.cool/dtapp/certflow/ent/scanresult"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScanResultDelete is the builder for deleting a ScanResult entity.
type ScanResultDelete struct {
	config
	hooks    []Hook
	mutation *ScanResultMutation
}

// Where appends a list predicates to the ScanResultDelete builder.
func (_d *ScanResultDelete) Where(ps ...predicate.ScanResult) *ScanResultDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ScanResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScanResultDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ScanResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scanresult.Table, sqlgraph.NewFieldSpec(scanresult.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ScanResultDeleteOne is the builder for deleting a single ScanResult entity.
type ScanResultDeleteOne struct {
	_d *ScanResultDelete
}

// Where appends a list predicates to the ScanResultDelete builder.
func (_d *ScanResultDeleteOne) Where(ps ...predicate.ScanResult) *ScanResultDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ScanResultDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scanresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ScanResultDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
