// Code generated by ent, DO NOT EDIT.

package ent_log

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"sync"
	"time"

	"cnb.cool/dtapp/certflow/ent_log/httplog"
	"cnb.cool/dtapp/certflow/ent_log/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHttpLog = "HttpLog"
)

// HttpLogMutation represents an operation that mutates the HttpLog nodes in the graph.
type HttpLogMutation struct {
	config
	op                     Op
	typ                    string
	id                     *int
	hostname               *string
	method                 *string
	url                    *string
	request_headers        *map[string][]string
	request_body           *jsontext.Value
	appendrequest_body     jsontext.Value
	status_code            *int
	addstatus_code         *int
	response_headers       *map[string][]string
	response_body          *jsontext.Value
	appendresponse_body    jsontext.Value
	elapse_time            *int64
	addelapse_time         *int64
	process_elapse_time    *int64
	addprocess_elapse_time *int64
	is_error               *bool
	created_at             *time.Time
	go_version             *string
	plugin_version         *string
	clearedFields          map[string]struct{}
	done                   bool
	oldValue               func(context.Context) (*HttpLog, error)
	predicates             []predicate.HttpLog
}

var _ ent.Mutation = (*HttpLogMutation)(nil)

// httplogOption allows management of the mutation configuration using functional options.
type httplogOption func(*HttpLogMutation)

// newHttpLogMutation creates new mutation for the HttpLog entity.
func newHttpLogMutation(c config, op Op, opts ...httplogOption) *HttpLogMutation {
	m := &HttpLogMutation{
		config:        c,
		op:            op,
		typ:           TypeHttpLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHttpLogID sets the ID field of the mutation.
func withHttpLogID(id int) httplogOption {
	return func(m *HttpLogMutation) {
		var (
			err   error
			once  sync.Once
			value *HttpLog
		)
		m.oldValue = func(ctx context.Context) (*HttpLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().HttpLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHttpLog sets the old HttpLog of the mutation.
func withHttpLog(node *HttpLog) httplogOption {
	return func(m *HttpLogMutation) {
		m.oldValue = func(context.Context) (*HttpLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HttpLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HttpLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent_log: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HttpLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HttpLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().HttpLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHostname sets the "hostname" field.
func (m *HttpLogMutation) SetHostname(s string) {
	m.hostname = &s
}

// Hostname returns the value of the "hostname" field in the mutation.
func (m *HttpLogMutation) Hostname() (r string, exists bool) {
	v := m.hostname
	if v == nil {
		return
	}
	return *v, true
}

// OldHostname returns the old "hostname" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldHostname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHostname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHostname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHostname: %w", err)
	}
	return oldValue.Hostname, nil
}

// ClearHostname clears the value of the "hostname" field.
func (m *HttpLogMutation) ClearHostname() {
	m.hostname = nil
	m.clearedFields[httplog.FieldHostname] = struct{}{}
}

// HostnameCleared returns if the "hostname" field was cleared in this mutation.
func (m *HttpLogMutation) HostnameCleared() bool {
	_, ok := m.clearedFields[httplog.FieldHostname]
	return ok
}

// ResetHostname resets all changes to the "hostname" field.
func (m *HttpLogMutation) ResetHostname() {
	m.hostname = nil
	delete(m.clearedFields, httplog.FieldHostname)
}

// SetMethod sets the "method" field.
func (m *HttpLogMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *HttpLogMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ClearMethod clears the value of the "method" field.
func (m *HttpLogMutation) ClearMethod() {
	m.method = nil
	m.clearedFields[httplog.FieldMethod] = struct{}{}
}

// MethodCleared returns if the "method" field was cleared in this mutation.
func (m *HttpLogMutation) MethodCleared() bool {
	_, ok := m.clearedFields[httplog.FieldMethod]
	return ok
}

// ResetMethod resets all changes to the "method" field.
func (m *HttpLogMutation) ResetMethod() {
	m.method = nil
	delete(m.clearedFields, httplog.FieldMethod)
}

// SetURL sets the "url" field.
func (m *HttpLogMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *HttpLogMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ClearURL clears the value of the "url" field.
func (m *HttpLogMutation) ClearURL() {
	m.url = nil
	m.clearedFields[httplog.FieldURL] = struct{}{}
}

// URLCleared returns if the "url" field was cleared in this mutation.
func (m *HttpLogMutation) URLCleared() bool {
	_, ok := m.clearedFields[httplog.FieldURL]
	return ok
}

// ResetURL resets all changes to the "url" field.
func (m *HttpLogMutation) ResetURL() {
	m.url = nil
	delete(m.clearedFields, httplog.FieldURL)
}

// SetRequestHeaders sets the "request_headers" field.
func (m *HttpLogMutation) SetRequestHeaders(value map[string][]string) {
	m.request_headers = &value
}

// RequestHeaders returns the value of the "request_headers" field in the mutation.
func (m *HttpLogMutation) RequestHeaders() (r map[string][]string, exists bool) {
	v := m.request_headers
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestHeaders returns the old "request_headers" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldRequestHeaders(ctx context.Context) (v map[string][]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestHeaders: %w", err)
	}
	return oldValue.RequestHeaders, nil
}

// ClearRequestHeaders clears the value of the "request_headers" field.
func (m *HttpLogMutation) ClearRequestHeaders() {
	m.request_headers = nil
	m.clearedFields[httplog.FieldRequestHeaders] = struct{}{}
}

// RequestHeadersCleared returns if the "request_headers" field was cleared in this mutation.
func (m *HttpLogMutation) RequestHeadersCleared() bool {
	_, ok := m.clearedFields[httplog.FieldRequestHeaders]
	return ok
}

// ResetRequestHeaders resets all changes to the "request_headers" field.
func (m *HttpLogMutation) ResetRequestHeaders() {
	m.request_headers = nil
	delete(m.clearedFields, httplog.FieldRequestHeaders)
}

// SetRequestBody sets the "request_body" field.
func (m *HttpLogMutation) SetRequestBody(j jsontext.Value) {
	m.request_body = &j
	m.appendrequest_body = nil
}

// RequestBody returns the value of the "request_body" field in the mutation.
func (m *HttpLogMutation) RequestBody() (r jsontext.Value, exists bool) {
	v := m.request_body
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestBody returns the old "request_body" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldRequestBody(ctx context.Context) (v jsontext.Value, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestBody: %w", err)
	}
	return oldValue.RequestBody, nil
}

// AppendRequestBody adds j to the "request_body" field.
func (m *HttpLogMutation) AppendRequestBody(j jsontext.Value) {
	m.appendrequest_body = append(m.appendrequest_body, j...)
}

// AppendedRequestBody returns the list of values that were appended to the "request_body" field in this mutation.
func (m *HttpLogMutation) AppendedRequestBody() (jsontext.Value, bool) {
	if len(m.appendrequest_body) == 0 {
		return nil, false
	}
	return m.appendrequest_body, true
}

// ClearRequestBody clears the value of the "request_body" field.
func (m *HttpLogMutation) ClearRequestBody() {
	m.request_body = nil
	m.appendrequest_body = nil
	m.clearedFields[httplog.FieldRequestBody] = struct{}{}
}

// RequestBodyCleared returns if the "request_body" field was cleared in this mutation.
func (m *HttpLogMutation) RequestBodyCleared() bool {
	_, ok := m.clearedFields[httplog.FieldRequestBody]
	return ok
}

// ResetRequestBody resets all changes to the "request_body" field.
func (m *HttpLogMutation) ResetRequestBody() {
	m.request_body = nil
	m.appendrequest_body = nil
	delete(m.clearedFields, httplog.FieldRequestBody)
}

// SetStatusCode sets the "status_code" field.
func (m *HttpLogMutation) SetStatusCode(i int) {
	m.status_code = &i
	m.addstatus_code = nil
}

// StatusCode returns the value of the "status_code" field in the mutation.
func (m *HttpLogMutation) StatusCode() (r int, exists bool) {
	v := m.status_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStatusCode returns the old "status_code" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldStatusCode(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatusCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatusCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatusCode: %w", err)
	}
	return oldValue.StatusCode, nil
}

// AddStatusCode adds i to the "status_code" field.
func (m *HttpLogMutation) AddStatusCode(i int) {
	if m.addstatus_code != nil {
		*m.addstatus_code += i
	} else {
		m.addstatus_code = &i
	}
}

// AddedStatusCode returns the value that was added to the "status_code" field in this mutation.
func (m *HttpLogMutation) AddedStatusCode() (r int, exists bool) {
	v := m.addstatus_code
	if v == nil {
		return
	}
	return *v, true
}

// ClearStatusCode clears the value of the "status_code" field.
func (m *HttpLogMutation) ClearStatusCode() {
	m.status_code = nil
	m.addstatus_code = nil
	m.clearedFields[httplog.FieldStatusCode] = struct{}{}
}

// StatusCodeCleared returns if the "status_code" field was cleared in this mutation.
func (m *HttpLogMutation) StatusCodeCleared() bool {
	_, ok := m.clearedFields[httplog.FieldStatusCode]
	return ok
}

// ResetStatusCode resets all changes to the "status_code" field.
func (m *HttpLogMutation) ResetStatusCode() {
	m.status_code = nil
	m.addstatus_code = nil
	delete(m.clearedFields, httplog.FieldStatusCode)
}

// SetResponseHeaders sets the "response_headers" field.
func (m *HttpLogMutation) SetResponseHeaders(value map[string][]string) {
	m.response_headers = &value
}

// ResponseHeaders returns the value of the "response_headers" field in the mutation.
func (m *HttpLogMutation) ResponseHeaders() (r map[string][]string, exists bool) {
	v := m.response_headers
	if v == nil {
		return
	}
	return *v, true
}

// OldResponseHeaders returns the old "response_headers" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldResponseHeaders(ctx context.Context) (v map[string][]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponseHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponseHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponseHeaders: %w", err)
	}
	return oldValue.ResponseHeaders, nil
}

// ClearResponseHeaders clears the value of the "response_headers" field.
func (m *HttpLogMutation) ClearResponseHeaders() {
	m.response_headers = nil
	m.clearedFields[httplog.FieldResponseHeaders] = struct{}{}
}

// ResponseHeadersCleared returns if the "response_headers" field was cleared in this mutation.
func (m *HttpLogMutation) ResponseHeadersCleared() bool {
	_, ok := m.clearedFields[httplog.FieldResponseHeaders]
	return ok
}

// ResetResponseHeaders resets all changes to the "response_headers" field.
func (m *HttpLogMutation) ResetResponseHeaders() {
	m.response_headers = nil
	delete(m.clearedFields, httplog.FieldResponseHeaders)
}

// SetResponseBody sets the "response_body" field.
func (m *HttpLogMutation) SetResponseBody(j jsontext.Value) {
	m.response_body = &j
	m.appendresponse_body = nil
}

// ResponseBody returns the value of the "response_body" field in the mutation.
func (m *HttpLogMutation) ResponseBody() (r jsontext.Value, exists bool) {
	v := m.response_body
	if v == nil {
		return
	}
	return *v, true
}

// OldResponseBody returns the old "response_body" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldResponseBody(ctx context.Context) (v jsontext.Value, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResponseBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResponseBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResponseBody: %w", err)
	}
	return oldValue.ResponseBody, nil
}

// AppendResponseBody adds j to the "response_body" field.
func (m *HttpLogMutation) AppendResponseBody(j jsontext.Value) {
	m.appendresponse_body = append(m.appendresponse_body, j...)
}

// AppendedResponseBody returns the list of values that were appended to the "response_body" field in this mutation.
func (m *HttpLogMutation) AppendedResponseBody() (jsontext.Value, bool) {
	if len(m.appendresponse_body) == 0 {
		return nil, false
	}
	return m.appendresponse_body, true
}

// ClearResponseBody clears the value of the "response_body" field.
func (m *HttpLogMutation) ClearResponseBody() {
	m.response_body = nil
	m.appendresponse_body = nil
	m.clearedFields[httplog.FieldResponseBody] = struct{}{}
}

// ResponseBodyCleared returns if the "response_body" field was cleared in this mutation.
func (m *HttpLogMutation) ResponseBodyCleared() bool {
	_, ok := m.clearedFields[httplog.FieldResponseBody]
	return ok
}

// ResetResponseBody resets all changes to the "response_body" field.
func (m *HttpLogMutation) ResetResponseBody() {
	m.response_body = nil
	m.appendresponse_body = nil
	delete(m.clearedFields, httplog.FieldResponseBody)
}

// SetElapseTime sets the "elapse_time" field.
func (m *HttpLogMutation) SetElapseTime(i int64) {
	m.elapse_time = &i
	m.addelapse_time = nil
}

// ElapseTime returns the value of the "elapse_time" field in the mutation.
func (m *HttpLogMutation) ElapseTime() (r int64, exists bool) {
	v := m.elapse_time
	if v == nil {
		return
	}
	return *v, true
}

// OldElapseTime returns the old "elapse_time" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldElapseTime(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldElapseTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldElapseTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldElapseTime: %w", err)
	}
	return oldValue.ElapseTime, nil
}

// AddElapseTime adds i to the "elapse_time" field.
func (m *HttpLogMutation) AddElapseTime(i int64) {
	if m.addelapse_time != nil {
		*m.addelapse_time += i
	} else {
		m.addelapse_time = &i
	}
}

// AddedElapseTime returns the value that was added to the "elapse_time" field in this mutation.
func (m *HttpLogMutation) AddedElapseTime() (r int64, exists bool) {
	v := m.addelapse_time
	if v == nil {
		return
	}
	return *v, true
}

// ClearElapseTime clears the value of the "elapse_time" field.
func (m *HttpLogMutation) ClearElapseTime() {
	m.elapse_time = nil
	m.addelapse_time = nil
	m.clearedFields[httplog.FieldElapseTime] = struct{}{}
}

// ElapseTimeCleared returns if the "elapse_time" field was cleared in this mutation.
func (m *HttpLogMutation) ElapseTimeCleared() bool {
	_, ok := m.clearedFields[httplog.FieldElapseTime]
	return ok
}

// ResetElapseTime resets all changes to the "elapse_time" field.
func (m *HttpLogMutation) ResetElapseTime() {
	m.elapse_time = nil
	m.addelapse_time = nil
	delete(m.clearedFields, httplog.FieldElapseTime)
}

// SetProcessElapseTime sets the "process_elapse_time" field.
func (m *HttpLogMutation) SetProcessElapseTime(i int64) {
	m.process_elapse_time = &i
	m.addprocess_elapse_time = nil
}

// ProcessElapseTime returns the value of the "process_elapse_time" field in the mutation.
func (m *HttpLogMutation) ProcessElapseTime() (r int64, exists bool) {
	v := m.process_elapse_time
	if v == nil {
		return
	}
	return *v, true
}

// OldProcessElapseTime returns the old "process_elapse_time" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldProcessElapseTime(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProcessElapseTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProcessElapseTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProcessElapseTime: %w", err)
	}
	return oldValue.ProcessElapseTime, nil
}

// AddProcessElapseTime adds i to the "process_elapse_time" field.
func (m *HttpLogMutation) AddProcessElapseTime(i int64) {
	if m.addprocess_elapse_time != nil {
		*m.addprocess_elapse_time += i
	} else {
		m.addprocess_elapse_time = &i
	}
}

// AddedProcessElapseTime returns the value that was added to the "process_elapse_time" field in this mutation.
func (m *HttpLogMutation) AddedProcessElapseTime() (r int64, exists bool) {
	v := m.addprocess_elapse_time
	if v == nil {
		return
	}
	return *v, true
}

// ClearProcessElapseTime clears the value of the "process_elapse_time" field.
func (m *HttpLogMutation) ClearProcessElapseTime() {
	m.process_elapse_time = nil
	m.addprocess_elapse_time = nil
	m.clearedFields[httplog.FieldProcessElapseTime] = struct{}{}
}

// ProcessElapseTimeCleared returns if the "process_elapse_time" field was cleared in this mutation.
func (m *HttpLogMutation) ProcessElapseTimeCleared() bool {
	_, ok := m.clearedFields[httplog.FieldProcessElapseTime]
	return ok
}

// ResetProcessElapseTime resets all changes to the "process_elapse_time" field.
func (m *HttpLogMutation) ResetProcessElapseTime() {
	m.process_elapse_time = nil
	m.addprocess_elapse_time = nil
	delete(m.clearedFields, httplog.FieldProcessElapseTime)
}

// SetIsError sets the "is_error" field.
func (m *HttpLogMutation) SetIsError(b bool) {
	m.is_error = &b
}

// IsError returns the value of the "is_error" field in the mutation.
func (m *HttpLogMutation) IsError() (r bool, exists bool) {
	v := m.is_error
	if v == nil {
		return
	}
	return *v, true
}

// OldIsError returns the old "is_error" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldIsError(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsError: %w", err)
	}
	return oldValue.IsError, nil
}

// ClearIsError clears the value of the "is_error" field.
func (m *HttpLogMutation) ClearIsError() {
	m.is_error = nil
	m.clearedFields[httplog.FieldIsError] = struct{}{}
}

// IsErrorCleared returns if the "is_error" field was cleared in this mutation.
func (m *HttpLogMutation) IsErrorCleared() bool {
	_, ok := m.clearedFields[httplog.FieldIsError]
	return ok
}

// ResetIsError resets all changes to the "is_error" field.
func (m *HttpLogMutation) ResetIsError() {
	m.is_error = nil
	delete(m.clearedFields, httplog.FieldIsError)
}

// SetCreatedAt sets the "created_at" field.
func (m *HttpLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *HttpLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *HttpLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetGoVersion sets the "go_version" field.
func (m *HttpLogMutation) SetGoVersion(s string) {
	m.go_version = &s
}

// GoVersion returns the value of the "go_version" field in the mutation.
func (m *HttpLogMutation) GoVersion() (r string, exists bool) {
	v := m.go_version
	if v == nil {
		return
	}
	return *v, true
}

// OldGoVersion returns the old "go_version" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldGoVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGoVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGoVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoVersion: %w", err)
	}
	return oldValue.GoVersion, nil
}

// ClearGoVersion clears the value of the "go_version" field.
func (m *HttpLogMutation) ClearGoVersion() {
	m.go_version = nil
	m.clearedFields[httplog.FieldGoVersion] = struct{}{}
}

// GoVersionCleared returns if the "go_version" field was cleared in this mutation.
func (m *HttpLogMutation) GoVersionCleared() bool {
	_, ok := m.clearedFields[httplog.FieldGoVersion]
	return ok
}

// ResetGoVersion resets all changes to the "go_version" field.
func (m *HttpLogMutation) ResetGoVersion() {
	m.go_version = nil
	delete(m.clearedFields, httplog.FieldGoVersion)
}

// SetPluginVersion sets the "plugin_version" field.
func (m *HttpLogMutation) SetPluginVersion(s string) {
	m.plugin_version = &s
}

// PluginVersion returns the value of the "plugin_version" field in the mutation.
func (m *HttpLogMutation) PluginVersion() (r string, exists bool) {
	v := m.plugin_version
	if v == nil {
		return
	}
	return *v, true
}

// OldPluginVersion returns the old "plugin_version" field's value of the HttpLog entity.
// If the HttpLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HttpLogMutation) OldPluginVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPluginVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPluginVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPluginVersion: %w", err)
	}
	return oldValue.PluginVersion, nil
}

// ClearPluginVersion clears the value of the "plugin_version" field.
func (m *HttpLogMutation) ClearPluginVersion() {
	m.plugin_version = nil
	m.clearedFields[httplog.FieldPluginVersion] = struct{}{}
}

// PluginVersionCleared returns if the "plugin_version" field was cleared in this mutation.
func (m *HttpLogMutation) PluginVersionCleared() bool {
	_, ok := m.clearedFields[httplog.FieldPluginVersion]
	return ok
}

// ResetPluginVersion resets all changes to the "plugin_version" field.
func (m *HttpLogMutation) ResetPluginVersion() {
	m.plugin_version = nil
	delete(m.clearedFields, httplog.FieldPluginVersion)
}

// Where appends a list predicates to the HttpLogMutation builder.
func (m *HttpLogMutation) Where(ps ...predicate.HttpLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HttpLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HttpLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.HttpLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HttpLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HttpLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (HttpLog).
func (m *HttpLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HttpLogMutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.hostname != nil {
		fields = append(fields, httplog.FieldHostname)
	}
	if m.method != nil {
		fields = append(fields, httplog.FieldMethod)
	}
	if m.url != nil {
		fields = append(fields, httplog.FieldURL)
	}
	if m.request_headers != nil {
		fields = append(fields, httplog.FieldRequestHeaders)
	}
	if m.request_body != nil {
		fields = append(fields, httplog.FieldRequestBody)
	}
	if m.status_code != nil {
		fields = append(fields, httplog.FieldStatusCode)
	}
	if m.response_headers != nil {
		fields = append(fields, httplog.FieldResponseHeaders)
	}
	if m.response_body != nil {
		fields = append(fields, httplog.FieldResponseBody)
	}
	if m.elapse_time != nil {
		fields = append(fields, httplog.FieldElapseTime)
	}
	if m.process_elapse_time != nil {
		fields = append(fields, httplog.FieldProcessElapseTime)
	}
	if m.is_error != nil {
		fields = append(fields, httplog.FieldIsError)
	}
	if m.created_at != nil {
		fields = append(fields, httplog.FieldCreatedAt)
	}
	if m.go_version != nil {
		fields = append(fields, httplog.FieldGoVersion)
	}
	if m.plugin_version != nil {
		fields = append(fields, httplog.FieldPluginVersion)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HttpLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case httplog.FieldHostname:
		return m.Hostname()
	case httplog.FieldMethod:
		return m.Method()
	case httplog.FieldURL:
		return m.URL()
	case httplog.FieldRequestHeaders:
		return m.RequestHeaders()
	case httplog.FieldRequestBody:
		return m.RequestBody()
	case httplog.FieldStatusCode:
		return m.StatusCode()
	case httplog.FieldResponseHeaders:
		return m.ResponseHeaders()
	case httplog.FieldResponseBody:
		return m.ResponseBody()
	case httplog.FieldElapseTime:
		return m.ElapseTime()
	case httplog.FieldProcessElapseTime:
		return m.ProcessElapseTime()
	case httplog.FieldIsError:
		return m.IsError()
	case httplog.FieldCreatedAt:
		return m.CreatedAt()
	case httplog.FieldGoVersion:
		return m.GoVersion()
	case httplog.FieldPluginVersion:
		return m.PluginVersion()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HttpLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case httplog.FieldHostname:
		return m.OldHostname(ctx)
	case httplog.FieldMethod:
		return m.OldMethod(ctx)
	case httplog.FieldURL:
		return m.OldURL(ctx)
	case httplog.FieldRequestHeaders:
		return m.OldRequestHeaders(ctx)
	case httplog.FieldRequestBody:
		return m.OldRequestBody(ctx)
	case httplog.FieldStatusCode:
		return m.OldStatusCode(ctx)
	case httplog.FieldResponseHeaders:
		return m.OldResponseHeaders(ctx)
	case httplog.FieldResponseBody:
		return m.OldResponseBody(ctx)
	case httplog.FieldElapseTime:
		return m.OldElapseTime(ctx)
	case httplog.FieldProcessElapseTime:
		return m.OldProcessElapseTime(ctx)
	case httplog.FieldIsError:
		return m.OldIsError(ctx)
	case httplog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case httplog.FieldGoVersion:
		return m.OldGoVersion(ctx)
	case httplog.FieldPluginVersion:
		return m.OldPluginVersion(ctx)
	}
	return nil, fmt.Errorf("unknown HttpLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HttpLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case httplog.FieldHostname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHostname(v)
		return nil
	case httplog.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case httplog.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case httplog.FieldRequestHeaders:
		v, ok := value.(map[string][]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestHeaders(v)
		return nil
	case httplog.FieldRequestBody:
		v, ok := value.(jsontext.Value)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestBody(v)
		return nil
	case httplog.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatusCode(v)
		return nil
	case httplog.FieldResponseHeaders:
		v, ok := value.(map[string][]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponseHeaders(v)
		return nil
	case httplog.FieldResponseBody:
		v, ok := value.(jsontext.Value)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResponseBody(v)
		return nil
	case httplog.FieldElapseTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetElapseTime(v)
		return nil
	case httplog.FieldProcessElapseTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProcessElapseTime(v)
		return nil
	case httplog.FieldIsError:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsError(v)
		return nil
	case httplog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case httplog.FieldGoVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoVersion(v)
		return nil
	case httplog.FieldPluginVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPluginVersion(v)
		return nil
	}
	return fmt.Errorf("unknown HttpLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HttpLogMutation) AddedFields() []string {
	var fields []string
	if m.addstatus_code != nil {
		fields = append(fields, httplog.FieldStatusCode)
	}
	if m.addelapse_time != nil {
		fields = append(fields, httplog.FieldElapseTime)
	}
	if m.addprocess_elapse_time != nil {
		fields = append(fields, httplog.FieldProcessElapseTime)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HttpLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case httplog.FieldStatusCode:
		return m.AddedStatusCode()
	case httplog.FieldElapseTime:
		return m.AddedElapseTime()
	case httplog.FieldProcessElapseTime:
		return m.AddedProcessElapseTime()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HttpLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case httplog.FieldStatusCode:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatusCode(v)
		return nil
	case httplog.FieldElapseTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddElapseTime(v)
		return nil
	case httplog.FieldProcessElapseTime:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProcessElapseTime(v)
		return nil
	}
	return fmt.Errorf("unknown HttpLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HttpLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(httplog.FieldHostname) {
		fields = append(fields, httplog.FieldHostname)
	}
	if m.FieldCleared(httplog.FieldMethod) {
		fields = append(fields, httplog.FieldMethod)
	}
	if m.FieldCleared(httplog.FieldURL) {
		fields = append(fields, httplog.FieldURL)
	}
	if m.FieldCleared(httplog.FieldRequestHeaders) {
		fields = append(fields, httplog.FieldRequestHeaders)
	}
	if m.FieldCleared(httplog.FieldRequestBody) {
		fields = append(fields, httplog.FieldRequestBody)
	}
	if m.FieldCleared(httplog.FieldStatusCode) {
		fields = append(fields, httplog.FieldStatusCode)
	}
	if m.FieldCleared(httplog.FieldResponseHeaders) {
		fields = append(fields, httplog.FieldResponseHeaders)
	}
	if m.FieldCleared(httplog.FieldResponseBody) {
		fields = append(fields, httplog.FieldResponseBody)
	}
	if m.FieldCleared(httplog.FieldElapseTime) {
		fields = append(fields, httplog.FieldElapseTime)
	}
	if m.FieldCleared(httplog.FieldProcessElapseTime) {
		fields = append(fields, httplog.FieldProcessElapseTime)
	}
	if m.FieldCleared(httplog.FieldIsError) {
		fields = append(fields, httplog.FieldIsError)
	}
	if m.FieldCleared(httplog.FieldGoVersion) {
		fields = append(fields, httplog.FieldGoVersion)
	}
	if m.FieldCleared(httplog.FieldPluginVersion) {
		fields = append(fields, httplog.FieldPluginVersion)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HttpLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HttpLogMutation) ClearField(name string) error {
	switch name {
	case httplog.FieldHostname:
		m.ClearHostname()
		return nil
	case httplog.FieldMethod:
		m.ClearMethod()
		return nil
	case httplog.FieldURL:
		m.ClearURL()
		return nil
	case httplog.FieldRequestHeaders:
		m.ClearRequestHeaders()
		return nil
	case httplog.FieldRequestBody:
		m.ClearRequestBody()
		return nil
	case httplog.FieldStatusCode:
		m.ClearStatusCode()
		return nil
	case httplog.FieldResponseHeaders:
		m.ClearResponseHeaders()
		return nil
	case httplog.FieldResponseBody:
		m.ClearResponseBody()
		return nil
	case httplog.FieldElapseTime:
		m.ClearElapseTime()
		return nil
	case httplog.FieldProcessElapseTime:
		m.ClearProcessElapseTime()
		return nil
	case httplog.FieldIsError:
		m.ClearIsError()
		return nil
	case httplog.FieldGoVersion:
		m.ClearGoVersion()
		return nil
	case httplog.FieldPluginVersion:
		m.ClearPluginVersion()
		return nil
	}
	return fmt.Errorf("unknown HttpLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HttpLogMutation) ResetField(name string) error {
	switch name {
	case httplog.FieldHostname:
		m.ResetHostname()
		return nil
	case httplog.FieldMethod:
		m.ResetMethod()
		return nil
	case httplog.FieldURL:
		m.ResetURL()
		return nil
	case httplog.FieldRequestHeaders:
		m.ResetRequestHeaders()
		return nil
	case httplog.FieldRequestBody:
		m.ResetRequestBody()
		return nil
	case httplog.FieldStatusCode:
		m.ResetStatusCode()
		return nil
	case httplog.FieldResponseHeaders:
		m.ResetResponseHeaders()
		return nil
	case httplog.FieldResponseBody:
		m.ResetResponseBody()
		return nil
	case httplog.FieldElapseTime:
		m.ResetElapseTime()
		return nil
	case httplog.FieldProcessElapseTime:
		m.ResetProcessElapseTime()
		return nil
	case httplog.FieldIsError:
		m.ResetIsError()
		return nil
	case httplog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case httplog.FieldGoVersion:
		m.ResetGoVersion()
		return nil
	case httplog.FieldPluginVersion:
		m.ResetPluginVersion()
		return nil
	}
	return fmt.Errorf("unknown HttpLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HttpLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HttpLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HttpLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HttpLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HttpLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HttpLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HttpLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown HttpLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HttpLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown HttpLog edge %s", name)
}
