// Code generated by ent, DO NOT EDIT.

package monitorchecklog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the monitorchecklog type in the database.
	Label = "monitor_check_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCertRemainingDays holds the string denoting the cert_remaining_days field in the database.
	FieldCertRemainingDays = "cert_remaining_days"
	// FieldResponseTimeMs holds the string denoting the response_time_ms field in the database.
	FieldResponseTimeMs = "response_time_ms"
	// FieldHTTPStatusCode holds the string denoting the http_status_code field in the database.
	FieldHTTPStatusCode = "http_status_code"
	// FieldLastCheckError holds the string denoting the last_check_error field in the database.
	FieldLastCheckError = "last_check_error"
	// EdgeDomain holds the string denoting the domain edge name in mutations.
	EdgeDomain = "domain"
	// Table holds the table name of the monitorchecklog in the database.
	Table = "monitor_check_logs"
	// DomainTable is the table that holds the domain relation/edge.
	DomainTable = "monitor_check_logs"
	// DomainInverseTable is the table name for the MonitoredDomain entity.
	// It exists in this package in order to avoid circular dependency with the "monitoreddomain" package.
	DomainInverseTable = "monitored_domains"
	// DomainColumn is the table column denoting the domain relation/edge.
	DomainColumn = "monitored_domain_check_logs"
)

// Columns holds all SQL columns for monitorchecklog fields.
var Columns = []string{
	FieldID,
	FieldCheckedAt,
	FieldStatus,
	FieldCertRemainingDays,
	FieldResponseTimeMs,
	FieldHTTPStatusCode,
	FieldLastCheckError,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "monitor_check_logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"monitored_domain_check_logs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCheckedAt holds the default value on creation for the "checked_at" field.
	DefaultCheckedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusUnknown is the default value of the Status enum.
const DefaultStatus = StatusUnknown

// Status values.
const (
	StatusOk      Status = "ok"
	StatusWarning Status = "warning"
	StatusError   Status = "error"
	StatusExpired Status = "expired"
	StatusUnknown Status = "unknown"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusOk, StatusWarning, StatusError, StatusExpired, StatusUnknown:
		return nil
	default:
		return fmt.Errorf("monitorchecklog: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MonitorCheckLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCertRemainingDays orders the results by the cert_remaining_days field.
func ByCertRemainingDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCertRemainingDays, opts...).ToFunc()
}

// ByResponseTimeMs orders the results by the response_time_ms field.
func ByResponseTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTimeMs, opts...).ToFunc()
}

// ByHTTPStatusCode orders the results by the http_status_code field.
func ByHTTPStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHTTPStatusCode, opts...).ToFunc()
}

// ByLastCheckError orders the results by the last_check_error field.
func ByLastCheckError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckError, opts...).ToFunc()
}

// ByDomainField orders the results by domain field.
func ByDomainField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainStep(), sql.OrderByField(field, opts...))
	}
}
func newDomainStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DomainTable, DomainColumn),
	)
}
