// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"cnb.cool/dtapp/certflow/internal/ent"
)

// The AuthMethodFunc type is an adapter to allow the use of ordinary
// function as AuthMethod mutator.
type AuthMethodFunc func(context.Context, *ent.AuthMethodMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AuthMethodFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AuthMethodMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AuthMethodMutation", m)
}

// The CAFunc type is an adapter to allow the use of ordinary
// function as CA mutator.
type CAFunc func(context.Context, *ent.CAMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CAFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CAMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CAMutation", m)
}

// The CertUploadFunc type is an adapter to allow the use of ordinary
// function as CertUpload mutator.
type CertUploadFunc func(context.Context, *ent.CertUploadMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CertUploadFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CertUploadMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CertUploadMutation", m)
}

// The CertificateFunc type is an adapter to allow the use of ordinary
// function as Certificate mutator.
type CertificateFunc func(context.Context, *ent.CertificateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CertificateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CertificateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CertificateMutation", m)
}

// The DNSProviderFunc type is an adapter to allow the use of ordinary
// function as DNSProvider mutator.
type DNSProviderFunc func(context.Context, *ent.DNSProviderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DNSProviderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DNSProviderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DNSProviderMutation", m)
}

// The DeployCredentialFunc type is an adapter to allow the use of ordinary
// function as DeployCredential mutator.
type DeployCredentialFunc func(context.Context, *ent.DeployCredentialMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DeployCredentialFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DeployCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DeployCredentialMutation", m)
}

// The DeployLogFunc type is an adapter to allow the use of ordinary
// function as DeployLog mutator.
type DeployLogFunc func(context.Context, *ent.DeployLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DeployLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DeployLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DeployLogMutation", m)
}

// The DeployTargetFunc type is an adapter to allow the use of ordinary
// function as DeployTarget mutator.
type DeployTargetFunc func(context.Context, *ent.DeployTargetMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DeployTargetFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DeployTargetMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DeployTargetMutation", m)
}

// The MonitorCheckLogFunc type is an adapter to allow the use of ordinary
// function as MonitorCheckLog mutator.
type MonitorCheckLogFunc func(context.Context, *ent.MonitorCheckLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MonitorCheckLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MonitorCheckLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MonitorCheckLogMutation", m)
}

// The MonitoredDomainFunc type is an adapter to allow the use of ordinary
// function as MonitoredDomain mutator.
type MonitoredDomainFunc func(context.Context, *ent.MonitoredDomainMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MonitoredDomainFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MonitoredDomainMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MonitoredDomainMutation", m)
}

// The NotificationFunc type is an adapter to allow the use of ordinary
// function as Notification mutator.
type NotificationFunc func(context.Context, *ent.NotificationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NotificationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.NotificationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NotificationMutation", m)
}

// The PasskeyCredentialFunc type is an adapter to allow the use of ordinary
// function as PasskeyCredential mutator.
type PasskeyCredentialFunc func(context.Context, *ent.PasskeyCredentialMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PasskeyCredentialFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PasskeyCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PasskeyCredentialMutation", m)
}

// The RenewalLogFunc type is an adapter to allow the use of ordinary
// function as RenewalLog mutator.
type RenewalLogFunc func(context.Context, *ent.RenewalLogMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RenewalLogFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RenewalLogMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RenewalLogMutation", m)
}

// The ScanResultFunc type is an adapter to allow the use of ordinary
// function as ScanResult mutator.
type ScanResultFunc func(context.Context, *ent.ScanResultMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ScanResultFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ScanResultMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ScanResultMutation", m)
}

// The TOTPCredentialFunc type is an adapter to allow the use of ordinary
// function as TOTPCredential mutator.
type TOTPCredentialFunc func(context.Context, *ent.TOTPCredentialMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TOTPCredentialFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TOTPCredentialMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TOTPCredentialMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
