// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CreateInput 创建/更新监控域名请求
 */
export interface CreateInput {
    /**
     * 域名
     */
    "domain": string;

    /**
     * 端口号
     */
    "port": number;

    /**
     * 检查类型：https/http
     */
    "check_type": string;

    /**
     * 自定义检查 URL
     */
    "url": string;

    /**
     * 检查间隔（秒）
     */
    "check_interval": number;

    /**
     * 是否启用
     */
    "enabled": boolean;
}

/**
 * MonitoredDomainItem 监控域名条目（前端展示用）
 */
export interface MonitoredDomainItem {
    /**
     * 监控 ID
     */
    "id": number;

    /**
     * 域名
     */
    "domain": string;

    /**
     * 端口号
     */
    "port": number;

    /**
     * 检查类型：https/http
     */
    "check_type": string;

    /**
     * 自定义检查 URL
     */
    "url": string;

    /**
     * 检查间隔（秒）
     */
    "check_interval": number;

    /**
     * 是否启用
     */
    "enabled": boolean;

    /**
     * 状态：ok/warning/error/expired/unknown
     */
    "status": string;

    /**
     * SSL 证书颁发者
     */
    "cert_issuer": string;

    /**
     * 证书生效时间
     */
    "cert_not_before": string;

    /**
     * 证书过期时间
     */
    "cert_not_after": string;

    /**
     * 证书 SHA256 指纹
     */
    "cert_fingerprint": string;

    /**
     * 证书主题
     */
    "cert_subject": string;

    /**
     * 签名算法
     */
    "cert_signature_algo": string;

    /**
     * 公钥算法
     */
    "cert_public_key_algo": string;

    /**
     * 公钥位数
     */
    "cert_public_key_bits": number;

    /**
     * SAN 列表
     */
    "cert_sans": string[] | null;

    /**
     * 剩余天数
     */
    "cert_remaining_days": number;

    /**
     * 最后检查时间
     */
    "last_check_at": string;

    /**
     * 最后检查错误
     */
    "last_check_error": string;

    /**
     * HTTP 响应码
     */
    "http_status_code": number;

    /**
     * 响应时间（毫秒）
     */
    "response_time_ms": number;

    /**
     * 创建时间
     */
    "created_at": string;

    /**
     * 更新时间
     */
    "updated_at": string;
}
