// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteOldHttpLog(ctx context.Context, createdAt sql.NullTime) (int64, error)
	InsertHttpLog(ctx context.Context, arg InsertHttpLogParams) error
}

var _ Querier = (*Queries)(nil)
