// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deleteOldHttpLog = `-- name: DeleteOldHttpLog :execrows
DELETE FROM http_log WHERE created_at < ?
`

func (q *Queries) DeleteOldHttpLog(ctx context.Context, createdAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldHttpLog, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertHttpLog = `-- name: InsertHttpLog :exec
INSERT INTO http_log (
    hostname,
    method,
    url,
    request_headers,
    request_body,
    status_code,
    response_headers,
    response_body,
    elapse_time,
    process_elapse_time,
    is_error,
    created_at,
    go_version,
    plugin_version
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertHttpLogParams struct {
	Hostname          *string
	Method            *string
	Url               *string
	RequestHeaders    sql.NullString
	RequestBody       []byte
	StatusCode        *int64
	ResponseHeaders   sql.NullString
	ResponseBody      []byte
	ElapseTime        *int64
	ProcessElapseTime *int64
	IsError           bool
	CreatedAt         sql.NullTime
	GoVersion         *string
	PluginVersion     *string
}

func (q *Queries) InsertHttpLog(ctx context.Context, arg InsertHttpLogParams) error {
	_, err := q.db.ExecContext(ctx, insertHttpLog,
		arg.Hostname,
		arg.Method,
		arg.Url,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.StatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.ElapseTime,
		arg.ProcessElapseTime,
		arg.IsError,
		arg.CreatedAt,
		arg.GoVersion,
		arg.PluginVersion,
	)
	return err
}
